### ISSUE TITLE
showcamera program issue

### ISSUE THREAD

**Issue by CWEastman** [TheImagingSource/tiscamera#100]
When running the ./showcamera command the program runs and recognizes the camera I have attached (DMK 22AUC03-F) and all the properties can be accessed. However, the screen is black and does not register any images coming through the camera.  There is also the issues of "Error: Could not negotiate format," as well as the error "Error: Device 'dev/video0' is busy." 

Has this happened to anyone before and is there a way to fix this?

**Comment by CWEastman** [comment]
<img width="1280" alt="screen shot 2017-06-27 at 1 42 00 pm" src="https://user-images.githubusercontent.com/29663725/27601751-6d3cf31c-5b3e-11e7-8492-1b042d369b70.png">


This is what I am seeing when I run the ./showcamera command

**Comment by CWEastman** [comment]
<img width="1170" alt="screen shot 2017-06-27 at 1 42 00 pm" src="https://user-images.githubusercontent.com/29663725/27601845-aff87a96-5b3e-11e7-95e9-ccdf8d4d63ae.png">


This is what I see when I run the ./showcamera command

**Comment by TIS-Stefan** [comment]
Hi again
Try lower frame rates

Try the pipeline

gst-launch-0.10 v4l2src ! video/x-raw-gray ! tisvideobufferfilter ! tis_auto_exposure ! tis_autofocus, auto=1 ! ffmpegcolorspace ! ximagesink

The showcamera sample is quite too complex to narrow down issues. 

Now I know, you use an Ubuntu.  So you do not need to answer in issue #99. Which computer model do you use?

However, why do you still use GStreamer 0.10?

**Comment by CWEastman** [comment]
Hi again, 

I use a MacBook Pro, and I didn't realize I was supposed to use a different GStreamer until now, I will change that.  I am new to setting up this camera.

**Comment by TIS-Stefan** [comment]
MacBook pro with Ubuntu Linux? 

The pipeline above, does it work on the comandline?
`gst-launch-0.10 v4l2src ! video/x-raw-gray ! tisvideobufferfilter ! tis_auto_exposure ! tis_autofocus, auto=1 ! ffmpegcolorspace ! ximagesink`

**Comment by CWEastman** [comment]
yes, I am running Ubuntu in a virtual box, sorry I did not mention that earlier.  The pipeline does not fully work, I have gotten the camera to see gray pixilations when I move it around but no clear image.

**Comment by CWEastman** [comment]
Never mind, I am back to the camera having the segmentation core dumped error.  I'm not sure what caused it to fail w like this again

**Comment by TIS-Stefan** [comment]
If you use "Parallels", you may have some problems with USB forwarding. I had this often on Mac OXs. It seems, you can not receive all image datablocks from the camera. So lets reduce the frame rate:

`gst-launch-0.10 v4l2src ! video/x-raw-gray,width=640,height=480,framerate=15/1 ! tisvideobufferfilter ! tis_auto_exposure ! tis_autofocus, auto=1 ! ffmpegcolorspace ! ximagesink
`

**Comment by CWEastman** [comment]
<img width="730" alt="screen shot 2017-06-28 at 12 23 18 pm" src="https://user-images.githubusercontent.com/29663725/27648473-aeb8afd4-5bfc-11e7-9709-b518123c098f.png">

OK, I used this pipeline but got this error

**Comment by TIS-Stefan** [comment]
Seems the device video0 does not exist. So you may disconnect and reconnect the camera.
With 
`ls /dev/vid*`
you will see, whether the camera is "video0" again.

**Comment by CWEastman** [comment]
Ok, I've gotten the camera back again after disconnecting it.  It is video0 again and this is what I am seeing.  I can click the start button and it says 'ready' and then I can also click the snap image button and nothing happens. 

<img width="1191" alt="screen shot 2017-06-29 at 2 54 26 pm" src="https://user-images.githubusercontent.com/29663725/27705134-f8ad8fae-5cda-11e7-9718-ca6673351ac4.png">

**Comment by CWEastman** [comment]
It is still fragile though, occasionally the segmentation error core dumped comes back.

**Comment by TIS-Stefan** [comment]
Well, I wanted you to use the last pipeline I had written for you. The showcamera program is far to complex for checking, whether we can get a live video in your environment.

**Comment by CWEastman** [comment]
When I used the pipeline you gave me previously, it did not work as well as the ones I have been using.

**Comment by TIS-Stefan** [comment]
OK. How to proceed now? 
Other question: Can you use GStreamer 1.0 instead of 0.10? 0.10 is somewhat outdated.
Last point: What exactly do you want to do with the camera and the images? I ask this, because I may can provide a better sample code for you.

Stefan

**Comment by TIS-Arne** [comment]
Closing this issue since we need feedback on Stefans last questions. Please re-open when neccessary.
