### ISSUE TITLE
Interfacing my GIGE mono chrome camera with OpenCV

### ISSUE THREAD

**Issue by louispetitjean** [TheImagingSource/tiscamera#107]
Hi, 
I just bought a GigE camera, and i'm currently trying to access it with an openCV capture function. I first fixed the camera's ip address and now i'm kind of stuck, cause the camera is unreachable. 
I know that it's possible to access a GigE camera thanks to this process, it works for exemple with a PtGrey GigE Camera. 
So do you have any clue why it's not working ? Or do you provide some facilities between opencv and your camera ? 
Best regards, Louis

**Comment by TIS-Arne** [comment]
@louispetitjean I am not sure what you mean with "unreachable". If the camera is not listed with "tcam-ctrl -l" then please try to start the "gige-daemon" first:

```
sudo systemctl start gige-daemon
tcam-ctrl -l
```

If the camera still can not be found by tcam-ctrl, then try the following command:

```
tcam-gigetool list
```

If this correctly detect the camera, please check the IP settings of the camera. 

If you need an example on how to interact with opencv, please let me know which programming language you are using.

**Comment by louispetitjean** [comment]
Hi, 
Sorry if i wasn't clear ! I can access to the camera with the aravis arv-viewer program, but i can't compile the tiscamera example. 
I'm using C++ i would be really glad if you could provide me some examples !

**Comment by louispetitjean** [comment]
Hi again, 
Last time you said you had an example using C++ and openCV, is it possible to see this example ?

**Comment by TIS-Arne** [comment]
Hi, 
there is no ready made sample. I am currently preparing one and will post it on this site tomorrow.

**Comment by louispetitjean** [comment]
Hi, 
Is the sample ready ?

**Comment by TIS-Stefan** [comment]
Sorry for the long delay of my answer. 

In the attachment is a C++ sample for GStreamer, our tiscamera modules and how to convert a GStBuffer to cv::Mat.
The interesting part is in main.cpp.

I hope, this helps. 
Stefan
[tcambin-autofocus.zip](https://github.com/TheImagingSource/tiscamera/files/1903143/tcambin-autofocus.zip)
