### ISSUE TITLE
Cannot capture images in OpenCV in UVC mode

### ISSUE THREAD

**Issue by nickaein** [TheImagingSource/tiscamera#11]
Hi,

I have a **DFK 42AUC03** camera and I want to grab images using OpenCV in Linux. Using **euvccam-fw** tool, I've updated the firmware to **dmk42uc03_143.euvc** and switched camera to UVC mode.

guvcview now gives a grayscale video stream in 1280x960. Here is log of running guvcview with --verbose switch: [http://textuploader.com/kleq](http://textuploader.com/kleq).

I couldn't find a way to get a color image in guvcview. Changing the **Camera output** to RGB3 caused guvcview to be closed with this error:

    libv4l2: error dequeuing buf: Invalid argument
    VIDIOC_DQBUF - Unable to dequeue buffer : Invalid argument

Also, I have a problem in capturing image using OpenCV. This simple code which capture image from the camera:

    #include <stdio.h>
    #include <opencv2/opencv.hpp>
    #include <iostream>
    using namespace cv;
    using namespace std;

    int main(int argc, char** argv )
    {
    	VideoCapture cap(0);
    	Mat img;

    	if(cap.isOpened())
    		cout << "Device opened." << endl;
    	else
    		cout << "Device not opened." << endl;
    
    	cap >> img;
    	if(!img.empty())
    	{
    		imwrite("frame.bmp",img);
    		cout << "Capture success!" << endl;
    	}
    	else
    	{
    		cout << "Capture failed." << endl;
    	}
    
    	return 0;
    }

Gives the following errors:

    libv4l2: error setting pixformat: Invalid argument
    HIGHGUI ERROR: libv4l unable to ioctl S_FMT
    libv4l2: error setting pixformat: Invalid argument
    libv4l1: error setting pixformat: Invalid argument
    HIGHGUI ERROR: libv4l unable to ioctl VIDIOCSPICT

    Device not opened.
    Capture failed.

I wonder if I should set some parameters before using **VideoCapture** object (I have tried settings resolution which didn't help and I couldn't find a way to set the pixel-format).

**Comment by mdxx** [comment]
Hello again, after some time. I want to ask you a critical question. I have DFK 23U274 and i tried it in windows with IC Capture 2.3. There i can snap images with Gain 9Db and Exposure time 2sec and 4,5 sec. In linux i use your C++. I saw from V4L2 API that i can have exposure time up to 30 secs, but in DFK 23U274 specs i read that i can use only up to 1/4sec . So i am wondering why in windows and in IC Capture 2.3 i can have a photo with 9DB and 2secs and in Linux i cannot. Can you help me pls with this final problem before my last tests?

Marios Dimiou
Date: Tue, 16 Dec 2014 02:45:22 -0800

**Comment by TIS-Stefan** [comment]
Hi

Unfortunately the spec of the DFK 23U274 is somewhat inexact about exposure times,

Please excuse this.

Stefan

**Comment by mdxx** [comment]
Goodmorning. In Linux i change exposure time at 7000 for example and i have timestamp. can i correct that somehow?

I saw in V4l2 that exposure value of 10.000 is 1sec

**Comment by TIS-Stefan** [comment]
Hi

I do not understand your question " In Linux i change exposure time at 7000 for example and i have timestamp. can i correct that somehow?" What is wrong, what should be corrected?

When I query the available properties of the DFK 23U274, then I get:

Property id 0x980913 name Gain min: 176, max: 1023
Property id 0x9a0902 name Exposure (Absolute) min: 1, max: 300000
Property id 0x199e201 name Exposure Time (us) min: 100, max: 30000000
Property id 0x199e204 name Gain (dB/100) min: 0, max: 3032
Property id 0x199e208 name Trigger Mode min: 0, max: 1
Property id 0x199e209 name Software Trigger min: 0, max: 0
Property id 0x199e210 name Trigger Delay min: 0, max: 128
Property id 0x199e211 name Strobe Enable min: 0, max: 1
Property id 0x199e212 name Strobe Polarity min: 0, max: 1
Property id 0x199e213 name Strobe Exposure min: 0, max: 1
Property id 0x199e214 name Strobe Duration min: 0, max: 10000
Property id 0x199e215 name Strobe Delay min: -10000, max: 10000
Property id 0x199e216 name GPOUT min: 0, max: 1
Property id 0x199e217 name GPIN min: 0, max: 1


BR
Stefan

**Comment by mdxx** [comment]
I have this part of code for exposure:
ctrl.id =V4L2_CID_EXPOSURE_ABSOLUTE;
    ctrl.value = 7000;
    ioctl(fd, VIDIOC_S_CTRL, &ctrl);

but when i am trying to snap a photo i have timestamp message. and i don't have a photo....
Date: Mon, 16 Feb 2015 02:08:25 -0800

**Comment by TIS-Stefan** [comment]
Hello

I suppose, your code is based on the V4l2 OpenCV sample, that we provided somewhere. I see a snaimage() call in one of the previous calls. I suppose, you want to set the exposure time to a longer value, so the image gets brighter.
The new exposure time is valid after a frame has been delivered by the camera.
So you should snap an image and discard it. The next should have the correct time,

I do not see a relation to "timestamp" here.

BR
Stefan

**Comment by mdxx** [comment]
Hello, i tried to work with IC Capture today and i had this message
              
I reconnecting it and it is the same. PLs tell me that my camera isn't broken.... :/

Date: Mon, 16 Feb 2015 02:20:28 -0800

**Comment by TIS-Stefan** [comment]
"Hello, i tried to work with IC Capture today and i had this message

I reconnecting it and it is the same. PLs tell me that my camera isn't broken.... :/"


What is "this message"?

**Comment by filesync** [comment]
>>If you only get a mono image you have a kernel prior to version 3.15. All kernel >= 3.15 have a fix >>I wrote that allows correct color interpretation. For older kernel you will have to reinterpret them >>manually. 

Hi, I have a 3.03 kernel and the same monochrome issue as described here. Can you please shed some more light on how to "reinterpret" these captures manually. Right now I have a bunch of *.mkv files that are all monochrome. I have tried converting them into RGB, avi using ffmpeg but couldn't get to extracting colored bmp out of those. Any help would be appreciated (good astronomical seeing is rare in my parts!).

**Comment by TIS-Stefan** [comment]
Mr filesync

could you please give some more context? Or create a new issue? This thread here is quite long

Stefan

**Comment by labreu** [comment]
@mdxx, 
could you share or explain your "set up(ind fd,ind exp,int gain)" function? I really need it =)
what type of variable is ctrl?
This function should be in v4ldevice.cpp, yea?

set up(ind fd,ind exp,int gain){
  **var? ctrl;**

  //setting exposure
  ctrl.id = V4L2_CID_EXPOSURE;
  ctrl.value = "an integer for exposure";
  ioctl(fd, VIDIOC_S_CTRL, &ctrl);

  //setting gain
  ctrl.id = V4L2_CID_GAIN;
  ctrl.value = "an integer for gain";
  ioctl(fd, VIDIOC_S_CTRL, &ctrl);
}

**Comment by labreu** [comment]
btw, I have a problem before the one above. I am getting images like this attached with this code: 
https://gist.github.com/TIS-Edgar/10f04501f49b6b3bf75e

All I changed:
* remove while loop and break
* added a function to save image, imwrite. And the saved image is exactly like the one in the cvShowImage output.
![result](https://cloud.githubusercontent.com/assets/10853158/7006864/e0015330-dc5a-11e4-9ff2-86cf85d3416b.png)

**Comment by TIS-Stefan** [comment]
Answer to your first question:

struct v4l2_control ctrl;
ctrl.id    = V4L2_CID_EXPOSURE;
ctrl.value = exposure;

v4l2_ioctl(fd, VIDIOC_S_PARM, &ctrl);

Please see also at http://linuxtv.org/downloads/v4l-dvb-apis/vidioc-g-ctrl.html

The Raspberry PI is somewhat weak to handle the images at high frame rate of your DFK 42. Therefore, you must lower the frame rate.

  struct v4l2_streamparm setfps;
  setfps.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
  setfps.parm.capture.timeperframe.numerator = 1;
  setfps.parm.capture.timeperframe.denominator = fps;
  v4l2_ioctl(fd, VIDIOC_S_PARM, &setfps);

I did not test this code on my own.

**Comment by labreu** [comment]
it worked, thanks @TIS-Stefan.

**Comment by gonewith** [comment]
Hi @TIS-Stefan 
I am using DFM 72BUC02-ML in ubuntu 14.04. I find here from google
I have asked technical supporter to update the firmware with dmk72uc02_162_uvc.euvc. is it correct?
Now I can get color pictures using the code you posted before at here: https://gist.github.com/10f04501f49b6b3bf75e but there is a problem: the color is not correct,for example, orange become blue ... I think Maybe I need change some parameters to adjust it in the code, so It 's not a big problem?

I have another important question: Do you have some C sample code Not c++ to get video stream? if you have not ,Do I need write it from V4L2 for my company embedded device(not not need GUI to display the Live image,only get the data to memory )?

Thank you very much for your reply very soon

peter zhang 

@TIS-Stefan
