### ISSUE TITLE
DBK Support

### ISSUE THREAD

**Issue by rodolfo-picoreti** [TheImagingSource/tiscamera#111]
Hi,
I have a **DBK21AUC03** camera and I'm trying to access it using this driver. The camera is shown in `lsusb`, but when I execute `tcam-ctrl -l` no devices are found. Is this model supported?

**Comment by TIS-Arne** [comment]
@rodolfo-picoreti I am sorry but this camera is not supported by the tiscamera software. You may get it to work with Linux by using my old "unicap" libraries which you can find here: https://github.com/unicap/unicap

However there is no support by The Imaging Source for this library and I do not really maintain it any more.
