### ISSUE TITLE
auto_exposure: gstreamer 1.0 doesn't support exposure-min property

### ISSUE THREAD

**Issue by g0hl1n** [TheImagingSource/tiscamera#116]
Commit 7e3838d45f1c80abd506ad6c599737b82ee20460 in the gstreamer-0.10 branch introduced the exposure-min property for auto_exposure. This property is missing in the gstreamer-1.0 implementation of auto_exposure.

Would it be possible to port this feature to the master branch?

Thanks & Regards,
Richard L.

**Comment by TIS-Arne** [comment]
You are right, this is a missing feature. We will port this feature to the master branch.

**Comment by g0hl1n** [comment]
Ok. Thanks. Do you already know when it will be available?

**Comment by g0hl1n** [comment]
Any updates/timeline on this issue?

**Comment by TIS-Edgar** [comment]
The feature is currently being tested. You can expect the feature by next week.

**Comment by TIS-Edgar** [comment]
Hi,
I pushed a preview branch:
https://github.com/TheImagingSource/tiscamera/tree/exposure-min

Can you try those changes and verify that everything works as you would expect?
After a few additional internal tests and your OK I would push them to master.

**Comment by g0hl1n** [comment]
Introduced to master in ddf7bc3271beaaf8d711330f8a183876d62f1fe1. Thanks.
