### ISSUE TITLE
Tool Tcam-capture... How can it save images?

### ISSUE THREAD

**Issue by cappelaere** [TheImagingSource/tiscamera#118]
There are no documentation on that tool that I can find.
Would be nice to have an example of a pipeline that can save images on a disk at some rate (and be able to turn it on/off).
It looks like tcam_capture/ImageSaver.py could do something like that... but how does it work from the GUI?
Thanks,
Pat.

**Comment by TIS-Arne** [comment]
tcam-capture application is subject to a major rework in the near future.
