### ISSUE TITLE
tcam-capture permission error

### ISSUE THREAD

**Issue by cappelaere** [TheImagingSource/tiscamera#119]
It tries to save a config file in a hardcoded directory that may not exist or you may not have permission to write to.  You have to dig in the code to find out what it is.
Search no longer: "/home/edt/.config/"

May want to change to "./.config", you may have better chance to pass this error and tackle the next one.

Looks like you could save imgs in a preferred directory...but dang if I can find out how to do this! 
PLEEEEEEAAAAAASE!!!!!!
Pat.

**Comment by TIS-Arne** [comment]
tcam-capture application is subject to a major rework in the near future.
