### ISSUE TITLE
Getting "VIDIOC_DQBUF error, Invalid Argument" on Linux kernel 3.0.36+

### ISSUE THREAD

**Issue by nickaein** [TheImagingSource/tiscamera#12]
Hi,

I get this error on kernel 3.0.36+:

> VIDIOC_DQBUF error 22, Invalid Argument

when I run the following example code (provided by @TIS-Edgar at #11) for capturing images:

https://gist.github.com/10f04501f49b6b3bf75e

After debugging, apparently at the line 109 of v4ldevice.cpp (inside **read_frame** function) this error occurs.

I checked capturing video of a webcam using [guvcview](http://guvcview.sourceforge.net) and it didn't any this problem.

**Comment by TIS-Stefan** [comment]
Issue closed, since there was no answer anymore.
