### ISSUE TITLE
Example Python TCam-Capture Special Dialog????

### ISSUE THREAD

**Issue by cappelaere** [TheImagingSource/tiscamera#120]
$python3 tcam-capture
Pick a device from Device tab
You get a properties dialog
Hit Special Tab
Any chance to get/find some explanation on that dialog?
What is that Software Trigger with no label on the button?  What does this do?
What about the strobe and GPIO options?
There is a formats tab you can click.  For my camera, it show GRAY8 and then points to frame rates.  If I select a frame rate, does it use it somehow?  How is that supposed to work?
Thanks,
Pat.

**Comment by TIS-Arne** [comment]
tcam-capture application is subject to a major rework in the near future.
