### ISSUE TITLE
DFK Z12GX236 Wont stream with stock examples

### ISSUE THREAD

**Issue by duddled** [TheImagingSource/tiscamera#124]
I am using Ubuntu 17.04.
Camera is on a static IP address connected directly to the PC with a POE injector.
MTU has been set to 9000.

When I try the command `gst-launch-1.0 tcambin ! videoconvert ! autovideosink` I get the terminal output:

> Setting pipeline to PAUSED ...
> Pipeline is live and does not need PREROLL ...
> Setting pipeline to PLAYING ...
> New clock: GstSystemClock

A empty window appears and when closed I get the terminal output 

> ERROR: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstXvImageSink:autovideosink0-actual-sink-xvimage: Output window was closed
> Additional debug info:
> xvimagesink.c(555): gst_xv_image_sink_handle_xevents (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstXvImageSink:autovideosink0-actual-> sink-xvimage
> Execution ended after 0:00:46.335956763
> Setting pipeline to PAUSED ...

When I use the command `gst-launch-1.0 tcambin ! video/x-raw,format=RGBx,width=1920,height=1200,framerate=10/1 ! videoconvert ! ximagesink`
The stream does work.

The C examples also have the same issue, when I run  ./properties I get the terminal output 

> Starting stream...
> Exposure Max has weird range. ignoring. min: 0 max: 0
> 
> (properties:1155): Gtk-CRITICAL **: gtk_scale_new_with_range: assertion 'min < max' failed
> 
> (properties:1155): Gtk-CRITICAL **: gtk_scale_set_draw_value: assertion 'GTK_IS_SCALE (scale)' failed
> 
> (properties:1155): Gtk-CRITICAL **: gtk_range_set_value: assertion 'GTK_IS_RANGE (range)' failed
> 
> (properties:1155): GLib-GObject-WARNING **: invalid (NULL) pointer instance
> 
> (properties:1155): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (properties:1155): Gtk-CRITICAL **: gtk_box_pack: assertion 'GTK_IS_WIDGET (child)' failed
> Exposure ROI Left has weird range. ignoring. min: 0 max: 4294967287
> Exposure ROI Width has weird range. ignoring. min: 8 max: 0
> Exposure ROI Top has weird range. ignoring. min: 0 max: 4294967287
> Exposure ROI Height has weird range. ignoring. min: 8 max: 0
> Focus ROI Left has weird range. ignoring. min: 0 max: 0
> Focus ROI Top has weird range. ignoring. min: 0 max: 0
> Focus ROI Width has weird range. ignoring. min: 0 max: 0
> Focus ROI Height has weird range. ignoring. min: 0 max: 0

The stream doesn't show but I can change the cameras properties.

When I modify line 120 from by `adding video/x-raw,format=RGBx,width=1920,height=1200,framerate=10/1`properties works.
```
pipeline = gst_parse_launch("tcambin name=src ! tee name=t t. ! queue ! valve name=valve ! 
videoconvert ! jpegenc ! multifilesink name=filesink post-messages=true location=/tmp/image-%06d.jpg 
t. ! queue ! videoconvert ! xvimagesink ", &err); 
```
to 
```
pipeline = gst_parse_launch("tcambin name=src ! tee name=t t. ! queue ! valve name=valve ! 
videoconvert ! jpegenc ! multifilesink name=filesink post-messages=true location=/tmp/image-%06d.jpg 
t. ! queue ! video/x-raw,format=RGBx,width=1920,height=1200,framerate=10/1 ! videoconvert ! 
xvimagesink ", &err); 
```

Is there some camera configuration that is not set that is preventing the camera from automatically getting the video format?

Thanks
Alex

**Comment by TIS-Stefan** [comment]
Hello and sorry for not answering. 

If only low frame rates work, then I guess, there is an issue with the PoE Injector, the network controller or software.

Therefore I need to know, which PoE injector and computer model is in use.
