### ISSUE TITLE
ARV_BUFFER_STATUS_TIMEOUT and Frame Rate 0

### ISSUE THREAD

**Issue by haseeb-uob** [TheImagingSource/tiscamera#127]
I am getting error ARV_BUFFER_STATUS_TIMEOUT . I also tried to increase timeout but still the same error. 
Please have a look at output of ./tests/arv-camera-test ./arv-camera-test -d stream:3. 
[arv_camera_test.txt](https://github.com/TheImagingSource/tiscamera/files/1458601/arv_camera_test.txt)

**Comment by TIS-Stefan** [comment]
Hello

First make sure, you use an GigE network and GigE devices. If your switch or PoE Injector supports 100mBit only, you wont get images.

Enable Jumbo Frames. It is done like the following:
`ip link set enp2s0 mtu 9000`
"enp2s0" is the name of your network controller.

These are my first guesses.

**Comment by haseeb-uob** [comment]
Yes, you are right. I am using a GigE switch with 1000mbps speed and also the mtu is 9000.

**Comment by TIS-Stefan** [comment]
The I must continue guessing....

what is the exposure time or is exposure set to automatic?
Is the external trigger disabled?
Is the IP configuration correct, so there are no conflicts?

**Comment by haseeb-uob** [comment]
Exposure time 10000
yes software and hardware trigger is disabled and I am using continuous mode
Yes, Ip configuration is fine. when I run ./arv-camera-test I could see the device properties, features etc...

**Comment by haseeb-uob** [comment]
sudo ethtool eth1 | grep Speed
Speed: 1000Mb/s

**Comment by TIS-Stefan** [comment]
Also the arv_viewer does not show an image?

**Comment by haseeb-uob** [comment]
nope. I can see the camera name but can't see any images.

**Comment by TIS-Stefan** [comment]
Which computer model / manufacturer do you use?
Which Linux version do you use?

**Comment by haseeb-uob** [comment]
Ubuntu 14.04 64 bit
Manufacturer: AES-HM76Z1FL
Processor Intel® Core™ i7-3517UE CPU @ 1.70GHz × 4 
RAM 8 GB

**Comment by TIS-Stefan** [comment]
Hello and sorry for not answering. 

I also should have looked in the "arv_camera_test.txt" you posted at start. 

The frame rate list of the camera seems to be wrong, so you must pass a valid frame rate to the camera. 

This should have been fixed with a newer firmware.

Stefan
