### ISSUE TITLE
Grabbing frames issue with DMx 31AU03.AS connected on USB 3.0 port

### ISSUE THREAD

**Issue by drupper** [TheImagingSource/tiscamera#129]
Hi, 
I have a DMx 31AU03.AS camera connected to a mini computer with only usb 3.0 ports.
I noticed that on that computer, I can't grab full frame. It seems that I only have half images.
When I tried to grab frames (with a custom program via v4l2, also used on the mini computer) on an older computer with only usb 2.0 ports, I can get full image. Do you know if it is possible to have this camera working by being connected on usb 3.0 port ? Is it possible that the usb 3.0 port causes this kind of issue ?

**Comment by TIS-Stefan** [comment]
Hello,

I am not really sure, whether the following hits your issue:

There is an incompatibility between the USB 2.0 CCD cameras and current Intel USB 3.0 controllers, which also control the USB 2.0 connectors of the computer. The cameras wont run with full frame rate. Only half frame rate of maximum available will provide images. 

Stefan
