### ISSUE TITLE
Example error on ubuntu 16.04

### ISSUE THREAD

**Issue by midjji** [TheImagingSource/tiscamera#131]
The readme proposes trying: 
install deps

cmake 
make 
make install

gst-launch-1.0 tcambin ! videoconvert ! autovideosink
which gives 
WARNING: erroneous pipeline: no element "tcambin"
no file named tcambin is created by the script

BUILD_TOOLS=ON
makes no difference.

**Comment by TIS-Stefan** [comment]
What about
`sudo make install`

**Comment by midjji** [comment]
Yeah did that too once irealized install prefix wasnt respected,

He issue is including that and with the default prefix.

**Comment by chutsu** [comment]
Can confirm that all the examples (C, C++, Python) do not work under Ubuntu 16.04 even after performing make install, it seems there is a fundamental problem with GStreamer not being able to access the camera. I have had some success in viewing images via `qv4l2` but not via the example code provided.

**Comment by TIS-Stefan** [comment]
I must admit, I am lost. I use Ubuntu 16.04. Our modules are working fine on my machine. 

If there is no element "tcambin", then something went wrong. Have you been able to compile and link the modules? with the command "make" in the "build" directory?

Stefan

**Comment by chutsu** [comment]
Ok, I think I resolved the issue, I forgot how I did it so I cannot explain here, I now have a different problem which I'll post a new issue.

**Comment by TIS-Stefan** [comment]
ok.
