### ISSUE TITLE
/dev/video0 is not generated

### ISSUE THREAD

**Issue by Nick-Zhang1996** [TheImagingSource/tiscamera#133]
Hi, I had everything working on my old PC with VMware workstation player and win7. I'm working with a new computer now (win10 + VMware) and after I installed everything according to the README.md I encountered this error, any idea?

Thanks

![dmesg](https://github.com/Nick-Zhang1996/test_module/blob/master/dmesg.png)

**Comment by TIS-Stefan** [comment]
Which camera model do you use?

**Comment by Nick-Zhang1996** [comment]
Thank you for your reply. I was using DFK 23U445, serial number 39710010

**Comment by Nick-Zhang1996** [comment]
Configured VMWare USB setting to be USB 3.0 and the problem is resolved.
