### ISSUE TITLE
Camera cannot run save-video examples

### ISSUE THREAD

**Issue by jie-zhou** [TheImagingSource/tiscamera#142]
Hello,

I'm trying to run the save-video example in /tiscamera/examples/c. I am using the DFK 23UX236 Camera and want to be able to control the saving of a stream. I compiled the file and when I run ./save-video it gives me the below error and nothing happens. A few of the other examples give this error as well.

**(save-video:20546): GStreamer-CRITICAL **: gst_caps_get_size: assertion 'GST_IS_CAPS (caps)' failed

(save-video:20546): GStreamer-CRITICAL **: gst_caps_get_size: assertion 'GST_IS_CAPS (caps)' failed
Press 'q' then 'enter' to stop the stream.**

Thanks,
Jie

**Comment by TIS-Stefan** [comment]
Hello

In most cases you can ignore these warnings. There should have been a file "/tmp/stream.ts" created, which is the saved video file.
