### ISSUE TITLE
Shutter Speed Control

### ISSUE THREAD

**Issue by tamrako** [TheImagingSource/tiscamera#143]
Hi everyone,
I'm using the DFK 23UX236 camera and I want to change the shutter speed to 10 microseconds. How would I go about doing this? I saw the shutter speed option for AFU420, is it similar to that? How would I implement this feature to the tcam_view example?
Thanks,
Tamra

**Comment by TIS-Stefan** [comment]
Hello

The shortest exposure time (shutter speed) is 15µs. The tcam-view example should already have a slider named "Exposure" which is the shutter time. Exposure automatic must be disabled in order to set  fixed exposure times.

**Comment by tamrako** [comment]
Thank you for your help, I appreciate it.
