### ISSUE TITLE
Min/Max-Exposure Values Units differ for gstreamer versions

### ISSUE THREAD

**Issue by g0hl1n** [TheImagingSource/tiscamera#156]
For the gstreamer 1.0 plugins the min and max-exposure is given in 1 µs units.
For the gsteramer 0.10 plugins the same value is given in 100 µs units.

Please harmonize these units! I'd prefer to use the 1 µs unit also for the gstreamer 0.10 plugins.

**Comment by TIS-Arne** [comment]
@g0hl1n I am sorry but the 0.10 plugins are discontinued. We do not plan to implement any new feature requests for the gstreamer-0.10 branch.
