### ISSUE TITLE
DFK 33GX236 (GIGE Color) on Jetson TX2 with PCIe-POE

### ISSUE THREAD

**Issue by nr-patel** [TheImagingSource/tiscamera#160]
My Hardware setup:
1. Jetson TX2 - Ubuntu 16.04
2. PCIe-POE : https://www.neousys-tech.com/en/product/feature/poe-poe/pcie-poe354at
3. DFK 33GX236 (GIGE Color) Camera
---
I have installed:
1. tiscamera
2. Aravis
---

Following errors, let me know what I am doing wrong:
1. $gst-launch-1.0 tcambin ! videoconvert ! autovideosink
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstTcamBin:tcambin0/GstTcamSrc:tcambin-source: Internal data flow error.
Additional debug info:
gstbasesrc.c(2948): gst_base_src_loop (): /GstPipeline:pipeline0/GstTcamBin:tcambin0/GstTcamSrc:tcambin-source:
streaming task paused, reason not-negotiated (-4)
Execution ended after 0:00:00.455284095
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
---
2. arv-test-0.6 
Testing device 'DFK 33GX236' from 'The Imaging Source Europe GmbH'
(process:9385): Aravis-CRITICAL **: arv_xml_schema_validate: assertion 'schema->priv->valid_ctxt != NULL' failed
(process:9385): Aravis-CRITICAL **: arv_xml_schema_validate: assertion 'schema->priv->valid_ctxt != NULL' failed
Genicam: FAILED Invalid Genicam XML data
Sensor size read: 1920 1200
---
3. /tiscamera/examples/gstreamer-1.0$ ./live-stream.sh 07814032
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstTcamSrc:tcamsrc0: Internal data flow error.
Additional debug info:
gstbasesrc.c(2948): gst_base_src_loop (): /GstPipeline:pipeline0/GstTcamSrc:tcamsrc0:
streaming task paused, reason not-negotiated (-4)
Execution ended after 0:00:00.826090115
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
---

Please suggest what went wrong in installation process.

**Comment by TIS-Stefan** [comment]
Hello and sorry for the late answer

First of all, I would like to to set the MTU to 9000 on the network controllers.

Then I would like you to set try different video formats and frame rates:
```
gst-launch-1.0 tcambin  ! video/x-raw, format=BGRA,width=640,height=480,framerate=30/1 ! videoconvert ! ximagesink

gst-launch-1.0 tcambin  ! video/x-raw, format=BGRA,width=1920,height=1200,framerate=10/1 ! videoconvert ! ximagesink

gst-launch-1.0 tcambin  ! video/x-raw, format=BGRA,width=1920,height=1200,framerate=30/1 ! videoconvert ! ximagesink
 ```
and so on up to framerate=50/1 until you get no more images. 

However, even the pipeline without specifying the video format runs fine on my Core i5.
Stefan
