### ISSUE TITLE
Some problems when "Trigger Mode" <case:444461>

### ISSUE THREAD

**Issue by AbnerCSZ** [TheImagingSource/tiscamera#171]
I run example/cpp/tcam_demo.cpp , and set the "Trigger Mode" is true. At the same time, I input a 32Hz signal to the camera. Unfortunately,  the rate of the callback function is **Slower than** 32Hz, just about 20Hz. I am sure that the exposure is smaller than 1/32(I set 12.7ms) and the 32Hz signal is stable. And I just printf time in the callback function. By the way, When I set the "Trigger Mode" is false, I can get the right rate(I set the frame rate is 60Hz).   
The strange thing is that I can run normally by /example/ROS/tiscamera.py. (The rate is 32Hz).  
Can you tell me why? Is it due to different modes of gstreamer?  
Thank you very much.

**Comment by TIS-Stefan** [comment]
Which camera do you use?
Also please keep in mind, on some cameras, the t exposure time and transport time (frame rate) sum up in trigger mode. In free running, exposure and transport of the previous image can run in parallel.

Stefan

**Comment by AbnerCSZ** [comment]
DFK 22BUC03  
What's mean " sum up in trigger mode"?  
But why can I get the 32Hz rate by ROS?

**Comment by TIS-Stefan** [comment]
> What's mean " sum up in trigger mode"?
Means: your 12.7ms exposure sum up with 16.7ms transport time = 29.4 ms. That is the estimated time for each image needed by the camera.  Therefore, the camera will not react on all trigger pulses, even if  the 29.4 seems to be shorter than the 31,25ms time interval of the trigger signal.

> But why can I get the 32Hz rate by ROS?
I have to admit, I do not know. Maybe something GStreamer inside? Maybe a color space transformation issue, that needs too much time? I can guess into the blue only.

Stefan

**Comment by AbnerCSZ** [comment]
I think i know why.  
When I use cpp demo, program did't close the **Auto Exposure**. And there is the code to close it in the ROS example/tis_rosstarter:
```
cam.set_property("Exposure Auto", False)
```
So how can I do it in the cpp demo?

**Comment by AbnerCSZ** [comment]
In addition, I know how to close it by command line:
```
cam-ctrl -p -s "Exposure Auto=false" <SERIAL>
```
I want to konw how to change it in code.  Likes  'cam.set' ?

**Comment by TIS-Stefan** [comment]
```
std::shared_ptr<Property> ExposureAuto = NULL;
std::shared_ptr<Property> Exposure= NULL;

cam.start();
ExposureAuto = cam.get_property("Exposure Auto");
Exposure = cam.get_property("Exposure");

ExposureAuto ->set(cam,false);
Exposure->set(cam,120);
```
Very important: Your camera has no automatics. Therefore, the software exposure automatic module is loaded after `cam.start()` and the automatic can be disabled after that.
I hope, the property names are correct. If not, an exception will be thrown.

Stefan

**Comment by AbnerCSZ** [comment]
Thanks for your help. I solved this problem. This is the result of the automatic exposure mode.
