### ISSUE TITLE
Trigger Mode <case:444486>

### ISSUE THREAD

**Issue by tsybaya** [TheImagingSource/tiscamera#172]
Hello,

I am using DMK 33GP2000e cameras, and in example example/cpp/tcam_demo.cpp I set "Trigger Mode" "On", but the camera does not react on it. I works such as trigger mode is disabled. This is a list of properties of current values.

```
button property 'Software Trigger': value = false default_value = false
enum property 'Trigger Activation': value = 'RisingEdge' default_value = 'RisingEdge' values = {FallingEdge, RisingEdge, }
enum property 'Trigger Source': value = 'Line1' default_value = 'Any' values = {Action0, Any, Line1, Software, }
enum property 'Trigger Mode': value = 'On' default_value = 'Off' values = {Off, On, }
enum property 'Trigger Selector': value = 'FrameStart' default_value = 'FrameStart' values = {FrameStart, }
```

I tried all variants of 'Trigger Source' property, but it still does not react. On the windows version everything is ok.
Thank you in advance.

**Comment by TIS-Stefan** [comment]
Hello
First of all, you need the trigger mode property:

`std::shared_ptr<Property> TriggerMode = cam.get_property("Trigger Mode");`

So far, so well, but the trick is, the trigger mode must be enabled *after* starting the video stream:
```
    // Start the camera
    cam.start();

    // Enable trigger mode. Must be done after the camera start, because 
    // Aravis likes to reset the trigger mode on camera start.
    TriggerMode->set(cam,"On");
```
And end the trigger mode, before the stream is stopped:
```
    // Before stopping the trigger mode must be disabled, because of a little
    // error in TcamCamera::stop()
    TriggerMode->set(cam,"Off");
    cam.stop();
```
However the last one will be fixed soon, so `cam.stop()` can be called, while trigger mode is on.

Stefan
