### ISSUE TITLE
Storing images in memory without saving them on a disk

### ISSUE THREAD

**Issue by Kolya96** [TheImagingSource/tiscamera#179]
Is here any ability to trigger image and get it into some variable (instead of saving to the file) for further use in opencv functions? 
(In C++ or C)

Thanks in advance.

**Comment by TIS-Stefan** [comment]
Hello

yes, that is possible. Simply check for the "appsink" Gstreamer module. https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gst-plugins-base-libs-appsink.html

Stefan

**Comment by Kolya96** [comment]
Thx.
