### ISSUE TITLE
what is GstClockTime timestamp <case:447163>

### ISSUE THREAD

**Issue by tahasadr** [TheImagingSource/tiscamera#182]
Hi TIS team,
What is timestamp provided by the below line in tcam_demo.cpp:
`GstClockTime timestamp = GST_BUFFER_PTS(buffer);`
Is it timestamp created by the camera?

**Comment by TIS-Stefan** [comment]
Hello

Currently the time stamps are generated by software and not by cameras.

Stefan

**Comment by tahasadr** [comment]
Hi @TIS-Stefan
Thanks for your reply.
How can i get the camera timestamp ?
There is another open issue about camera that.
you said that we can get it by aravis directly. could you help us to get camera timestamp by a sample code?

**Comment by TIS-Stefan** [comment]
Hello

I have to admit never used Aravis on my own.. However, I searched in the internet and found 
https://aravisproject.github.io/docs/aravis-0.4/ArvBuffer.html
There is a "arv_buffer_get_timestamp ()" on the "ArvBuffer". That should do the job.

Stefan
