### ISSUE TITLE
Unable to access white balancing on DFK 22BUC03 <case:447862>

### ISSUE THREAD

**Issue by danielofdaniels** [TheImagingSource/tiscamera#185]
I am unable to access the white balancing parameters on the DFK 22BUC03 camera under Ubuntu 16.04. I have followed the instructions on the wiki to update the firmware and enabled the uvc extension units. The only parameters accessible in Guvcview, v4l2-ctl, and tcam-ctrl are: brightness, gain, trigger_global_reset_shutter, exposure_absolute, focus_absolute, privacy, trigger, softwar_trigger, extio, x_offset, and y_offset.
Using the firmware-update tool I can see the firmware is version 201 and that UVC mode is on.

The camera is currently unusable due to the green tinge dominating everything. What have I failed to do to unlock the white balancing options in linux?

**Comment by TIS-Stefan** [comment]
Hello

the white balance of the DFK 22BUC03 is done with one of our GStreamer modules.  The camera itself has no white balance at all. White balancing is done in the computer by sotfware. Therefore, v4l2, guvcview can not see the white balance parameters.
