### ISSUE TITLE
Low frame rate

### ISSUE THREAD

**Issue by PrithviKambhampati** [TheImagingSource/tiscamera#187]
Hi,
I am using a GigE camera through a Power over Ethernet board to extract frames/videos. The POE board is connected through the PCIe lane to the Jetson TX2. I am only able to get a maximum of 8 frames per second from the camera. I am using gstreamer for this. Is there a reason for this? Have any of you encountered this issue before? Am I doing something wrong? If so, let me know the solution.

I am using the following code to get images:
1. Gstreamer command: 
gst-launch-1.0 tcambin serial='07814032' ! video/x-raw,format=BGRA,width=1920,height=1080,framerate=30/1 ! videoconvert ! ximagesink

I have tried different combinations of width, height, and framerate with no success.

I also have a python script which uses gstreamer library and opencv to read the frames but it is has a similar frame rate.

My Hardware setup:
Jetson TX2 - Ubuntu 16.04
PCIe-POE : https://www.neousys-tech.com/en/product/feature/poe-poe/pcie-poe354at
DFK 33GX236 (GIGE Color) Camera

I have installed:
tiscamera
Aravis

**Comment by TIS-Stefan** [comment]
Sorry for never giving an answer. But I wonder, whether the GigE Board works on the Jetson at all. I never tried that on my own.
