### ISSUE TITLE
Loaw frame rate and resolution on jetson tx2 and odroid xu3 with usb3.1 camera <case:448723>

### ISSUE THREAD

**Issue by tahasadr** [TheImagingSource/tiscamera#188]
Hi TIS team.
I tested my USB 3.1 board camera with odroid xu3 and jetson tx2 using aravis library through usb 3 port. In this situation i can't get more than 22 frame per second in 640*480 resolution.
Also I can't get full resolution (1440*1080) even with one fps.
When I install the camera on my PC I the video can be captured more than 100 fps over 1440x1080.
What is the problem? Is it USB port bottleneck (buffer size, driver, hardware, etc.) or lack of the CPU performance?

**Comment by TIS-Stefan** [comment]
I am not sure about the Odroid, but about the Tegra. I also do not know, which camera you use, which makes me guessing into the blue... so I guess, it is a 37U series.
[fw910.zip](https://github.com/TheImagingSource/tiscamera/files/2094542/fw910.zip)

In the zip file above is a firmware update, which you may need and a python file. The firmware
update should be done on a Windows PC.

The Jetson Tegra TX2 has a limited USB transfer size. Therefore, if I use a video resolution
above640x480, I will get half of expected frame rate only. Therefore, the USB block size must be set
in the camera. Please download the script from the above listed ftp link.

Usage:

1.) Install necessary Python packages:

sudo apt-get install libusb-dev python-usb

2.) Query the product ID of your camera:

lsusb

You will see an output containing a line similar to 
Bus 004 Device 011: ID 199e:9482 The Imaging Source Europe GmbH 

the "9482 " is needed as parameter to the python script.

3.) run the Python script:

sudo pythton2.7 ./limitmaxtransfersize.py 9482 

Output will be
Camera: 199e:9482 
Maximum payload transfer size is 1048592

This seems to work on all cameras, that are currently connected to the computer with the same
product ID.

Unfortunately this wont be saved permanently in the camera, therefore, each time, the computer
starts or the camera is connected, the script must be executed.

Stefan
