### ISSUE TITLE
Is it possible to modify GigE camera parameters from command line <case:448971>

### ISSUE THREAD

**Issue by yoelk** [TheImagingSource/tiscamera#192]
Hi,
I've installed tiscamera and can run the examples.
In the python examples, there is a way to access camera parameters (zoom/gain/etc.).
Is this possible also via command-line? Similar to what v4l2-ctl offers for USB cameras?

Thanks!

**Comment by TIS-Stefan** [comment]
Hi

yes, you can do that with the "tcam-ctrl" program.

Stefan

**Comment by yoelk** [comment]
Thanks!
