### ISSUE TITLE
Power line frequency setting for TIS cameras <case:449681>

### ISSUE THREAD

**Issue by yoelk** [TheImagingSource/tiscamera#196]
Hello,
In some USB cameras I've worked with in the past, there was a `power_line_frequency` setting, to set to 50 or 60 Hz. Does something similar exist for TIS cameras? Perhaps for some of them?

I believe it is used to filter out image flickering that might happen due of the power line frequency.

Thanks,
Joel

**Comment by TIS-Stefan** [comment]
Hello

No, the cameras do not have a flickering light frequency filter.

Stefan

PS: That is not a "tiscamera" issue. Questions like that are better placed at https://www.theimagingsource.com/company/contact/

**Comment by yoelk** [comment]
Thanks a lot!
