### ISSUE TITLE
Backup current FW version before flashing new one? <case:450168>

### ISSUE THREAD

**Issue by mrcg** [TheImagingSource/tiscamera#199]
Is there any possibility to make backup - by reading out from flash on Imaging Source camera - from current FW? This would be useful to have fallback option in case some issues happen with new FW.
Would be good to know how to generate this backup image.

Thanks for support.
Br
Christian

**Comment by TIS-Stefan** [comment]
Hello Christian

there is no backup of old firmware. But the firmwares are in the github repo and you can also ask me for versions.

Stefan
