### ISSUE TITLE
stropts.h dependency

### ISSUE THREAD

**Issue by TripackMcLovin** [TheImagingSource/tiscamera#209]
Having compiling issue on fedora core 27:

tiscamera/src/v4l2/dfk73.c:10:10: fatal error: stropts.h: No such file or directory
 #include <stropts.h>
          ^~~~~~~~~~~
compilation terminated.

After creating a blank stropts.h at /usr/inlcude, the build was completed without any issues. Since STREAM is not supported anymore, why the include is still there. Can we may get rid of it?

**Comment by TIS-Stefan** [comment]
stropts.h is a posix header that _may_ not be available on all systems.
RHEL based systems seem to particularly prone to this problem.
