### ISSUE TITLE
Getting Aravis example code work for DMK23G274 

### ISSUE THREAD

**Issue by nickaein** [TheImagingSource/tiscamera#21]
Hi,

I am trying to get stream from DMK23G274 in C++ code using Aravis library on the ARM board with Ubuntu server. I've downloaded Aravis 0.3.6 from the repository:

https://git.gnome.org/browse/aravis/snapshot/ARAVIS_0_3_6.tar.xz

and after installing various packages, I finally was able to configure, compile and install aravis:

    ./autogen.sh --enable-gst-0.10-plugin --enable-gst-plugin
    make
    make install 

The [aravis example](https://github.com/TheImagingSource/tiscamera/tree/master/examples/aravis) program now compiles, but running it gives the following error:

    gstaravis could not be created.

I tried to capture images using **gst-launch** tool:

    gst-launch-0.10 --gst-plugin-load=/root/ARAVIS_0_3_6/gst-0.10/.libs/libgstaravis-0.4.so aravissrc ! video/x-raw-gray,width=1600,height=1200,framerate=3/1 ! jpegenc ! filesink location=capture1.jpeg

By running this command I get the following output.

    Setting pipeline to PAUSED ...

    (gst-launch-0.10:30230): GStreamer-CRITICAL **: range start is not smaller than end for `GstIntRange'

    (gst-launch-0.10:30230): GStreamer-CRITICAL **: range start is not smaller than end for `GstIntRange'
    Pipeline is live and does not need PREROLL ...
    Setting pipeline to PLAYING ...
    New clock: GstSystemClock

This commands blocks until so I guess it has connected to the camera. However, the created **capture1.jpeg** is a zero-length file.

**Comment by TIS-Stefan** [comment]
Issue closed since there were no answers
