### ISSUE TITLE
DFK AFU420-CCS on RHEL / Fedora 27 <case:455631>

### ISSUE THREAD

**Issue by TripackMcLovin** [TheImagingSource/tiscamera#210]
Hi Edgar,

it seems I've a similar issue, having a DFK AFU420-CCS trying to run on fedora 27,
finally got the build (with empty stropts.h) complete but tcam-ctrl is telling me now "No devices found."

lsusb:
Bus 001 Device 006: ID 199e:8804 The Imaging Source Europe GmbH 

and dmesg after plugin:
[ 333.196725] usb 1-6: new SuperSpeed USB device number 4 using xhci_hcd
[  333.209577] usb 1-6: LPM exit latency is zeroed, disabling LPM.
[  333.210141] usb 1-6: New USB device found, idVendor=199e, idProduct=0804, bcdDevice= 0.0c
[  333.210146] usb 1-6: New USB device strings: Mfr=1, Product=2, SerialNumber=6
[  333.210150] usb 1-6: Product: DFK AFU420-CCS
[  333.210154] usb 1-6: Manufacturer: The Imaging Source Europe GmbH
[  333.210158] usb 1-6: SerialNumber: 507*****

added a udev-rule with 0666 to the TIS vid so that i've got for 
ls -l /dev/bus/usb/001/006
I've got
crw-rw-rw-. 1 root root 189, 5 Aug 28 16:59 /dev/bus/usb/001/006

so what am I missing or what should be the next step?

**Comment by TIS-Stefan** [comment]
I wonder, whether that was solved somehow.
