### ISSUE TITLE
erroneous pipeline: no element "tcambin" <case:457529>

### ISSUE THREAD

**Issue by rbrown-acertaralabs** [TheImagingSource/tiscamera#217]
1. Running Debian 9.5 (stretch)
2. Followed all instructions at https://github.com/theimagingsource/tiscamera
3. Build appears successful...see screenshot below.
4. Trying `gst-launch-1.0 tcambin ! videoconvert ! ximagesink` as indicated at URL from (2) above -- both as normal user and as sudo.
5. Getting error message:  `erroneous pipeline: no element "tcambin"`     (see screenshot below)
6. Note: I have NO cameras connected to my system...I am simply checking if the built binaries are running...I figured if they run with no cameras they would at least execute and report "no cameras found" or something along those lines.  Is that true?  

![z](https://user-images.githubusercontent.com/17712548/45851171-b46fc280-bcf6-11e8-9886-5fafe893218f.png)

**Comment by TIS-Stefan** [comment]
Hi 

Unfortunately you did not follow the instructions completele.
You forgot the "make" and the "sudo make install" step.

Stefan

**Comment by rbrown-acertaralabs** [comment]
My fault...I overlooked that.  Thank you!
