### ISSUE TITLE
How can I transfer tiscamera libraty from windows to Linux ? <case:457645>

### ISSUE THREAD

**Issue by hzback** [TheImagingSource/tiscamera#218]
In microsoft visual studio project, I use #include <tisudsh1.h>. But Ican't find this file after I install tiscamera library in Ubuntu system. 
How can I transfer tiscamera libraty from windows to Linux ?
Thanks a lot.

**Comment by TIS-Stefan** [comment]
I am very sorry, but the Linux approach differs from the Windows approach. The is no code compatibility.
That means, you must program the image acquisition again.
