### ISSUE TITLE
Release the memory in arvcameratest.c

### ISSUE THREAD

**Issue by hanabata** [TheImagingSource/tiscamera#22]
Hi,

I have a question about the release of the memory in arvcameratest.c of ARAVIS 0_3_3. I modified the program to handle several cameras with one program alternately. This program makes a loop that one camera takes a snapshot with a software trigger and the analysis of the image is done and then it goes to the next camera and do the same procedure. As a start point, I ran the program with only a single camera. Then I found the short of memory after some loops. I inserted system("free") to check how the amount of free memory is decreasing. I found that setting the callback function written in every loop might be suspicious. 
l.261 g_signal_connect (stream, "new-buffer", G_CALLBACK (new_buffer_cb), &data);

I guess that unset of the callback function or releasing the memory of "data" is necessary to avoid the problem. If you know anything, could you teach me how to do that?

**Comment by TIS-Stefan** [comment]
Hello

Sorry for the delay of my answer

I searched a little bit in the internet and found this sample:
http://code.metager.de/source/xref/gnome/DevelopmentTools/aravis/tests/arvexample.c

It looks like your sample. I guess, you used it too.

Some annotations:
As far as I know, it is totally wrong to do 
g_signal_connect (stream, "new-buffer", G_CALLBACK (new_buffer_cb), &data)
more than once. 
Move it out of the look you use in you main() function at 	while(cap_check<10){...}
The trick is setting up the Aravis library and callbacks and camera. Then you run the software trigger in the loop. If the loop has ended you clean up the Aravis and other things.

**Comment by TIS-Stefan** [comment]
Closed since there are no more answers.
