### ISSUE TITLE
Select binning mode? <case:457833>

### ISSUE THREAD

**Issue by midjji** [TheImagingSource/tiscamera#220]
Camera supports it? but cant find how to activate it.

**Comment by TIS-Stefan** [comment]
Which camera model do you use?

The binning / skipping property is name "Override Scanning Mode". Before it can be used a video format of half size must be set.
Some of the possible values in Override Scanning Mode do not fit to cameras. I suggest to try tcam-capture for testing this property.

**Comment by midjji** [comment]
Using dmk 33ux252

**Comment by midjji** [comment]
The dmk 33ux252
hmm there is only a single parameter, between 1,16 if I read it right,

shouldnt there be two, one for each binning factor, row col?

How do I compute what happens?

Den tis 25 sep. 2018 kl 16:41 skrev TIS-Stefan <notifications@github.com>:

**Comment by TIS-Stefan** [comment]
> hmm there is only a single parameter, between 1,16 if I read it right,
This is correct, the values enable the different possible binning / skipping modes.

> How do I compute what happens?
Try them the in the tcam-capture program. Set a 640x480 video format first. Currently I do not know the valid values.
