### ISSUE TITLE
Camera device time and trigger id values <case:457834>

### ISSUE THREAD

**Issue by midjji** [TheImagingSource/tiscamera#221]
In windows we can access the device time and the current trigger index since last the camera was set to trigger mode. (unless we read the docs wrong). How do I access these values in linux?

**Comment by TIS-Stefan** [comment]
You may let me know, which camera you use.

**Comment by TIS-Stefan** [comment]
I now know, which camera you use.

The additional data for each image as you mention above, is currently not available. First of all, the V4L2 does not support this frame information. Secondly , the tcambin does not have this implemented, also not for GigE cameras.
But if you use Aravis with USB3Vision directly, you could get access to this properties. I did not try this on my own.

**Comment by midjji** [comment]
Hi,
Isnt Aravis ethernet only? Any examples for something like what you mean?



Den tis 25 sep. 2018 kl 16:58 skrev TIS-Stefan <notifications@github.com>:

**Comment by midjji** [comment]
Nevermind I found it,
You say that isnt tested? which is the most stable ?

Den ons 26 sep. 2018 kl 12:55 skrev Mikael Persson <
mikael.p.persson@gmail.com>:

**Comment by TIS-Stefan** [comment]
> You say that isnt tested? which is the most stable ?
I said, I did not test that on my own. Aravis is not our project.

**Comment by midjji** [comment]
Do you fully support the genicam standard?

**Comment by TIS-Stefan** [comment]
> Do you fully support the genicam standard?

As far as I know, yes.
