### ISSUE TITLE
camera-ip-conf make failing -- best practice for includes

### ISSUE THREAD

**Issue by rbrown-acertaralabs** [TheImagingSource/tiscamera#222]
Trying to build `camera-ip-conf` at `/home/user/ansel/tiscamera/tools/camera-ip-conf` per the TIS Wiki here.

During the build, it cannot find various `.h` files -- there's likely a best-practice, here, but I am forgetting.  How should I setup the environment so that make and g++ properly find all needed `.h` files?

For example, I've done this, but it seems clunky and wrong (although it would eventually work):

First build/make error (no such file `Camera.h`):
![2018-09-25-175302_718x177_scrot](https://user-images.githubusercontent.com/17712548/46049601-91755200-c0ec-11e8-9987-5159aa7a634e.png)

Manually forcing it within `ConsoleManager.h` by suppliying a relative path to `Camera.h` does work but it just bubbles to the next `.h` that it cannot find:

![2018-09-25-175348_371x31_scrot](https://user-images.githubusercontent.com/17712548/46049630-aeaa2080-c0ec-11e8-9d0b-3283ae9d3bd7.png)

![2018-09-25-175402_725x211_scrot](https://user-images.githubusercontent.com/17712548/46049632-b1a51100-c0ec-11e8-9acf-137ac0ad1910.png)

I'm sure there is a better way, so I am simply asking for the best practice here to make the build/make work when it cannot find '.h' files.

There is the `-I` option for g++, but that would mean I am editing TIS makefiles, so that also seems clunky and wrong.

Perhaps the environment variables `CPATH` or `CPLUS_INCLUDE_PATH`?

**Comment by rbrown-acertaralabs** [comment]
Neither `CPATH` nor `CPLUS_INCLUDE_PATH` seem to work...

**Comment by rbrown-acertaralabs** [comment]
WAIT!  I was overcomplicating things!  I of course did all the steps under "Building tiscamera" and I just realized that all of the tools were built as part of that and placed under `builds`.  Well, I feel silly.  Closing this ticket.

**Comment by TIS-Stefan** [comment]
Hello 

Please do not feel silly. When I started with Linux coming from many years using Windows, I made the same errors as you. 

Stefan
