### ISSUE TITLE
White Balance Differences between Windows and Linux

### ISSUE THREAD

**Issue by rbrown-acertaralabs** [TheImagingSource/tiscamera#228]
I see a difference in color tone (white balance?) when comparing images from TIS "IC Capture 2.4" on Windows to images from Python/tiscamera/aravis/gstreamer on Linux...
* Image capture from "IC Capture 2.4" tool on Windows:

![001_connector_windows_ic_capture_rgb-69-64-126-lores](https://user-images.githubusercontent.com/17712548/46819062-ff9e5380-cd3f-11e8-906d-d41bae40f5ca.jpg)

* Image capture from Python and "tiscamera" libraries on Linux:

![002_connector_linux_python_tiscamera_rgb-69-64-126-lores](https://user-images.githubusercontent.com/17712548/46819066-0200ad80-cd40-11e8-8602-0b13afc14aae.jpg)

Notice the color difference, especially on the metallic portion of the connector in the image: the image from "IC Capture" is "warmer" and the image from "tiscamera" appears to be "bluer".

Inside "IC Capture 2.4", I queried the settings for gain, white balance (r,g,b), and exposure and then used those settings when capturing on Linux/tiscamera.  So both images are using the same camera, same lighting, and same camera setpoints.  One odd aspect was that "IC Capture" provides exposure in a fraction (1/128) whereas the tiscamera libraries accept an integer (e.g. 6000 was the "visual equivalent" of 1/128 ... is this int parameter in microseconds?  ifso, I should be using 7812usec = 1/128sec, but I doubt this exposure setting would significantly affect the color balance).

The "IC Capture" image appears to be truer to what the human eye sees.  I've adjusted white balance (r,g,b) in the Linux/tiscamera environment in an attempt make it match the "IC Capture" image, but I can't quite get there.  Is white balance (r,g,b) the only adjustment that could make these two images match, or are there other parameter(s) I should try?

**Comment by TIS-Stefan** [comment]
Hi Rob

I did not forget the email you already sent to me. The difference is, that the white balance in the Windows driver is far more sophisticated and includes proprietary knowledge about colors. This is not open source. 
Please see the mail I send to you.

Stefan
