### ISSUE TITLE
DMM 72BUC02-ML tcam-ctrl -l "No device found." on Linux <case:464019>

### ISSUE THREAD

**Issue by mihainicolae80** [TheImagingSource/tiscamera#232]
Hi,
I have a DMM 72BUC02-ML camera and I am trying to use it on Linux. I face a similar issue to this one "https://github.com/TheImagingSource/tiscamera/issues/91" which sadly ended abruptedly without a solution. When I run "tcam-ctrl -l" I get "No device founds" while having the camera plugged. 
When I run dmesg I can see that the OS detected the camera properly. I have copied the udev rules from "data/udev/80-theimagingsource-cameras.rules" to "/etc/udev/rules.d/" as sugested. I am using linux mint 18.3 but I also tried on a fresh install of Ubuntu 18.04 64bit (on an actual PC, not a VM).

**Comment by TIS-Stefan** [comment]
Hi

the DMM needs a firmware update in order to make it UVC compatible. Please follow the link at https://github.com/TheImagingSource/tiscamera/wiki/Getting-Started-with-USB-2.0-CMOS-Cameras.

The firmware file to be written in your camera is data\firmware\usb2\dmk72uc02_162_uvc.euvc

Stefan

**Comment by mihainicolae80** [comment]
Thx, that fixed the problem! As a side note, there is a missing link on the page https://github.com/TheImagingSource/tiscamera/wiki/First-Steps , look for [here] .
So, for the sake of completeness, in case some one else stumbles upon this, the story goes like this:
*The camera's stock firmware is not compatible with linux, thus the firmware has to be updated.
*To update the firmware you need to build the project from the Git repo, as the firmware-update tool is not provided otherwise. In order to do this:
1) Follow the instructions on the Git readme.md page to build the project. Link(at present time): https://github.com/TheImagingSource/tiscamera
2)The firmware-update utility might not get built so you may need to go in the repository folder in "build/tools/firmware-update/" and do a "sudo make".
3)Then use the utility to write the new firmware, this is well documented on the git wiki page: https://github.com/TheImagingSource/tiscamera/wiki/Getting-Started-with-USB-2.0-CMOS-Cameras

**Comment by TIS-Stefan** [comment]
Hi

Thank you for the change request of the readme. I forward this to the project manager.

Stefan
