### ISSUE TITLE
Camera image is not published using python script in examples/ROS <case:464778>

### ISSUE THREAD

**Issue by wep21** [TheImagingSource/tiscamera#234]
I try to publish image in ROS with DFK37AUX273, but image is not publish when executing ./tis_rosstarter.
The output is the following.
tcambin serial="47810526" name=source ! video/x-raw,format=BGRx,width=1920,height=1080,framerate=30/1 ! shmsink socket-path=/tmp/ros_mem

(python3:10777): GStreamer-CRITICAL **: gst_caps_get_structure: assertion 'index < GST_CAPS_LEN (caps)' failed

(python3:10777): GStreamer-CRITICAL **: gst_structure_get_value: assertion 'structure != NULL' failed

(python3:10777): GStreamer-CRITICAL **: gst_structure_set_value: assertion 'G_IS_VALUE (value)' failed

(python3:10777): GStreamer-CRITICAL **: gst_structure_get_value: assertion 'structure != NULL' failed

(python3:10777): GStreamer-CRITICAL **: gst_structure_set_value: assertion 'G_IS_VALUE (value)' failed

(python3:10777): GStreamer-CRITICAL **: gst_structure_get_value: assertion 'structure != NULL' failed

(python3:10777): GStreamer-CRITICAL **: gst_structure_set_value: assertion 'G_IS_VALUE (value)' failed
Press Enter to end program[ INFO] [1544692263.613193617]: Using gstreamer config from env: "shmsrc socket-path=/tmp/ros_mem ! video/x-raw, format=BGRx,width=1920,height=1080,framerate=30/1! videoconvert"
[ INFO] [1544692263.616918788]: using default calibration URL
[ INFO] [1544692263.616965951]: camera calibration URL: file:///home/daisuke/.ros/camera_info/camera.yaml
[ INFO] [1544692263.617008673]: Unable to open camera calibration file [/home/daisuke/.ros/camera_info/camera.yaml]
[ WARN] [1544692263.617023731]: Camera calibration file /home/daisuke/.ros/camera_info/camera.yaml not found.
[ INFO] [1544692263.617034853]: Loaded camera calibration from 
[ INFO] [1544692263.621753530]: Time offset: 1544687118.745
[ERROR] [1544693093.063864575]: poll failed with error Interrupted system call
^CTraceback (most recent call last):
  File "./tis_rosstarter", line 23, in <module>
    input("Press Enter to end program")
then press enter key,
KeyboardInterrupt
[FATAL] [1544696051.270307009]: Failed to PAUSE stream, check your gstreamer configuration.
[FATAL] [1544696051.270393120]: Failed to initialize gscam stream!
I guess there is something wrong with config.
I was able to get image with gs-launch-1.0.
Someone has any solution for this?
Thanks in advance!

**Comment by TIS-Stefan** [comment]
Hello

Unfortunately I answer with a question. Does the pipeline

`tcambin serial="47810526" name=source ! video/x-raw,format=BGRx,width=1920,height=1080,framerate=30/1 ! videoconvert ! ximagesink`

Provide an image?

Which computer do you use?

Stefan

**Comment by wep21** [comment]
Hi, thank you fot your reply!
I set the pipeline as you said but no image would appear.
The output is following.
tcambin serial="47810526" name=source ! video/x-raw,format=BGRx,width=1920,height=1080,framerate=30/1 ! videoconvert ! ximagesink

(python3:20875): GStreamer-CRITICAL **: gst_caps_get_structure: assertion 'index < GST_CAPS_LEN (caps)' failed

(python3:20875): GStreamer-CRITICAL **: gst_structure_get_value: assertion 'structure != NULL' failed

(python3:20875): GStreamer-CRITICAL **: gst_structure_set_value: assertion 'G_IS_VALUE (value)' failed

(python3:20875): GStreamer-CRITICAL **: gst_structure_get_value: assertion 'structure != NULL' failed

(python3:20875): GStreamer-CRITICAL **: gst_structure_set_value: assertion 'G_IS_VALUE (value)' failed

(python3:20875): GStreamer-CRITICAL **: gst_structure_get_value: assertion 'structure != NULL' failed

(python3:20875): GStreamer-CRITICAL **: gst_structure_set_value: assertion 'G_IS_VALUE (value)' failed
Press Enter to end program[ INFO] [1545018285.127409902]: Using gstreamer config from env: "shmsrc socket-path=/tmp/ros_mem ! video/x-raw, format=BGRx,width=1920,height=1080,framerate=30/1! videoconvert"
[ INFO] [1545018285.132188780]: using default calibration URL
[ INFO] [1545018285.132232142]: camera calibration URL: file:///home/daisuke/.ros/camera_info/camera.yaml
[ INFO] [1545018285.132286229]: Unable to open camera calibration file [/home/daisuke/.ros/camera_info/camera.yaml]
[ WARN] [1545018285.132308073]: Camera calibration file /home/daisuke/.ros/camera_info/camera.yaml not found.
[ INFO] [1545018285.132323782]: Loaded camera calibration from 
[ INFO] [1545018285.138949432]: Time offset: 1544933483.411
[FATAL] [1545018285.139084451]: Failed to PAUSE stream, check your gstreamer configuration.
[FATAL] [1545018285.139104487]: Failed to initialize gscam stream!

I use DELL XPS15 laptop PC.

**Comment by TIS-Stefan** [comment]
Hello

The pipeline I have posted should provide an image on the screen, not in ROS. I posted the pipeline in order to see, whether you got an image at all. As you can see from this pipeline, there is nothing in, what writes into a memory sink.

Also I found, the video can not be shown, because the wrong resolution is set. Maximum is 1440x1080 pixels, while you and I (very bad) 1920x1080.

Please try on the command line:
`gst-launch-1.0 tcambin serial="47810526"  ! video/x-raw,format=BGRx,width=1440,height=1080,framerate=30/1 ! videoconvert ! ximagesink
`
Stefan

**Comment by wep21** [comment]
Thank you for your advice!
I can see the image with that command.
Do you know how to see the image on ROS with gscam?

**Comment by TIS-Stefan** [comment]
Hello

It should work in the same way by specifying the correct video format in the pipeline 

`tcambin serial="47810526" name=source ! video/x-raw,format=BGRx,width=1440,height=1080,framerate=30/1 ! shmsink socket-path=/tmp/ros_mem
`
Stefan

**Comment by wep21** [comment]
I executed ./tis_rosstarter with the pipeline above.
Image topisc seems to appear in rostopic list, but I cannot see images on rqt_image_view.

tcambin serial="47810526" name=source ! video/x-raw,format=BGRx,width=1440,height=1080,framerate=30/1 ! shmsink socket-path=/tmp/ros_mem
Press Enter to end program[ INFO] [1545104976.954984777]: Using gstreamer config from env: "shmsrc socket-path=/tmp/ros_mem ! video/x-raw, format=BGRx,width=1440,height=1080,framerate=30/1! videoconvert"
[ INFO] [1545104976.958616987]: using default calibration URL
[ INFO] [1545104976.958650851]: camera calibration URL: file:///home/daisuke/.ros/camera_info/camera.yaml
[ INFO] [1545104976.958724728]: Unable to open camera calibration file [/home/daisuke/.ros/camera_info/camera.yaml]
[ WARN] [1545104976.958761081]: Camera calibration file /home/daisuke/.ros/camera_info/camera.yaml not found.
[ INFO] [1545104976.958774963]: Loaded camera calibration from 
[ INFO] [1545104976.962970238]: Time offset: 1545102603.234
[ INFO] [1545104976.996078085]: Publishing stream...
[ INFO] [1545104976.996189523]: Started stream.

(gscam:9315): GStreamer-CRITICAL **: gst_caps_get_structure: assertion 'GST_IS_CAPS (caps)' failed

(gscam:9315): GStreamer-CRITICAL **: gst_structure_get_int: assertion 'structure != NULL' failed

(gscam:9315): GStreamer-CRITICAL **: gst_structure_get_int: assertion 'structure != NULL' failed
[ WARN] [1545104976.996257095]: GStreamer image buffer underflow: Expected frame to be 1932623616 bytes but got only 6220800 bytes. (make sure frames are correctly encoded)

Do you have any thoughts?

**Comment by TIS-Stefan** [comment]
6220800 is 1440x1080*4, which is the expected image size at BGRx, but the pipeline in tiscamera.py is RGB.  That means, the image should have 4665600 bytes only.  
However, your pipeline uses BGRx. But the pipeline for GSCam uses 24 bits / RGB. Therefore you have a conflict. But in the script tiscamera.py the BGRx to RGB converted.

Edit the tis_rosstarter script and change the line
`cam = tiscamera.Camera("17719924", 1920, 1080, 30, True, False)`
to
`cam = tiscamera.Camera("47810526", 1440, 1080, 30, True, False)`

If you run "tis_rosstarter", you should see an own window opening and showing a live stream. Does this happen?

However, I wonder, why gscam expected 190MB image size... maybe this is gone with the Python script changed as shown above..

Stefan

**Comment by wep21** [comment]
I can see the image on ROS. Thank you for your advice!
