### ISSUE TITLE
Getting a software event when the camera is disconnected <case:465514>

### ISSUE THREAD

**Issue by yoelk** [TheImagingSource/tiscamera#236]
Hello,
I'm using a `GIGE29 WUXGA M Z12` camera, with tiscamera and its python bindings.
I'd like to ask, how can I get an indication in software when a camera is suddenly unreachable (e.g. the Ethernet cable got disconnected).
Is there some keepalive mechanism to check? I've noticed that when I use gstreamer (`gst-launch-1.0 tcambin serial=41810580 ! video/x-raw,format=GRAY8,width=1640,height=1080,framerate=18/1 ! videoconvert ! ximagesink sync=false`) and I disconnect the camera, gstreamer notices it and closes itself, so I imagine there must be a way to do it.

Thanks,
Joel

**Comment by TIS-Stefan** [comment]
Hello

The device lost event is handled by the GStreamer message bus:

```
bus = pipeline.get_bus()
bus.add_signal_watch()
bus.connect('message::error', on_error)
```
The on_error function contains:

```
     def on_error(bus, msg):
            """
            Callback for gst bus messages
            Receives errors and chooses appropriate actions
            """
            err, dbg = msg.parse_error()

            if msg.src.get_name() == "tcambin-source":

                  if err:

                        if err.message == "Device lost":
                              log.error("Received device lost message")
                              fire_device_lost()
```

The code was copied from tcam-capture.
Stefan
