### ISSUE TITLE
tiscamera doesn't have format setting and properties <case:465541>

### ISSUE THREAD

**Issue by ngotra2710** [TheImagingSource/tiscamera#237]
When I type `tcam-ctrl -l `in the command line, the result:
```
Available devices:
Model		Type	Serial
DFK 23G445	Aravis	50414275
```
After that, I try `tcam-ctrl -f 50414275`, the result:
`Available format settings:`
And nothing happens...
I also try `tcam-ctrl -p 50414275` and
`Found 0 propert(y/ies)`
`tcam-ctrl -c 50414275`
`Unable to display caps. Conversion failed.`

I also try to set the format of the camera but it doesn't help. What should I have to do to fix this problem?
Thank you very much.

p/s: I use Ubuntu 18.04.1 LTS.

**Comment by TIS-Stefan** [comment]
Hello

Maybe it is a firmware issue, your camera seems to be quite old.

[GigECamFirmware.606.zip](https://github.com/TheImagingSource/tiscamera/files/2732312/GigECamFirmware.606.zip)

The firmware can be uploaded with the "camera-ip-config" tool into the camera.

Stefan
