### ISSUE TITLE
Not compatible with Qt

### ISSUE THREAD

**Issue by jhihn** [TheImagingSource/tiscamera#253]
import QtQuick 2.12
import QtQuick.Window 2.12
import QtMultimedia 5.12

Window {
    visible: true
    width: 640
    height: 480
    title: qsTr("Hello World")
    Camera {
        id: camera
    }
    VideoOutput {
        source: camera
        anchors.fill: parent
    }
    Component.onCompleted: console.log(JSON.stringify(QtMultimedia.availableCameras))
}
// Output: 
qml: [{"deviceId":"/dev/video0","displayName":"DFK 27AUJ003","position":0,"orientation":0}]
Unable to query the parameter info: "Invalid argument"
Unable to query the parameter info: "Invalid argument"
Unable to query the parameter info: "Invalid argument"
Unable to query the parameter info: "Invalid argument"
Unable to query the parameter info: "Invalid argument"
libv4l2: error set_fmt gave us a different result then try_fmt!
CameraBin error: "Device '/dev/video0' cannot capture in the specified format"

**Comment by TIS-Stefan** [comment]
I already answered by Email. I would appreciate, if we use only one channel for communication, so we do not need to write all twice.

Stefan
