### ISSUE TITLE
Raspberry PI 2 not able to access some camera properties, cannot set <White Balance Auto >mode 

### ISSUE THREAD

**Issue by xiat5** [TheImagingSource/tiscamera#256]
$ tcam-ctrl -p 33714614
Found 9 propert(y/ies)
Brightness                              (int) min=0 max=255 step=1 default=-8193 value=12 category=Exposure
Gain                                    (int) min=4 max=63 step=1 default=57343 value=36 category=Exposure
Trigger Global Reset Shutter            (bool) default=false value=false category=Unknown
Exposure                                (int) min=100 max=30000000 step=100 default=12700 value=12700 category=Exposure
Focus                                   (int) min=0 max=1000 step=1 default=57343 value=0 category=Lens
Trigger Mode                            (bool) default=false value=false category=Special
Software Trigger                        (button) category=Special
X Offset                                (int) min=0 max=1794 step=2 default=12287 value=0 category=Unknown
Y Offset                                (int) min=0 max=1464 step=2 default=12287 value=0 category=Unknown
-------------------------------------
how to close the White Balance Auto,and how to set Gain R ，Gain G,Gain  B？

**Comment by TIS-Stefan** [comment]
Some properties are available, after the pipeline with tcambin have been started. Because they are done by GStreamer modules, which are not used by tcam-ctrl.

You can start the pipeline and use tcam-ctrl in parallel.
