### ISSUE TITLE
Changing capture format to 16-bit Monochrome

### ISSUE THREAD

**Issue by userinv** [TheImagingSource/tiscamera#258]
I am using a DMX 33UX252 camera and I want to change the capture format from 'BGRx' to 16-bit monochrome. How can I output the different capture formats for this camera?

**Comment by TIS-Stefan** [comment]
You can use 
`tcam-ctrl -c <serial of your camera>`
 on the console for a list of all formats.

The 16 /12 bit format is named "GRAY16_LE".

Stefan
