### ISSUE TITLE
DFK 33UJ003

### ISSUE THREAD

**Issue by MChow1** [TheImagingSource/tiscamera#261]
I want to handle the camera settings using opencv for detection application. The camera is completly zoomed and due to which i have to place the objects at a real far distance which ideally should not be the case. I started with the dependencies installation using (https://github.com/TheImagingSource/tiscamera) **Building tiscamera**. During this step:

# With ARAVIS:
cmake -DBUILD_ARAVIS=ON -DBUILD_GST_1_0=ON -DBUILD_TOOLS=ON -DBUILD_V4L2=ON -DCMAKE_INSTALL_PREFIX=/usr ..
# Without ARAVIS
cmake -DBUILD_ARAVIS=OFF -DBUILD_GST_1_0=ON -DBUILD_TOOLS=ON -DBUILD_V4L2=ON -DCMAKE_INSTALL_PREFIX=/usr ..

i get this error:

>  ~/tiscamera/build$ cmake -DBUILD_ARAVIS=ON -DBUILD_GST_1_0=ON -DBUILD_TOOLS=ON -DBUILD_V4L2=ON -DCMAKE_INSTALL_PREFIX=/usr ..
> CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
>   A required package was not found
> Call Stack (most recent call first):
>   /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
>   cmake/modules/FindGObjectIntrospection.cmake:39 (pkg_check_modules)
>   src/gobject/CMakeLists.txt:20 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/tiscamera/build/CMakeFiles/CMakeOutput.log".

I have no clue with this as a beginner, any suggestion would be of great help.

**Comment by TIS-Stefan** [comment]
Hello 

Please checkout the "development" branch. In this branch the problem is solved.

Stefan

**Comment by MChow1** [comment]
How do i do that?
I wanted help with camera settings

**Comment by TIS-Stefan** [comment]
Hello

I am not a git usage trainer....

However, change into your tiscamera directory. Enter
git checkout development
cd build 
make -j

And see, what happens.
Stefan
