### ISSUE TITLE
Saving and Displaying Video Simultaneously Using Gstreamer

### ISSUE THREAD

**Issue by userinv** [TheImagingSource/tiscamera#262]
I am using a DMK 33UX252 to save and display live video. Within tcamcamera.cpp theres existing code under `enable_video_display(GstElement *displaysink)` which allows live video to be displayed on my laptop. However, I read through Gstreamer documentation and examples to write a separate function which also saves the live video in parallel. 

Here is the code. I included the function within `enable_video_display` so it is easier to read:
```
void
TcamCamera::enable_video_display(GstElement *displaysink)
{
  if(displaybin_)
      return;
  displaybin_ = gst_element_factory_make("bin", nullptr);
  GstElement *queue = gst_element_factory_make("queue", nullptr);
  GstElement *convert = gst_element_factory_make("videoconvert", nullptr);
  GstElement *capsfilter = gst_element_factory_make("capsfilter", nullptr);
  gst_bin_add(GST_BIN(pipeline_), displaybin_);
  gst_bin_add_many(GST_BIN(displaybin_), queue, convert, capsfilter, displaysink, nullptr);
  if (!gst_element_link_many(tee_, queue, convert, capsfilter, displaysink, nullptr))
      throw std::runtime_error("Could not link 'display' elements");
  
  //starting of my code
  if(savevideobin_)
    return;
  savevideobin_ = gst_element_factory_make("bin", nullptr);
  GstElement *queue2 = gst_element_factory_make("queue", nullptr);
  GstElement *convert2 = gst_element_factory_make("videoconvert", nullptr);
  GstElement *x264enc = gst_element_factory_make("x264enc", nullptr);
  GstElement *videomux = gst_element_factory_make("flvmux", nullptr);
  GstElement *filesink = gst_element_factory_make("filesink", nullptr);
  g_object_set(G_OBJECT(filesink), "location", "./output/video.flv", nullptr);
  gst_bin_add(GST_BIN(pipeline_), savevideobin_);
  gst_bin_add_many(GST_BIN(savevideobin_), queue2, convert2, x264enc, videomux, filesink, nullptr);
  if(!gst_element_link_many(tee_, queue2, convert2, x264enc, videomux, filesink, nullptr))
    throw std::runtime_error("Could not link 'savevideo' elements");
  std::cout << "end of enable_video_display" << std::endl;
}
```

When I execute the program, these functions are executed in the following order.. (these functions are found under `tcamcamera.cpp`)

1. `TcamCamera::TcamCamera(std::string serial = "");`
2. `cam->set_capture_format(format, size, rate);`
3. `cam->set_new_frame_callback(CameraConfig::new_frame_cb, &frameData);`
4. `cam->enable_video_display(gst_element_factory_make("ximagesink", NULL));`
5. `cam->start();`

The program hangs at `gst_element_get_state(pipeline_, NULL, NULL, GST_CLOCK_TIME_NONE);` which is located in `start()` but a popup window opens that is supposed to display the video. However, the popup is stuck on a single frame and an empty output_video.flv is also created.

When I comment out the addition code I added to `enable_video_display()`, the program works fine. What am I doing incorrectly when setting up the elements?

Do I need to edit the initial elements of the pipeline so I can support another parallel set of elements for saving video?

```
void
TcamCamera::create_pipeline()
{
    pipeline_ = gst_pipeline_new("pipeline");
    tcambin_ = gst_element_factory_make("tcambin", nullptr);
    if (!tcambin_)
        throw std::runtime_error("'tcambin' could not be initialized! Check tiscamera installation");
    capturecapsfilter_ = gst_element_factory_make("capsfilter", nullptr);
    tee_ = gst_element_factory_make("tee", "tee");
    GstElement *queue = gst_element_factory_make("queue", nullptr);
    capturesink_ = gst_element_factory_make("appsink", nullptr);
    g_object_set(capturesink_, "max-buffers", 4, "drop", true, nullptr);
    assert(pipeline_ && tee_ && capturecapsfilter_ && queue && capturesink_);


    gst_bin_add_many(GST_BIN(pipeline_),
                     tcambin_, capturecapsfilter_, tee_, queue, capturesink_, nullptr);
    assert(gst_element_link_many(tcambin_, capturecapsfilter_, tee_, queue, capturesink_, nullptr));
}```

**Comment by TIS-Stefan** [comment]
Hello 

Can you please post the complete project (packed), so I try to debug it for you? I am not that GStreamer expert and supporter, I must try and error on my own,

However, you do not encounter a problem with the camera and the original code worked?

Stefan
