### ISSUE TITLE
Loading firmware to the camera

### ISSUE THREAD

**Issue by yoelk** [TheImagingSource/tiscamera#263]
Is it possible to reload firmware to a camera?
I have a TIS_GIGE29_WUXGA_M_Z12.

The reason is ask is that sometimes some camera parameters get "stuck" and can not be modified.
Sometimes unplugging the power from the camera helps, but sometimes not, so I was wondering what possibilities I have for resetting the camera's inner state (e.g. by loading firmware).

Thanks,
Joel

**Comment by TIS-Stefan** [comment]
Hello Joel

You may let me now, which parameters get "stuck". also which software you use. 
Also I need the serial number of the camera.

There is no camera reset. Unpowering is the only reset.

Stefan

**Comment by yoelk** [comment]
Hi Stefan,
The code version we use is: tiscamera_0.10.0.2329.development_1e0b465_amd64.deb
I don't have the camera's ID at the moment. I'll write it when I do.
The stuck parameters are either the Zoom or the Focus (this time the Focus).
Unpowering did make focus unstuck but, auto-focus remained always on, and we couldn't turn it off.

**Comment by yoelk** [comment]
If you want to see the problem together with me, I can connect you via TeamViewer to see the problematic camera.

**Comment by TIS-Stefan** [comment]
Hi Joel

I suggest to use the github code. Either master or development branch.

Stefan

**Comment by yoelk** [comment]
Dear Stefan, we've been through this already. We can only use stable releases.
And regardless, this version was done by Arne especially for us, to overcome the Aravis MTU negotiation problems.

Can we get support from you regarding this problem?

**Comment by TIS-Stefan** [comment]
Hello Joel

I will notice Arne on this.

Stefan

**Comment by TIS-Stefan** [comment]
Hello Joel

> Dear Stefan, we've been through this already.

I did not knew that.

What does "stuck" mean: You move the sliders of zoom, but the camera does not react? Same with focus, the lens does not move?

Stefan

**Comment by TIS-Arne** [comment]
Hi Joel, 
I built a package from the latest development version of tiscamera. Could you please check whether the problem persists?

[tiscamera_0.10.0.2513~development_b4a58b2_amd64.zip](https://github.com/TheImagingSource/tiscamera/files/3029001/tiscamera_0.10.0.2513.development_b4a58b2_amd64.zip)


Thanks, 

/Arne

**Comment by yoelk** [comment]
Thanks Arne. Does it include the MTU change you did for us?
The one that checks the TCAM_GIGE_PACKET_SIZE environment variable.

**Comment by TIS-Arne** [comment]
@yoelk Yes, it should. This change is present in all development versions since commit 1e0b465b.

**Comment by yoelk** [comment]
Great! Thanks!
