### ISSUE TITLE
DFM 42BUC03-ML 

### ISSUE THREAD

**Issue by Luke-Mendonca** [TheImagingSource/tiscamera#276]
Hi, i've obtained 2 of the above cameras and have done the fallowing ...
 I'm running it on a raspbian latest version on the new Raspberrypi 3 B+.

 1.) https://github.com/TheImagingSource/tiscamera , all instructions fallowed, built, compiled and installed. All options on, besides DBUILD_ARAVIS. (tcam-capture) did not see the device.

 2.) https://github.com/TheImagingSource/tiscamera/wiki/UDEV-Rules, copied, restarted and checked content. (tcam-capture) did not see the device.

 3.) Using the instructions on https://github.com/TheImagingSource/tiscamera/wiki/Getting-Started-with-USB-2.0-CMOS-Cameras, i ran "sudo ./firmware-update -l" and got 2 different results for each camera.

 Camera 1 : Found 0 Devices - all information blank
 Camera 2 : Id is filled, but the name and serial are only filled sometimes.
                  Running sudo ./firmware-update -id <SERIAL> does not find the serialnumber that some times show up

I am unsure on how to proceed.

**Comment by TIS-Stefan** [comment]
Hello

Is it possible, you also wrote by email to me? So I do not need to handle this here again?

Stefan
