### ISSUE TITLE
focus_absolute

### ISSUE THREAD

**Issue by labreu** [TheImagingSource/tiscamera#28]
Hello,

I'd like to know what the variable focus_absolute is for. I tried to change the value but nothing seems to  happen.

The camera model is dfk72buc02.

thanks

**Comment by TIS-Stefan** [comment]
The current firmware of the camera states, it has a focus unit installed. It lies. There is none. Therefore, nothing happens.

The DFK 72AUC02-F has a focus unit. This camera model allows to focus by software.
