### ISSUE TITLE
ROS python script tiscamera.py fails to load camera.yaml calibration file

### ISSUE THREAD

**Issue by MedericFourmy** [TheImagingSource/tiscamera#280]
I am using the tiscamera.py example file to launch a rosnode publishing /camera/image_raw  but I get an error regarding the camera calibration file.

> [ INFO] [1558526303.996005024]: camera calibration URL: file:///home/mfourmy/.ros/camera_info/camera.yaml
> [ERROR] [1558526303.996296781]: Exception parsing YAML camera calibration:
> yaml-cpp: error at line 0, column 0: bad conversion
> [ERROR] [1558526303.996320751]: Failed to parse camera calibration from file [/home/mfourmy/.ros/camera_info/camera.yaml]
> [ WARN] [1558526303.996340050]: Camera calibration file /home/mfourmy/.ros/camera_info/camera.yaml not found.
> [ INFO] [1558526303.996360080]: Loaded camera calibration from 
> [ INFO] [1558526304.006460008]: Time offset: 1558516989,916
> [ INFO] [1558526304.135944829]: Publishing stream...
> [ INFO] [1558526304.136317009]: Started stream.

It seems that the parsing of the file is the cause of the problem (I do have a file at /home/mfourmy/.ros/camera_info/camera.yaml despite the misleading warning). The gscam node is started and publishes both `/camera/image_raw` and `/camera/image_info` topics but the latter is just zero values everywhere. Here is a dump of my yaml file (which is valid I think):

D = [-0.011282763152418432, 0.005933633101994206, -0.00042987175625651213, -0.0011417374465161805, 0.0]
K = [349.4587164359501, 0.0, 309.6278864780053, 0.0, 349.32186989550684, 273.2119115401279, 0.0, 0.0, 1.0]
R = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P = [348.2904357910156, 0.0, 308.4955324828625, 0.0, 0.0, 348.5977478027344, 272.8415570050729, 0.0, 0.0, 0.0, 1.0, 0.0]

[image]

width
640

height
480

[narrow_stereo]

camera matrix
349.458716 0.000000 309.627886
0.000000 349.321870 273.211912
0.000000 0.000000 1.000000

distortion
-0.011283 0.005934 -0.000430 -0.001142 0.000000

rectification
1.000000 0.000000 0.000000
0.000000 1.000000 0.000000
0.000000 0.000000 1.000000

projection
348.290436 0.000000 308.495532 0.000000
0.000000 348.597748 272.841557 0.000000
0.000000 0.000000 1.000000 0.000000

**Comment by TIS-Stefan** [comment]
Hello

I have the faint suspect, your issue is wrong here. We do not load YAML files with intrinsics at all. 

Stefan
