### ISSUE TITLE
Neximage 5MP support

### ISSUE THREAD

**Issue by fmadec** [TheImagingSource/tiscamera#29]
Hi,

I am trying to make a Neximage 5MP working on Raspberry PI2.
I was wondering if this camera is supported by your software, if so, which firmware should I use?

Thanks
F.

**Comment by TIS-Stefan** [comment]
Hello

This is a Celestron support case. Please ask the Celestron support for this.

dmk72 ones, I would use.

**Comment by fmadec** [comment]
Hi,
none of the dmk72 seems to work, the command returns nothing, no error, just nothing.
I will try to contact Celestron without hope because they unfortunately only talk about windows .

**Comment by TIS-Stefan** [comment]
The firmware you want to install was not intended to be used with the Neximage series.

However, did you follow the documentation at
https://github.com/TheImagingSource/tiscamera/wiki/Getting-Started-with-USB-Cameras?
The firmware should be "dmk72uc02_162_uvc.euvc". However, I am not sure, which camera your camera exactly is.

**Comment by fmadec** [comment]
Yes, I understand that the firmware was not for the Celestron one, in fact during my tries to make it working I discovered that the celestron camera was a tis one, that the reason way I am trying to use your software.

I did follow your documentation, I tried first on a raspberry PI 2 with raspbian without success.
I switched to an other PC and the firmware update works but after few seconds of grabbing images (with guvcview), it's stop and says: "could not grad image (select timeout): device temporary unavailable "

By the way my camera is the Clestron neximage 5 MP:
CMOS sensor (1/2.5") Micron MTP9P031
2.2 microns pixel size
2592x1944 pixels

Thanks for trying to help me.

**Comment by TIS-Stefan** [comment]
I did not test on a Raspberry PI2 on my own. However, try lower frame rates.

**Comment by fmadec** [comment]
Hi,
sorry for the late answer, but a lower frame rates simply gives more time before the freeze....

**Comment by TIS-Stefan** [comment]
No problem being late, but I have no context. I do not know, whether you run on Linux or Windows

**Comment by fmadec** [comment]
I an trying to make it running on linux

**Comment by TIS-Stefan** [comment]
Did you try a lower frame rate?

**Comment by fmadec** [comment]
Yes I tried without sucess
