### ISSUE TITLE
Extend FOV

### ISSUE THREAD

**Issue by eloibove** [TheImagingSource/tiscamera#298]
Hi, I am currently using a DFK33UX252. The field of view I get at 640x480 with 'Override Scanning Mode'=5 is not enough for my application. I understand that to use the binning feature the size of the image has to be at most half of the sensor resolution, which in my case is 1024x768. Then, I think that with this resolution and binning by half the FOV should be enough. However, this resolution is not available... 
I was wondering if there is a way to use this resolution as in issue #183 . I think that this resolution is available in Windows but not in Linux, and I am using Ubuntu 16.04.
Thank you in advance.

**Comment by TIS-Stefan** [comment]
Hi
Unfortunately V4L2 does support a limited list of resolutions, which must be saved in the USB descriptor of the camera, only. Therefore, not all possible resolutions are available. Unfortunately the USB descriptor has a limited size of memory.

Thus, we are not able to solve this issue to you needs.

Stefan

**Comment by eloibove** [comment]
Hi Stefan, thank you anyway!

**Comment by eloibove** [comment]
Hi Stefan, I was wondering if it is possible to change the available resolutions that are saved in the USB descriptor of the cameras since we don't need the 1920x1080 resolution and a resolution of 1024x768 would really be the solution to our problem. 

If it is possible, could you provide instructions to do it?

Thank you very much! 

Eloi

**Comment by TIS-Stefan** [comment]
Hello Eloi

Is it possible, your company is already in contact about that by email with me? I have  same case with another programmer. Same camera, same request.
Which means, we are working on that.

Stefan

**Comment by eloibove** [comment]
Hi Stefan. Yes, I contacted yesterday via email. It's good to know you are working on that! Please, keep me updated about any further news. 
Thank you very much,

Eloi

**Comment by TIS-Stefan** [comment]
ok, lets close the case here.
