### ISSUE TITLE
Why is Gain and Whitebalance set to manual for software trigger?

### ISSUE THREAD

**Issue by marcel1991** [TheImagingSource/tiscamera#299]
In the example code that describes how to use the software trigger function the automatic gain and automatic whitebalance is set to false. The explanation seems to be that because the timing of image recording can change depending on the automatic function and therefore the trigger timing can be unexpected?

I understand that this is the case for auto exposure. But the other functions (like gain or whitebalance) are applied in the post-processing after the image has been recorded, so it should not take any effect on the actual image recording. So why are automatic gain and whitebalance set to false?

Moreover how does Highlight Reduction work? If automatic exposure is disabled is this done only through the gain in the postprocessing? What does Highligh Reduction actually do or where can I read about it?

**Comment by TIS-Stefan** [comment]
Hello

if the automatics run, then they examine an image an set the values for the next image. If the light environment changes between the current and next image, then you may get wrong exposed images.

If the white balance automatic is done in software, as for the USB 2.0 , 23U, 23G camera series, then the image is indeed processed directly and you can use that with trigger.

If the white balance is done in hardware, then the amplifiers on the sensor are configured, so the next image is using these values.

However, if your trigger frequency not too low, then you can use automatics.

Stefan
