### ISSUE TITLE
Cannot set GstCaps field during runtime

### ISSUE THREAD

**Issue by jassib** [TheImagingSource/tiscamera#306]
Hi, I am having trouble setting the framerate after I have started the pipeline, to dynamically change the fps. This code works if `gst_caps_set_simple` is called before the pipeline is set to GST_STATE_PLAYING, but after I get the error: 
`GStreamer-CRITICAL **: 21:00:36.744: gst_caps_set_simple: assertion 'IS_WRITABLE (caps)' failed`, 
even if I try setting the state to GST_STATE_PAUSED or GST_STATE_READY.
Any tips?
```
GstCaps *capture_format_caps = gst_caps_new_simple("video/x-raw",
                                        "width", G_TYPE_INT, size.width,
                                        "height", G_TYPE_INT, size.height,
                                        "framerate", GST_TYPE_FRACTION, framerate.numerator, framerate.denominator,
                                        nullptr);
assert(capture_format_caps);
if(format != "")
    gst_caps_set_simple(capture_format_caps, 
                        "format", G_TYPE_STRING, format.c_str(), 
                        nullptr);

g_object_set(G_OBJECT(capturecapsfilter_), "caps", capture_format_caps, nullptr);
gst_caps_unref(capture_format_caps);

// later on in the code ...

capture_format_caps = gst_caps_copy(capture_format_caps);
gst_caps_set_simple(capture_format_caps,
                    "framerate", GST_TYPE_FRACTION, framerate.numerator, framerate.denominator,
                    nullptr);
```

**Comment by TIS-Stefan** [comment]
This is correct. In state paused and ready, the pipeline has bee built, the formats are negotiated, memory is allocated. I am not sure, whether the state must be NULL or the pipeline must be rebuild completely. I think, the pipeline must be rebuilt completely. 

Stefan
