### ISSUE TITLE
2x Binning on DMK33UX252

### ISSUE THREAD

**Issue by manindermatharoo** [TheImagingSource/tiscamera#313]
Hi 
I want to activate 2x Binning on my DMK33UX252 on Linux. I activated binning in Windows using the IC Capture software provided and it sets the resolution of the image to 1024 x 768 when 2x binning is activated. In tcamcamera.cpp, there is a function called TcamCamera::get_format_list() which prints the video formats as follows for DMK 33UX252:

`size = 640 x 480 color formats = {GRAY8,} frame rates = {600/1,480/1,5000000/20833,120/1,60/1,30/1,15/1,5/1,1/1,}

size = 1920 x 1080 color formats = {GRAY8,} frame rates = {180/1,120/1,60/1,30/1,15/1,5/1,1/1,}

size = 2048 x 1536 color formats = {GRAY8,} frame rates = {75/1,60/1,30/1,15/1,5/1,1/1,}

size = 640 x 480 color formats = {GRAY16_LE,} frame rates = {600/1,480/1,5000000/20833,120/1,60/1,30/1,15/1,5/1,1/1,}

size = 1920 x 1080 color formats = {GRAY16_LE,} frame rates = {90/1,60/1,30/1,15/1,5/1,1/1,}

size = 2048 x 1536 color formats = {GRAY16_LE,} frame rates = {35/1,30/1,15/1,5/1,1/1,}
`
How do I activate 2x binning on my camera. I have set the property "Override Scanning Mode" to 2 and the resolution to 1024 x 768 but it seems like that resolution isn't availbale in Linux on the USB3 cameras.

**Comment by TIS-Stefan** [comment]
Hello

You are right, a 1024x768 is not available in Linux, because this video format is not in the USB Descriptor of the camera. v4l2 can use formats that are in the USB descriptor of a camera, only. And the memory there is very limited.
At the moment, we can not do anything about it.

Stefan
