### ISSUE TITLE
Wrong property name in python sample code 02-set-properties.py 

### ISSUE THREAD

**Issue by hitpony** [TheImagingSource/tiscamera#317]
Hello Expert
- Problem: when I run the example code of 02-set-properties.py, I got following error message:

Expposure Auto has value: False
Traceback (most recent call last):
  File "/home/my_name/workspace/camera/python/02-set-properties.py", line 100, in <module>
Gain Auto has value: False
    sys.exit(main())
  File "/home/my_name/workspace/camera/python/02-set-properties.py", line 84, in main
    print_properties(camera)
  File "/home/my_name/workspace/camera/python/02-set-properties.py", line 60, in print_properties
    category, group) = camera.get_tcam_property("Exposure")
TypeError: unknown type (null)

(02-set-properties.py:4478): GStreamer-CRITICAL **: 
Trying to dispose element tcambin0, but it is in READY instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.

I change following two lines, seems it is OK:

Line 60
From:category, group) = camera.get_tcam_property("Exposure")
To: category, group) = camera.get_tcam_property("Exposure Time (us)")

same for Line 91.

I guess the sample code use the wrong name of Property of "Exposure Time (us)"

I am using:
- Latest master branch of TheImagingSource/tiscamera
- Ubuntu 16.04 LTS
- Python3.6
- CAMARA: DFK 33UX264

PS： Line 41， there is a typo, "Expposure" should be "Exposure"

Best Regards
MA Yuchu@zhmt

**Comment by TIS-Stefan** [comment]
Hello

You are right. The different Exposure names are created by supporting GigE Camera as well as USB cameras. Therefore, you have the "Exposure Time (us)". However, what is worse, is the different interfaces. The Gige cameras use "enum" like "on" and "off", while the USB cameras use 0 and 1 for turning automatics on and off. I hope, this will be unified in future.

Stefan
