### ISSUE TITLE
 error: ‘libusb_strerror’ was not declared in this scope

### ISSUE THREAD

**Issue by doanxuanthy** [TheImagingSource/tiscamera#325]
Hello guys, 
I install follow instruction. When I do step: make 
I have a problem 
[ 57%] Building CXX object src/libusb/CMakeFiles/tcam-libusb.dir/AFU420Device.cpp.o
In file included from /usr/tiscamera-master/tiscamera/src/libusb/LibusbDevice.h:25:0,
                 from /usr/tiscamera-master/tiscamera/src/libusb/AFU420Device.h:25,
                 from /usr/tiscamera-master/tiscamera/src/libusb/AFU420Device.cpp:17:
/usr/tiscamera-master/tiscamera/src/libusb/AFU420Device.cpp: In member function ‘int tcam::AFU420Device::setup_bit_depth(int)’:
/usr/tiscamera-master/tiscamera/src/libusb/AFU420Device.cpp:1089:56: error: ‘libusb_strerror’ was not declared in this scope
                    hr, libusb_strerror((libusb_error)hr));

Could you help me to solve it ? Thank you very much.

**Comment by TIS-Edgar** [comment]
Hi,

What version of libusb are you using? 
What distribution are you using?

**Comment by TIS-Stefan** [comment]
We got no answer. Is the issue solved?
Stefan
