### ISSUE TITLE
Request to add exposure time and gain metadata in each frame's statistics struct

### ISSUE THREAD

**Issue by chengguizi** [TheImagingSource/tiscamera#334]
I am working on DMM 37UX273-ML camera, USB3, Linux.

Currently for each frame, the available [statistics](https://github.com/TheImagingSource/tiscamera/blob/master/src/base_types.h) is frame_count, capture_time_ns, framerate. 
However, when auto exposure mode is enabled, I would also like to know the **actual exposure time** and **gain settings** for each frame, for each frame. This is available for other camera ([RealSense](https://github.com/IntelRealSense/librealsense/blob/83f952a4bd6b70d72459f66c7f67ddaba9d337a0/include/librealsense2/h/rs_frame.h) for example, exposed as RS2_FRAME_METADATA_ACTUAL_EXPOSURE  and RS2_FRAME_METADATA_GAIN_LEVEL)

These per-frame statistics are important for any image processing algorithms requiring photo-consistency, it will be great if tiscamera could add in supports for this feature, thanks!

**Comment by TIS-Stefan** [comment]
Hello

Thank you for your request. It is already on our ToDo list, but currently there no dead line determined.

Stefan
