### ISSUE TITLE
softerware trigger and copy image from camera doesn't work 

### ISSUE THREAD

**Issue by wutongyu98** [TheImagingSource/tiscamera#335]
Hi, I am using the usb3.1 board camera from imaging source. I can successfully run the "06-softwaretrigger" and "07-appsink" from the "tiscamera" example .  I know "07-appsink" is used to access data via "sink" from camera, and "06-softwaretrigger" is used to trigger the camera action. But when put them together, I cannot get the data out. Could you provide a short example how to get these two function (software trigger and copy data from camera) work together? Thanks

**Comment by TIS-Stefan** [comment]
Hello

you may look at https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples for complete samples, that try to do, what you want.

Stefan

**Comment by wutongyu98** [comment]
thanks stefan. I figured that out. Just need to set the syn=true, I can get the synchronized camera action.
