### ISSUE TITLE
DMM 72BUC02-MLPB: Global Reset Release and External Trigger

### ISSUE THREAD

**Issue by junsujang** [TheImagingSource/tiscamera#348]
Hello,

I am trying to use external trigger and global reset release. However, it seems like when I set global reset release property to true, external trigger is no longer valid, and the camera takes image as fast as it can, thereby hanging my computing unit. Is this an expected behavior? Do I have a way to make these two features work together?

**Comment by TIS-Stefan** [comment]
Hello

Both properties should be independent from each other. Can you repeat that issue in tcam-capture too?

Stefan

**Comment by junsujang** [comment]
I think I had some incorrect configuration while I was doing this initially. I tried again, and it seems to work. Thanks for checking.
