### ISSUE TITLE
Tcam- saved video presents with vertical line 

### ISSUE THREAD

**Issue by Vineet-Pandey** [TheImagingSource/tiscamera#353]
I am using DMK 37BUX287 camera in Ubuntu 18.04. Upon saving the video using the example python code (With Gstreamer) in the TheImagingSource repository, the video shows vertical lines (First image below) - which does not happen when I use OpenCV(Second image below). Is there a particular reason why this happens? Is there a workaround or a solution for this problem? TIA.
![image](https://user-images.githubusercontent.com/29963970/85902507-2e898100-b7d2-11ea-9fc6-b488b5b184ab.png)
![image](https://user-images.githubusercontent.com/29963970/85902743-bb343f00-b7d2-11ea-9a0a-fc2629ba1a67.png)

**Comment by TIS-Stefan** [comment]
That was something with video format.
