### ISSUE TITLE
some issues when i have installed two version of tiscamera

### ISSUE THREAD

**Issue by Heyinsen** [TheImagingSource/tiscamera#359]
When i have installed the latest version of tiscamera,as i run ‘tcam-ctrl’ ,i can find devices.

as my code has something incompatible with new version of tiscamera,so i installed the last version of tiscamera,but after i have finished it and run “tcam-ctrl -l”,i get only “No devices found!”

i have tried it two times, and i get entire same results.

maybe you can give me some advice on what has changed on these two versions and how to solve this problem. 

![image](https://user-images.githubusercontent.com/48718428/87676565-548bbb00-c7ab-11ea-820b-64d1438f0fc4.jpg)

camera is shown above.

shy

**Comment by TIS-Stefan** [comment]
Hello did you run cmake with

`cmake -DBUILD_ARAVIS=ON ..`

?

Stefan

**Comment by Jared-Shen** [comment]
‘cmake -DBUILD_ARAVIS=OFF ..’

so you mean ARAVIS is needed? Sorry i am not clear about this. Would you give me some advice on what this is?

Thanks.

shy

**Comment by TIS-Stefan** [comment]
Yes! You have a GigE camera. That needs Aravis GigEVision library.
