### ISSUE TITLE
tcam on Raspbian Buster (armhf/armv7 arch) not listing GRAY8 and GRAY16 formats: DBK 33UX178.AS

### ISSUE THREAD

**Issue by andreok** [TheImagingSource/tiscamera#362]
Hello,

I am having issues while trying to capture layered frames from GRAY8/Y800 and GRAY16/Y16 formats using tcam 0.12.0 on my Raspberry Pi 4b+ running Raspbian Buster (armhf/armv7 arch) and a DBK 33UX178.AS camera.
The camera works just fine on Windows 10, using IC Capture.

Here is the list of the available formats for the DBK 33UX178.AS:
"tcam-ctrl -f 26020406
Available format settings:
Format: 8-bit Bayer RGRG/GBGB - Fourcc(1111967570)
Resolution: 640x480
280.0000 fps
240.0038 fps
120.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 1920x1080
130.0000 fps
120.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 2048x2048
70.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 3072x2048
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps

Format: 70434752-0000-0010-8000-00aa003 - Fourcc(0)
Resolution: 640x480
280.0000 fps
240.0038 fps
120.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 1920x1080
120.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 2048x2048
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 3072x2048
40.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps

Format: 16-bit Bayer RGRG/GBGB - Fourcc(909199186)
Resolution: 640x480
280.0000 fps
240.0038 fps
120.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 1920x1080
90.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 2048x2048
45.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 3072x2048
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps

Format: YUYV 4:2:2 - Fourcc(1448695129)
Resolution: 640x480
280.0000 fps
240.0038 fps
120.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 1920x1080
90.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 2048x2048
45.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 3072x2048
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps

Format: 31313459-0000-0010-8000-00aa003 - Fourcc(0)
Resolution: 640x480
280.0000 fps
240.0038 fps
120.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 1920x1080
120.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 2048x2048
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 3072x2048
40.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps

Format: 24-bit BGR 8-8-8 - Fourcc(861030210)
Resolution: 640x480
280.0000 fps
240.0038 fps
120.0000 fps
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 1920x1080
60.0000 fps
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 2048x2048
30.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps
Resolution: 3072x2048
20.0000 fps
15.0000 fps
5.0000 fps
1.0000 fps"

And here is the output when I try to grab frames using GStreamer:
"gst-launch-1.0 tcamsrc name=source ! video/x-raw, format=GRAY8, width=640, height=480, framerate=30/1 ! videoconvert ! ximagesink
WARNING: erroneous pipeline: could not link source to videoconvert0, source can't handle caps video/x-raw, format=(string)GRAY8, width=(int)640, height=(int)480, framerate=(fraction)30/1"

Regards,
Andre

**Comment by TIS-Stefan** [comment]
There is no gray format, because it is a color format. The raw data formats of this cameras are something like video/x-bayer and something like "rggb".
You use "tcam-ctrl -c" for getting a list of possible GStreamer caps for video formats. In order to get raw data, you may have a look at https://theimagingsource.deskpro.com/de/kb/articles/linux-set-video-formats-in-camera-and-memory.
