### ISSUE TITLE
Error "Unable to display caps. Conversion failed." on DYK 33UX250

### ISSUE THREAD

**Issue by nikolajsheller** [TheImagingSource/tiscamera#364]
I am unable to capture any images from a DYK 33UX250 on Ubuntu 20.04 and a Raspberry Pi 4 running Raspbian Buster. They fail in the same way.

tcam-capture correctly identifies the camera, but lists no Formats, Resolutions or FPS in the selection boxes.

tcam-ctrl reports:
pi@raspberrypi:~ $ tcam-ctrl -c 45910379
Unable to display caps. Conversion failed.

![Screenshot from 2020-08-30 17-48-14](https://user-images.githubusercontent.com/875164/91664597-a20c7f00-eaf0-11ea-834a-0bd5ef1293f4.png)

**Comment by TIS-Edgar** [comment]
Hi,

The DYK 33UX250 requires two special settings to function properly.
1. The flag TCAM_ARAVIS_USB_VISION has to be set to ON during configuration.
2. tiscamera-dutils has to be installed. You can find them in our download section.

The kernel drivers do not yet contain our polarization formats so a workaround has to be used.
