### ISSUE TITLE
Returned the firmware to factory defaults, now it only displays in grayscale

### ISSUE THREAD

**Issue by diegohdezr** [TheImagingSource/tiscamera#37]
hello, I used the firmware update tool with a DFK 72BUC02 and it worked nice in linux but in grayscale, when I returned the firmware to factory defaults to work on Windows again, it keeps working on grayscale, so, how do I change this in Windows? I am trying to make a stereo pair and one takes the image in color and the other one in grayscale, so how can I set up both in color or in grayspace? with IC capture I use the debayering but can I activate it and deactivate it without IC capture? thanks

**Comment by TIS-Stefan** [comment]
First of all, it is not gray scale. You see the bayer raw data. This can be convertet by OpenCV or the GStreamer Bayer.2RGB pipeline module to color images.

The Windows firmware  file name for the DFK 72 startes with "dfk72.." Write this into the camera for Windows. Also the euvccam-fw tool created a backup of the previous firmware that was in the camera. This can be written back too.
