### ISSUE TITLE
Unknown Socket on DFM 37UX226-ML

### ISSUE THREAD

**Issue by Moj-Dev** [TheImagingSource/tiscamera#377]
Hi,
I'm looking for a compact cable interface with the camera module instead of micro USB cablee. Is the FFC socket [mentioned in the image] USB pinout?

![socket](https://user-images.githubusercontent.com/58832214/98055080-7dcf6600-1df1-11eb-8bd0-9d0f677a17c0.png)

**Comment by TIS-Stefan** [comment]
The connector you point to is a debug output. You can ot use it. On this board, there is only the USB C connector for communication to the computer.
