### ISSUE TITLE
gstreamer

### ISSUE THREAD

**Issue by Moj-Dev** [TheImagingSource/tiscamera#379]
I'm working with DFM 37UX226-ML camera on RaspberryPi4. When I use  "gst-launch-1.0 tcambin ! video/x-raw,format=BGRx,width=3840,height=2160,framerate=30/1 ! videoconvert ! ximagesink sync=false", the preview is ok but when I run the gstreamer in my python code, there is a huge lag and delay in preview. How can I fix this issue?

**Comment by TIS-Stefan** [comment]
Hello

I think, the best way is to optimize the code you use.
For example. the queue elements always create a new copy of the image. Thus, try not to use them, as you do in your gst-launch-1.0 pipeline.
The main trick is to avoid as many as possible image copies.
So you may not rely on the "TIS.py", but build your own optimized pipeline.

Stefan
