### ISSUE TITLE
about install-dependencies.sh

### ISSUE THREAD

**Issue by shinjihagio** [TheImagingSource/tiscamera#396]
I would like to build tiscamera module in docker container.
Therefore, install commands in install-dependencies.sh like "sudo apt-get install $ASSUME_YES $(read_file "$TISCAMERA_DIR/dependencies/dependencies-debian-compilation.txt") " are desirable like sudo apt-get install -y $ASSUME_YES $(read_file "$TISCAMERA_DIR/dependencies/dependencies-debian-compilation.txt").

Actually I can change these points like that, but I want to use this repository as a git submodule.
So, if you don't have concerning points about these change, would you like to change install commands that adding -y.

**Comment by TIS-Edgar** [comment]
install-dependencies.sh has a `--yes` flag. Does that do what you require?
0.13.0 introduced the dependency-manager as a more flexible replacement. It also has a `--yes` flag.
