### ISSUE TITLE
How can I set ROI (DMK 42BUC03)

### ISSUE THREAD

**Issue by ccrb** [TheImagingSource/tiscamera#40]
Hello all,

Can I set ROI (by Opencv or its hardware) not only supported on website.
For example: 

    ImageSize.width = 1280;
    ImageSize.height = 300;

While I change this on my main.cpp, I can't view correct image.
Can anyone tell me how to change image's ROI by myself?
Prefer the fastest way but not use waste CPU speed. (hardware? Opencv?)

thanks all, 
ccrb

**Comment by TIS-Stefan** [comment]
You can not change the roi on the camera. The 42 model has only 1280x960 resolution.
