### ISSUE TITLE
GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1

### ISSUE THREAD

**Issue by bigwhitebird29** [TheImagingSource/tiscamera#408]
I've looked this error up over and over, and all I keep getting is "what pipeline did you put in for GStreamer via cv2.VideoCapture()"  when in fact it comes up no matter what camera I'm using. It has to be something else that I need to change somewhere else. 

for my onboard IMX219-160, I have...cam=cv2.VideoCapture( 'nvarguscamerasrc !  video/x-raw(memory:NVMM), width=3264, height=2464, format=NV12, framerate=21/1 ! nvvidconv flip-method='+str(flip)+' ! video/x-raw, width='+str(dispW)+', height='+str(dispH)+', format=BGRx ! videoconvert ! video/x-raw, format=BGR ! appsink')

For my first Logitech C922x pro stream webcam, I have... cam=cv2.VideoCapture(1)
for my second Logitech C922x Pro stream webcam, I have.... cam=cv2.VideoCapture(2)

Im using jetson nano 4g with most current jetpack 4.5 as of 5/7/21 
python3 on code-oss not sure of version, latest version as of 5/7/21
opencv 4.1.1

here is my full basic code with all 3 cameras running... It works fine like this, but with this error. but when I need to start building on the code to do things like a moving watermark, the program crashes on some kind of boundary/size error. I assume has to do with this gstreamer video position error.

I normally comment out one camera code set, and comment in another to change cameras. 

import cv2
print(cv2.__version__)
dispW=320
dispH=240
flip=0

camSet ='nvarguscamerasrc !  video/x-raw(memory:NVMM), width=3264, height=2464, format=NV12, framerate=21/1 ! nvvidconv flip-method='+str(flip)+' ! video/x-raw, width='+str(dispW)+', height='+str(dispH)+', format=BGRx ! videoconvert ! video/x-raw, format=BGR ! appsink'
cam3 = cv2.VideoCapture(camSet)
cam=cv2.VideoCapture(1)
cam.set(cv2.CAP_PROP_FPS,30)
cam2=cv2.VideoCapture(2)
cam2.set(cv2.CAP_PROP_FPS,30)

while True:
    ret, frame=cam.read()
    frame = cv2.resize(frame,(dispW,dispH))
    cv2.imshow('logi1',frame)
    cv2.moveWindow('logi1',0,0)

    ret, frame1=cam2.read()
    frame1 = cv2.resize(frame1,(dispW,dispH))
    cv2.imshow('logi2',frame1)
    cv2.moveWindow('logi2',dispW+65,0)

    ret, frame2=cam3.read()
    #frame2 = cv2.resize(frame2,(dispW,dispH))
    cv2.imshow('piCam',frame2)
    cv2.moveWindow('piCam',dispW+dispW+65,0)

    if cv2.waitKey(1)==ord('q'):
        break

cam.release()
cv2.destroyAllWindows()

This is the full terminal report. 

$ /usr/bin/python3 /media/wms/pypro/pypro/basic/tricam.py
4.1.1
GST_ARGUS: Creating output stream
CONSUMER: Waiting until producer is connected...
GST_ARGUS: Available Sensor modes :
GST_ARGUS: 3264 x 2464 FR = 21.000000 fps Duration = 47619048 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 3264 x 1848 FR = 28.000001 fps Duration = 35714284 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1920 x 1080 FR = 29.999999 fps Duration = 33333334 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1640 x 1232 FR = 29.999999 fps Duration = 33333334 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1280 x 720 FR = 59.999999 fps Duration = 16666667 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1280 x 720 FR = 120.000005 fps Duration = 8333333 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: Running with following settings:
   Camera index = 0 
   Camera mode  = 0 
   Output Stream W = 3264 H = 2464 
   seconds to Run    = 0 
   Frame Rate = 21.000000 
GST_ARGUS: Setup Complete, Starting captures for 0 seconds
GST_ARGUS: Starting repeat capture requests.
CONSUMER: Producer has connected; continuing.
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
GST_ARGUS: Cleaning up
CONSUMER: Done Success
GST_ARGUS: Done Success
wms@wms-desktop:/media/wms/pypr

**Comment by TIS-Stefan** [comment]
Hello 

Sorry for not answering:
but:
* Logitech is not our brand, so here is the wrong place to ask.,
* I do not think, your Logitech cameras are MIPI cameras. So the nvarguscamerasrc should not handle the.

Stefan
