### ISSUE TITLE
Tcam-Capture error: displaysink: could not initilaize xv output

### ISSUE THREAD

**Issue by mbcel** [TheImagingSource/tiscamera#409]
I just installed the tiscamera repo. However I am not getting any camera live view with the tcam-capture program. No output stream frame rates are selectable/shown in the gui but the camera itself is recognized. 

Running the gui in a terminal outputs the error: 

`Tcamview.py:509 : - ERROR: displaysink : Could not initialise Xv output`

**Comment by TIS-Stefan** [comment]
Hello 

it seems, you use  ssh forwarding, which has no graphic board hardware support.
My suggestion: Search in the tcam-capture source for "xvimagesink" and replace it with "ximagesink". (Without "v".) The latter one does not use graphic boards hardware and therefore works with SSH.

Which camera model do you use?
Which computer model to you use?

Stefan

**Comment by mbcel** [comment]
I installed the tiscamera lib through ssh but when running I do not use ssh and instead run it on the computer itself. It's a amd64 based laptop running Ubuntu 18.04 and also equipped with an nvidia graphics card. Futhermore I blacklisted the nouveau driver since else I am not able to boot into Ubuntu. Could this be the reason? 

Camera is: Model: DFM 37UX273-ML Serial: xxxxxx Type: v4l2

**Comment by mbcel** [comment]
Yep, it does work. However I had to remove some properties that only exist in the xvimagesink.

**Comment by TIS-Stefan** [comment]
Very well!
