### ISSUE TITLE
Not complete frames with v4l2 and opencv

### ISSUE THREAD

**Issue by Asubayo** [TheImagingSource/tiscamera#41]
Hello,

I have a DMK Camera (DMx 31AU03.AS) that I would like to control under linux (Debian). I have tried your code example https://gist.github.com/TIS-Edgar/10f04501f49b6b3bf75e but I don't understand why the grabbed frames are not complete. I have tried to change the FPS value but it changes nothing to the result. Here is what I always get : 

![screenshot](https://cloud.githubusercontent.com/assets/5774471/9251400/4ff6feb4-41d3-11e5-9bf1-e6b4af0365e2.png)

Do you have an idea of the problem ?

Thank you very much !

**Comment by labreu** [comment]
may I see your main code? maybe I can help

**Comment by Asubayo** [comment]
Hello labreu,

My main code is the same as the example : 

int main ()
{

   	IplImage* pOpenCVImage;

    CvSize ImageSize;
    unsigned char* ImageBuffer = NULL;
    int wKey = -1;

    ImageSize.width = 1024;
    ImageSize.height = 768;

    cvNamedWindow( (char*)"Camera", 1 );

    printf("Program started\n");

    pOpenCVImage = cvCreateImage(ImageSize , IPL_DEPTH_8U, 1 ); // Grayscale
    
    open_device((char*)"/dev/video0");
    init_device(ImageSize.width, ImageSize.height);

    printf("Start capturing\n");

    start_capturing();

    while(wKey == -1 )
    {
        ImageBuffer = snapFrame();

        if( ImageBuffer != NULL )
        {

			memcpy( pOpenCVImage->imageData, ImageBuffer, pOpenCVImage->imageSize);

            cvShowImage( (char*)"Camera",pOpenCVImage);

            wKey = cvWaitKey(10);
			
        }
        else
        {
            printf("No image buffer retrieved.\n");
            break;
        }
    }

    cvDestroyWindow( (char*)"Camera" );
    stop_capturing();
    uninit_device();
    close_device();

    printf("Program ended\n");

    return 0;

}

**Comment by labreu** [comment]
try this

if( ImageBuffer != NULL )
{
             pOpenCVImage->imageData = (char*)ImageBuffer;
             currentImg = Mat(pOpenCVImage);    //convert IplImage to Mat type
             imshow("Window name", currentImg);
             wKey = cvWaitKey(10);
}

**Comment by Asubayo** [comment]
I have the same problem with this modification.

**Comment by TIS-Stefan** [comment]
Hello

Please step into the funcition
void init_mmap (void)

and evaluate the value of "buf.length" at:
 buffers[n_buffers].length = buf.length;

The returned value should be 1024*768 = 786432.

**Comment by Asubayo** [comment]
Hello Stefan,

Yes the value of buf.length is correct. 
I get the value 786432

**Comment by TIS-Stefan** [comment]
do you see a complete image in guvcview?

**Comment by Asubayo** [comment]
I have some troubles with guvcview. I have installed the last version 2.0 but there was a segmentation fault when I launched it. I have now installed the version 1.5.3 but I am not sure it works properly, I can adjust the properties of the camera but I just get black images.

**Comment by Asubayo** [comment]
I have launched guvcview with a different capture method (-r option with value 2) and I get frames  like : 
![screenshot2](https://cloud.githubusercontent.com/assets/5774471/9301423/b91ae9ca-44ce-11e5-8407-09f5dea1bdd5.png)

**Comment by Asubayo** [comment]
Ok, if I changed the fps value to 15, I get complete frames  : 

![screenshot3](https://cloud.githubusercontent.com/assets/5774471/9301520/5f7dd23c-44cf-11e5-89e8-4335120629e1.png)

**Comment by TIS-Stefan** [comment]
Is is possible, the camera is connected to an USB 3.0 controller? In this case, the image data transfer is interrupted. I never saw this on Linux, but on Windows. I did not keep in mind, the Windows driver drops these incomplete frames, therefore, I thought, simply no image was provided at all. Sorry for that.

So : on USB 3.0 controllers, your camera provides half frame rate only. It is in the hardware of the camera and can not be changed. On USB 2.0 controllers, the camera will run with full frame rate.
