### ISSUE TITLE
dfm 25gx236-ml

### ISSUE THREAD

**Issue by faccolo** [TheImagingSource/tiscamera#413]
Good morning,
sorry for the questions I'm new to the linux world!

I bought the following Cam:
DFM 25GX236 -ML to use in lan mode with raspberry pi 4.

I followed the steps outlined here:

https://github.com/TheImagingSource/tiscamera/

unfortunately I can not have any image and  video.

if i use this pipeline:
gst-launch-1.0 tcambin ! videoconvert ! ximagesink
only REC my desktop...
if i use 
tcam-capture
....in trigger mode waiting for first image...

Thanks in advance to everyone

![image](https://user-images.githubusercontent.com/35265845/124088715-809f5b00-da53-11eb-9e82-93721828c66d.png)

**Comment by TIS-Stefan** [comment]
Hello

maybe the Pi is too weak for the high frame rate. Please try lower frame rates and lower resolutions. 

Stefan

**Comment by faccolo** [comment]
Thanks for the reply.

i lowered frame rate to 5fps, but still wait for the trigger.
![WhatsApp Image 2021-07-01 at 11 40 43](https://user-images.githubusercontent.com/35265845/124103330-771cef80-da61-11eb-9559-3de3ac293842.jpeg)

**Comment by TIS-Stefan** [comment]
What are you doing with all these wires?
Did you try 640x480@30fps?
A question:

> if i use this pipeline:
> gst-launch-1.0 tcambin ! videoconvert ! ximagesink
> only REC my desktop...
> 
What does this mean?

Stefan

**Comment by faccolo** [comment]
> What are you doing with all these wires?
> Did you try 640x480@30fps?
> A question:

![image](https://user-images.githubusercontent.com/35265845/124105955-0925f780-da64-11eb-8aae-869d791ebbf0.png)
use  external power supply @12 V

when i use this pipeline 
gst-launch-1.0 tcambin ! videoconvert ! ximagesink

t seems that the terminal freezes
![image](https://user-images.githubusercontent.com/35265845/124106896-f95ae300-da64-11eb-833c-cc53536d38ad.png)

**Comment by TIS-Stefan** [comment]
What happens, if you use the pipeline
gst-launch-1.0 tcambin ! video/x-raw,format=BGRx,width=640,height=480,framerate=30/1 ! videoconvert ! ximagesink
?

Does the green LED lights on the RJ 45 connector of the camera?

I am sorry for guessing around. 

Stefan

**Comment by faccolo** [comment]
genius!

I see something ... 

how did you do?

**Comment by TIS-Stefan** [comment]
Well, I did nothing, you did. tcam-capture has sometimes an issue with changing video formats and frame rates. In particular it hangs, if no frames are delivered.  That will be fixed in tiscamera 0.15 hopefully.

Now you can enhance the width, height and frame rate until you get no more images.

Stefan
