### ISSUE TITLE
Camera property step precision reported wrong for doubles

### ISSUE THREAD

**Issue by Niv-R** [TheImagingSource/tiscamera#415]
Hello,
I came across misleading step values while testing properties with tcam-ctrl

Running on Ubuntu 16.04 Tcam version `0.13.1`
Using camera Model: `DMK 39GX265-Z20-TI` (Gige + Aravis)

When executing `tcam-ctrl -p <serial>`
The step for every (double) property is reported as **0.001**

While testing step values using` tcam-ctrl --load` (e.g. `tcam-ctrl --load <serial> "{\"Gain\":4.1234}"`)
shows the actual step is **0.1** for most values and **0.01** for others.

Can the actual step values be read anywhere else?

**Comment by TIS-Stefan** [comment]
Hello

Most devices do not provide a step size for properties. Some cameras provide step sizes for some, but not all properties.
The Aravis library does not know about step sizes at all. Therefore, we decided to use a dummy values of 0.01, which makes in most cases sense.
In all other cases it is trial and error to figure out the step sizes.

The answer to your question is "No".

Stefan
