### ISSUE TITLE
UTF-8/Unicode character error

### ISSUE THREAD

**Issue by mateustormin** [TheImagingSource/tiscamera#418]
I am trying to use tiscamera with a GigE Vision Camera but once I plug the camera on the network interface I get the following error:
![image](https://user-images.githubusercontent.com/20209658/128530261-a698bc2a-d977-42eb-b47b-60950a749dc1.png)

I believe its because of the manufacturer name on the camera
![image](https://user-images.githubusercontent.com/20209658/128529741-a2092184-5d2a-4183-be74-8a263c630445.png)

tcam-gigetools provides me the correct values (I guess because it doesnt try to decode the vendor name:
![image](https://user-images.githubusercontent.com/20209658/128530205-124f4bcc-5c80-400c-9287-01a022a2f56a.png)

am I right? is there anything I can do to work this around?

**Comment by TIS-Stefan** [comment]
Hello 

It seems, you do not use a The Imaging Source camera, this I am not able to help

Stefan

**Comment by mateustormin** [comment]
Yes sir, you are right, i am not using a The Imaging Source camera, but I am just the developer, R&D brought me this generic camera and I need to make it a product.

Although I did not chose the camera, engineering could use TIS cameras if the application would work, but since you cannot help I guess i'm gonna have to move on with vendor's SDK.

Anyway thanks for your time and stay safe!
