### ISSUE TITLE
tcam-caputre  version 0.14.0

### ISSUE THREAD

**Issue by cocopa** [TheImagingSource/tiscamera#419]
I've install tismodule version 0.14.0 to use the tcam-caputre.
I couldn't recode the color movie in tcam-capture in DFK33UX273.
Although it work displaying with color, it could save the movie of monochrome.
How can I save the movie with color?

**Comment by TIS-Edgar** [comment]
Hi,

I want to ensure there are no misunderstandings here:
Are able to save videos with tcam-capture?
The video file you are getting is mono, but you configured a color stream?

Could you try the example `examples/python/08-save-stream.py`?
It will create the file `/tmp/tiscamera-save-stream.avi`. Is that file correct?

**Comment by TIS-Edgar** [comment]
Closed due to inactivity.
