### ISSUE TITLE
 Can't see Color Video and gstreamer error "WARNING: erroneous pipeline: no element "bayer2rgb""" 

### ISSUE THREAD

**Issue by sanketjirapure** [TheImagingSource/tiscamera#42]
Hello,
I'm using USB 3.0 supported DFK23UX236 camera module on Ubuntu 14.04 system. I can see video using "guvcview" command but it's showing grey. I followed all the steps mentioned for buiding gstreamer module. I am getting following error after applying command for gstreamer:

root@alpr-LGE-MAINBD:~# gst-launch-0.10 v4l2src ! video/x-raw-gray ! tisvideobufferfilter ! tis_auto_exposure ! tiscolorize ! queue ! tiswhitebalance ! queue ! bayer2rgb ! queue ! ffmpegcolorspace ! ximagesink
WARNING: erroneous pipeline: no element "bayer2rgb"

The formats for camera module are shown beow: 
alpr@alpr-LGE-MAINBD:~$ v4l2-ctl --list-formats -d /dev/video1
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'GREY'
	Name        : Greyscale 8-bit (Y800)

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'GBRG'
	Name        : GBRG Bayer (GBRG)

	Index       : 2
	Type        : Video Capture
	Pixel Format: 'Y16 '
	Name        : Greyscale 16-bit (Y16 )

	Index       : 3
	Type        : Video Capture
	Pixel Format: ''
	Name        : 36314247-0000-0010-8000-00aa003

Thanks in advance.

**Comment by TIS-Stefan** [comment]
Debayering for color must be done in the camera. Please follow the steps shown on
https://github.com/TheImagingSource/tiscamera/wiki/Getting-Started-with-USB-2.0-cameras-on-a-Raspberry-PI-or-on-other-Linux-Systems
