### ISSUE TITLE
Discrepancy between FPS and camera properties

### ISSUE THREAD

**Issue by ilya71ru** [TheImagingSource/tiscamera#430]
I have camera DMK 33UX250
I'm using example 3 (https://github.com/TheImagingSource/tiscamera/blob/master/examples/c/03-live-stream.c)
I changed a line in a line of code - GstElement* pipeline = gst_parse_launch("tcambin name=source ! videoconvert ! ximagesink", &err); 
to
"tcambin name=source ! video/x-raw,format=GRAY8,width=2448,height=2048,framerate=75/1 ! videoconvert ! appsink name=sink"
FPS increased, but only to 20-25
What is the problem?

I also change some properties of the camera, such as exposure and gain, and then read what value at the time of frame acquisition. When the next frame comes, it is written that the value is already the same as I set, but in reality it only works after a few frames. How can this be fixed? Examples of changing and reading properties were taken from the example code 2 and 3, respectively.

**Comment by ilya71ru** [comment]
video converter does not affect fps in my case.
When I set fps = 30, I get 10, when 5, I get 3.5

But this is not the main problem, I can work on such fps.

Could you suggest a solution to the second problem 
"I also change some properties of the camera, such as exposure and gain, and then read what value at the time of frame acquisition. When the next frame comes, it is written that the value is already the same as I set, but in reality it only works after a few frames. How can this be fixed? Examples of changing and reading properties were taken from the example code 2 and 3, respectively."

**Comment by ilya71ru** [comment]
```
bool TisCamera::init()
    {
        gst_debug_set_default_threshold(GST_LEVEL_WARNING);
        gst_init(nullptr, nullptr);

        const char* serial = nullptr; // the serial number of the camera we want to use
        const char* pipeline_str = "tcambin name=source ! video/x-raw,format=GRAY8,width=2448,height=2048,framerate=75/1 ! appsink name=sink";

        GError* err = nullptr;
        _pipeline = gst_parse_launch(pipeline_str, &err);

        /* test for error */
        if (!_pipeline)
        {
            L_ERROR("Could not create pipeline. Cause: %s\n", err->message);
            return false;
        }

        _source = gst_bin_get_by_name(GST_BIN(_pipeline), "source");

        if (serial)
        {
            GValue val = {};
            g_value_init(&val, G_TYPE_STRING);
            g_value_set_static_string(&val, serial);

            g_object_set_property(G_OBJECT(_source), "serial", &val);
            gst_object_unref(_source);
        }

        /* retrieve the appsink from the pipeline */
        GstElement* sink = gst_bin_get_by_name(GST_BIN(_pipeline), "sink");

        // tell appsink to notify us when it receives an image
        g_object_set(G_OBJECT(sink), "emit-signals", TRUE, nullptr);

        // tell appsink what function to call when it notifies us
        g_signal_connect(sink, "new-sample", G_CALLBACK(callback), this);

        GValue trigger = {};
        g_value_init(&trigger, G_TYPE_BOOLEAN);
        g_value_set_boolean(&trigger, TRUE);

        tcam_prop_set_tcam_property(TCAM_PROP(_source), "Trigger Mode", &trigger);

        gst_element_set_state(_pipeline, GST_STATE_PLAYING);

        GValue trigger_val = {};
        g_value_init(&trigger_val, G_TYPE_BOOLEAN);
        g_value_set_boolean(&trigger_val, TRUE);

        gboolean r = tcam_prop_set_tcam_property(TCAM_PROP(_source), "Software Trigger", &trigger_val);
        if (!r)
        {
            printf("!!! Could not trigger. !!!\n");
        }
        else
        {
            printf("=== Triggered image. ===\n");
            //sleep(2);
            //callback(sink, this);
        }

        gst_object_unref(sink);

        return true;
    }

static GstFlowReturn callback(GstElement* sink, void* user_data);
GstFlowReturn TisCamera::callback(GstElement* sink, void* user_data)
    {
        TisCamera* _this = reinterpret_cast<TisCamera*>(user_data);

        GstSample* sample = nullptr;
        /* Retrieve the buffer */
        g_signal_emit_by_name(sink, "pull-sample", &sample, nullptr);

        if (sample)
        {
            GstBuffer* buffer = gst_sample_get_buffer(sample);
            GstMapInfo info; // contains the actual image
            
            GstMeta* meta = gst_buffer_get_meta(buffer, g_type_from_name("TcamStatisticsMetaApi"));

            if (meta)
            {
                printf("We have meta\n");
            }
            else
            {
                g_warning("No meta data available\n");
            }

            GstStructure* struc = ((TcamStatisticsMeta*)meta)->structure;

            // this prints all contained fields
            gst_structure_foreach(struc, meta_struc_print, NULL);

            if (gst_buffer_map(buffer, &info, GST_MAP_READ))
            {
                GstVideoInfo* video_info = gst_video_info_new();
                if (!gst_video_info_from_caps(video_info, gst_sample_get_caps(sample)))
                {
                    // Could not parse video info (should not happen)
                    L_WARN("Failed to parse video info");
                    return GST_FLOW_ERROR;
                }

                /* Get a pointer to the image data */
                unsigned char* data = info.data;

                /* Get the pixel value of the center pixel */
                const auto stride = video_info->stride[0];

                gst_buffer_unmap(buffer, &info);
                gst_video_info_free(video_info);
            }

            // delete our reference so that gstreamer can handle the sample
            gst_sample_unref(sample);
        }
        return GST_FLOW_OK;
    }
```

**Comment by ilya71ru** [comment]
my program does not terminate, but works for a long time, but the callback function is not called. In this function I was doing a printf or a breakpoint and I don't see it working

**Comment by ilya71ru** [comment]
I was able to raise FPS by removing some of my functions from the callback function. Then the FPS reaches 30.
I switched from a single-board computer to a regular linux laptop and checked using cam-capture and there I get 75 FPS. Now my callback cannot achieve this without any of my functions

**Comment by TIS-Stefan** [comment]
I tested the "06-softwaretrigger.c" sample with an 33U camera.

```
GValue trigger_val = {};
g_value_init(&trigger_val, G_TYPE_BOOLEAN);
g_value_set_boolean(&trigger_val, TRUE);
boolean r = tcam_prop_set_tcam_property(TCAM_PROP(source), "Software Trigger", &trigger_val);
```
Works perfectly on my Ubuntu 20.04.
I extended the sample by a callback:

```
#include <unistd.h> /* sleep  */
#include <stdio.h>  /* printf */
#include <gst/gst.h>
#include <tcamprop.h>

static GstFlowReturn callback(GstElement* sink, void* user_data)
{
    GstSample* sample = NULL;
    /* Retrieve the buffer */
    g_signal_emit_by_name(sink, "pull-sample", &sample, NULL);
    if (sample)
    {
        printf("Callback!\n");
         gst_sample_unref(sample);
    }
    return GST_FLOW_OK;
}

int main (int argc, char *argv[])
{
    /* this line sets the gstreamer default logging level
       it can be removed in normal applications
       gstreamer logging can contain verry useful information
       when debugging your application
       # see https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html
       for further details
    */
    gst_debug_set_default_threshold(GST_LEVEL_WARNING);

    gst_init(&argc, &argv); // init gstreamer

    const char* serial = NULL ; // the serial number of the camera we want to use

    GError* err = NULL;

    GstElement* pipeline = gst_parse_launch("tcambin name=source ! appsink name=sink", &err);

    /* test for error */
    if (pipeline == NULL)
    {
        printf("Could not create pipeline. Cause: %s\n", err->message);
        return 1;
    }

    GstElement* source = gst_bin_get_by_name(GST_BIN(pipeline), "source");

    if (serial != NULL)
    {
        GValue val = {};
        g_value_init(&val, G_TYPE_STRING);
        g_value_set_static_string(&val, serial);

        g_object_set_property(G_OBJECT(source), "serial", &val);

        g_value_unset(&val);
    }

    /* retrieve the appsink from the pipeline */
    GstElement* sink = gst_bin_get_by_name(GST_BIN(pipeline), "sink");

    // tell appsink to notify us when it receives an image
    g_object_set(G_OBJECT(sink), "emit-signals", TRUE, NULL);

    // tell appsink what function to call when it notifies us
    g_signal_connect(sink, "new-sample", G_CALLBACK(callback), NULL);


    gst_element_set_state(pipeline, GST_STATE_PLAYING);

    /*
      This sleep exists only to ensure
      that a live image exists before trigger mode is activated.
      for all other purposes this can be removed.
     */
    sleep(2);

    GValue trigger_val = {};
    g_value_init(&trigger_val, G_TYPE_BOOLEAN);
    g_value_set_boolean(&trigger_val, TRUE);

    // Check for the type of trigger
    // Depending on the camera model trigger may be a bool or an enum
    const gchar* trigger_mode_type =  tcam_prop_get_tcam_property_type(TCAM_PROP(source),
                                                                       "Trigger Mode");

    if (!trigger_mode_type)
    {
        printf("Unable to determine type of 'Trigger Mode'\n");
        exit(1);
    }

    gboolean trigger_is_bool = TRUE;
    GValue trigger = {};

    if (strcmp(trigger_mode_type, "enum") == 0)
    {
        trigger_is_bool = FALSE;
        g_value_init(&trigger, G_TYPE_STRING);
        g_value_set_string(&trigger, "On");
        tcam_prop_set_tcam_property(TCAM_PROP(source), "Trigger Mode", &trigger);
    }
    else
    {
        g_value_init(&trigger, G_TYPE_BOOLEAN);
        g_value_set_boolean(&trigger, TRUE);

        tcam_prop_set_tcam_property(TCAM_PROP(source), "Trigger Mode", &trigger);
    }

    while (0 == 0)
    {
        printf("Press 'q' then 'enter' to stop the stream.\n");
        printf("Press 'Enter' to trigger a new image.\n");

        char c = getchar();

        if (c == 'q')
        {
            break;
        }

        gboolean r = tcam_prop_set_tcam_property(TCAM_PROP(source), "Software Trigger", &trigger_val);
        if (!r)
        {
            printf("!!! Could not trigger. !!!\n");
        }
        else
        {
            printf("=== Triggered image. ===\n");
        }
    }

    /* deactivate trigger mode */
    /* this is simply to prevent confusion when the camera ist started without wanting to trigger */

    if (trigger_is_bool)
    {
        g_value_set_boolean(&trigger, FALSE);
        tcam_prop_set_tcam_property(TCAM_PROP(source), "Trigger Mode", &trigger);
    }
    else
    {
        g_value_set_string(&trigger, "Off");
        tcam_prop_set_tcam_property(TCAM_PROP(source), "Trigger Mode", &trigger);
    }

    g_value_unset(&trigger);
    g_value_unset(&trigger_val);

    // this stops the pipeline and frees all resources
    gst_element_set_state(pipeline, GST_STATE_NULL);

    gst_object_unref(source);
    /* the pipeline automatically handles all elements that have been added to it.
       thus they do not have to be cleaned up manually */
    gst_object_unref(pipeline);

    return 0;
}

```
You may try that sample. You will see, that the callback is called after pipeline set to PLAYING state many times, until the camera is set into trigger mode.

Stefan

**Comment by ilya71ru** [comment]
> Я тестировал образец "06-softwaretrigger.c" с камерой 33U.
> 
> ```
> GValue trigger_val = {};
> g_value_init(&trigger_val, G_TYPE_BOOLEAN);
> g_value_set_boolean(&trigger_val, TRUE);
> boolean r = tcam_prop_set_tcam_property(TCAM_PROP(source), "Software Trigger", &trigger_val);
> ```
> 
> Отлично работает на моем Ubuntu 20.04. Я расширил образец обратным вызовом:
> 
> ```
> #include <unistd.h> /* sleep  */
> #include <stdio.h>  /* printf */
> #include <gst/gst.h>
> #include <tcamprop.h>
> 
> static GstFlowReturn callback(GstElement* sink, void* user_data)
> {
>     GstSample* sample = NULL;
>     /* Retrieve the buffer */
>     g_signal_emit_by_name(sink, "pull-sample", &sample, NULL);
>     if (sample)
>     {
>         printf("Callback!\n");
>          gst_sample_unref(sample);
>     }
>     return GST_FLOW_OK;
> }
> 
> int main (int argc, char *argv[])
> {
>     /* this line sets the gstreamer default logging level
>        it can be removed in normal applications
>        gstreamer logging can contain verry useful information
>        when debugging your application
>        # see https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html
>        for further details
>     */
>     gst_debug_set_default_threshold(GST_LEVEL_WARNING);
> 
>     gst_init(&argc, &argv); // init gstreamer
> 
>     const char* serial = NULL ; // the serial number of the camera we want to use
> 
>     GError* err = NULL;
> 
>     GstElement* pipeline = gst_parse_launch("tcambin name=source ! appsink name=sink", &err);
> 
>     /* test for error */
>     if (pipeline == NULL)
>     {
>         printf("Could not create pipeline. Cause: %s\n", err->message);
>         return 1;
>     }
> 
>     GstElement* source = gst_bin_get_by_name(GST_BIN(pipeline), "source");
> 
>     if (serial != NULL)
>     {
>         GValue val = {};
>         g_value_init(&val, G_TYPE_STRING);
>         g_value_set_static_string(&val, serial);
> 
>         g_object_set_property(G_OBJECT(source), "serial", &val);
> 
>         g_value_unset(&val);
>     }
> 
>     /* retrieve the appsink from the pipeline */
>     GstElement* sink = gst_bin_get_by_name(GST_BIN(pipeline), "sink");
> 
>     // tell appsink to notify us when it receives an image
>     g_object_set(G_OBJECT(sink), "emit-signals", TRUE, NULL);
> 
>     // tell appsink what function to call when it notifies us
>     g_signal_connect(sink, "new-sample", G_CALLBACK(callback), NULL);
> 
> 
>     gst_element_set_state(pipeline, GST_STATE_PLAYING);
> 
>     /*
>       This sleep exists only to ensure
>       that a live image exists before trigger mode is activated.
>       for all other purposes this can be removed.
>      */
>     sleep(2);
> 
>     GValue trigger_val = {};
>     g_value_init(&trigger_val, G_TYPE_BOOLEAN);
>     g_value_set_boolean(&trigger_val, TRUE);
> 
>     // Check for the type of trigger
>     // Depending on the camera model trigger may be a bool or an enum
>     const gchar* trigger_mode_type =  tcam_prop_get_tcam_property_type(TCAM_PROP(source),
>                                                                        "Trigger Mode");
> 
>     if (!trigger_mode_type)
>     {
>         printf("Unable to determine type of 'Trigger Mode'\n");
>         exit(1);
>     }
> 
>     gboolean trigger_is_bool = TRUE;
>     GValue trigger = {};
> 
>     if (strcmp(trigger_mode_type, "enum") == 0)
>     {
>         trigger_is_bool = FALSE;
>         g_value_init(&trigger, G_TYPE_STRING);
>         g_value_set_string(&trigger, "On");
>         tcam_prop_set_tcam_property(TCAM_PROP(source), "Trigger Mode", &trigger);
>     }
>     else
>     {
>         g_value_init(&trigger, G_TYPE_BOOLEAN);
>         g_value_set_boolean(&trigger, TRUE);
> 
>         tcam_prop_set_tcam_property(TCAM_PROP(source), "Trigger Mode", &trigger);
>     }
> 
>     while (0 == 0)
>     {
>         printf("Press 'q' then 'enter' to stop the stream.\n");
>         printf("Press 'Enter' to trigger a new image.\n");
> 
>         char c = getchar();
> 
>         if (c == 'q')
>         {
>             break;
>         }
> 
>         gboolean r = tcam_prop_set_tcam_property(TCAM_PROP(source), "Software Trigger", &trigger_val);
>         if (!r)
>         {
>             printf("!!! Could not trigger. !!!\n");
>         }
>         else
>         {
>             printf("=== Triggered image. ===\n");
>         }
>     }
> 
>     /* deactivate trigger mode */
>     /* this is simply to prevent confusion when the camera ist started without wanting to trigger */
> 
>     if (trigger_is_bool)
>     {
>         g_value_set_boolean(&trigger, FALSE);
>         tcam_prop_set_tcam_property(TCAM_PROP(source), "Trigger Mode", &trigger);
>     }
>     else
>     {
>         g_value_set_string(&trigger, "Off");
>         tcam_prop_set_tcam_property(TCAM_PROP(source), "Trigger Mode", &trigger);
>     }
> 
>     g_value_unset(&trigger);
>     g_value_unset(&trigger_val);
> 
>     // this stops the pipeline and frees all resources
>     gst_element_set_state(pipeline, GST_STATE_NULL);
> 
>     gst_object_unref(source);
>     /* the pipeline automatically handles all elements that have been added to it.
>        thus they do not have to be cleaned up manually */
>     gst_object_unref(pipeline);
> 
>     return 0;
> }
> ```
> 
> Вы можете попробовать этот образец. Вы увидите, что обратный вызов вызывается после многократного перехода конвейера в состояние PLAYING, пока камера не будет переведена в режим триггера. Затем вы можете нажать клавишу Enter, чтобы запустить программные триггеры.
> 
> Стефан
I tried your code. The software trigger is working. But the maximum FPS on my laptop still does not exceed 30.
