### ISSUE TITLE
Starting camera in suspended state

### ISSUE THREAD

**Issue by lkucalaba** [TheImagingSource/tiscamera#431]
Hello, we would like to have full control over triggering captures but we are receiving a couple frames right when we open the camera connection that we aren't able to prevent or purge out. It's almost like these images were captured a long time ago and they are just sitting a buffer waiting to be consumed. Is there a way to start up the camera in a suspended state, or to purge the internal buffers, or to eliminate buffering entirely?  I saw a post where someone suggested setting the appsink max-buffers to one--does that work?  Any suggestions you can offer would be wonderful. Thanks! 
-Luke Kucalaba
Path Robotics, Inc.

**Comment by TIS-Stefan** [comment]
I am very sorry, but currently there is no way. The pipeline wont change into playing state, if no frames are sent through the pipeline. 
Therefore, I use a flag in the custom data, that passed to the callback functions. The flag controls, whether a frame should be discarded or handled. 

Sorry for not having a better way at this point of time.

Stefan

**Comment by lkucalaba** [comment]
Thanks for the quick response Stefan.  We are already doing this approach with passing flags via the callback context pointer, and for the most part it works well after establishing the initial connection and the pipeline stream starts playing.  But the very first instant when we connect, we get a bunch of unsolicited frames before we can have the opportunity to enable trigger mode to command the camera to stop sending us frames.  

Can we use timestamps to filter out old captures?  Are timestamps embedded in the capture buffer itself (when the capture actually occurred), or are they just grabbed from the system clock when processed in the callback?  This is the code i am referencing from the appsink example on the "new sample" callback:

          ::GstClockTime timestamp = GST_BUFFER_PTS(p_buffer);

Are these timestamps relative based on the time when the pipeline initially started playing?  What is the timestamp epoch event (when time=0) ?   I would really like to be able to filter out old captures based on the timestamp, using the logic that if the timestamp of the capture is before when we request it (when we send a trigger command) then it must be an old leftover capture.  How can I get the current timestamp from the system clock in the same way so it can be compared to the timestamp embedded in the capture buffer?

Thanks,
-Luke
