### ISSUE TITLE
Error when removing the tiscamera

### ISSUE THREAD

**Issue by seymseym** [TheImagingSource/tiscamera#434]
**My OS:
Distributor ID: Ubuntu
Description: Ubuntu 18.04.6 LTS
Release: 18.04
Codename: bionic**

Tiscamera was working fine like 2-3 days before and it totally crashed then.
Now, I can see it on the applications but nothing happens when I click on it.

It can be seen on the applications; but it can not be seen from the software center.

So, I want to delete all the things (even configurations, everyting) about it and reinstall again. But I can not delete it from the software center,etc.  

I tried to use command line but got these errors:

```
(base) upboard@upboard:~$ sudo dpkg --purge tiscamera
dpkg: dependency problems prevent removal of tiscamera:
 tiscamera-dutils depends on tiscamera-tcamprop; however:
  Package tiscamera-tcamprop is not installed.
  Package tiscamera which provides tiscamera-tcamprop is to be removed.

dpkg: error processing package tiscamera (--purge):
 dependency problems - not removing
Errors were encountered while processing:
 tiscamera
```

It says Package tiscamera-tcamprop is not installed. But I have installed everything like tons of times from the tutorial on the Github. I also installed tiscamera_0.14.0.3054_amd64_ubuntu_1804.deb and tiscamera-dutils_0.14.0.403_amd64.deb from the web site, using command line again. But it still insists like sth did not install so you can not remove..

**Comment by TIS-Stefan** [comment]
Hallo

Please use

sudo apt remove tiscamera

Stefan
