### ISSUE TITLE
gi.repository.GLib.Error: gst_parse_error: no element "Collection" (1)

### ISSUE THREAD

**Issue by vinit13792** [TheImagingSource/tiscamera#449]
System specs:
Ubuntu 20.04
8GB RAM
DFK 37BUX178 6.3MP color camera.

I installed from source using all the instructions mentioned [here](https://github.com/TheImagingSource/tiscamera).

When i "Save Image" using tcam-capture, I get the following error:

`(tcam-capture:57615): GStreamer-CRITICAL **: 16:38:06.206: gst_element_make_from_uri: assertion 'gst_uri_is_valid (uri)' failed`
`Traceback (most recent call last):`
`  File "/home/ubuntu/tiscamera/tools/tcam-capture/tcam-capture", line 420, in save_image_action`
`    self.view.save_image(self.settings.get_image_type())`
`  File "/home/ubuntu/tiscamera/tools/tcam-capture/tcam_capture/TcamView.py", line 190, in save_image`
`    self.imagesaver.save_image(get_encoder_dict()[image_type])`
`  File "/home/ubuntu/tiscamera/tools/tcam-capture/tcam_capture/MediaSaver.py", line 246, in save_image`
`    self._create_pipeline()`
`  File "/home/ubuntu/tiscamera/tools/tcam-capture/tcam_capture/MediaSaver.py", line 146, in _create_pipeline`
`    self.pipeline = Gst.parse_launch(save_str)`
`gi.repository.GLib.Error: gst_parse_error: no element "Collection" (1)`

And no image is saved in the default folder after clicking "Save Image"

**Comment by TIS-Stefan** [comment]
Hello

Maybe tcam-capture does not find any Gstreamer encoder modules. Which is strange. Please run
gst-inspect-1.0 pngenc. It should show the properties of the png encode.

Stefan

**Comment by vinit13792** [comment]
> Hello
> 
> Maybe tcam-capture does not find any Gstreamer encoder modules. Which is strange. Please run gst-inspect-1.0 pngenc. It should show the properties of the png encode.
> 
> Stefan

Hi Stefan,

I get the following output after running `gst-inspect-1.0 pngenc`:

`Factory Details:`
`  Rank                     primary (256)`
`  Long-name                PNG image encoder`
`  Klass                    Codec/Encoder/Image`
`  Description              Encode a video frame to a .png image`
`  Author                   Jeremy SIMON <jsimon13@yahoo.fr>`

`Plugin Details:`
`  Name                     png`
`  Description              PNG plugin library`
`  Filename                 /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstpng.so`
`  Version                  1.16.2`
`  License                  LGPL`
`  Source module            gst-plugins-good`
`  Source release date      2019-12-03`
`  Binary package           GStreamer Good Plugins (Ubuntu)`
`  Origin URL               https://launchpad.net/distros/ubuntu/+source/gst-plugins-good1.0`

`GObject`
` +----GInitiallyUnowned`
`       +----GstObject`
`             +----GstElement`
`                   +----GstVideoEncoder`
`:

**Comment by TIS-Stefan** [comment]
Hello

Lets see, whether you get an image at all in your other support case

Stefan

**Comment by TIS-Stefan** [comment]
If you look into the source code of tcam-capture you find in /MediaSaver.py"

```
   self.encoder_dict = get_encoder_dict()
  self.image_encoder = self.encoder_dict["png"]
```
get_encoder_dict() uses:
```
    if Gst.ElementFactory.find("pngenc") is not None:
        encoder_dict["png"] = Encoder("png", "pngenc", MediaType.image, "png")
``` 
I conclude, that tcam-capture can not find pngenc. Therefore, It may is possible, that tcam-capture runs in a different environment, than gst-inspect. In case you use Anaconda or Pythonbox(?), you must add the GStreamer search paths to these environments. 

Stefan

**Comment by vinit13792** [comment]
Hi Stefan,

I actually formatted the system, and re-installed Ubuntu and tiscamera, it started working. I guess there was some issue with the path

**Comment by vinit13792** [comment]
Hi Stefan,

This is recurring issue, formatting a OS cannot be an option always. Is there any particular reason why this keeps happening?

**Comment by TIS-Stefan** [comment]
You are nearly the only one with this issue. Therefore, I wonder, what is different on your computers compared to most others.

Do you use  Anaconda or Pythonbox?
Do you use a Docker container?
Did you change the standard path of Gstreamer etc?

Stefan

**Comment by vinit13792** [comment]
> Do you use Anaconda or Pythonbox?

Hi Stefan,

Do you use Anaconda or Pythonbox? No

Do you use a Docker container? No

Did you change the standard path of Gstreamer etc? How to find the gstreamer path? and how to add it to path?

Since it worked once, what did you change, so it does not work anymore? I uninstalled the tiscamera, and reinstalled, and then this error ocurred.

**Comment by TIS-Stefan** [comment]
> I am using ubuntu 20.04, followed tiscamera install guide on github There was no environment of anaconda involved here. This error occurred and i re-installed the tiscamera after uninstalling it from build directory

Did that work?

Stefan

**Comment by vinit13792** [comment]
> > I am using ubuntu 20.04, followed tiscamera install guide on github There was no environment of anaconda involved here. This error occurred and i re-installed the tiscamera after uninstalling it from build directory
> 
> Did that work?
> 
> Stefan

Hi Stefan,

It didnt work.

**Comment by TIS-Stefan** [comment]
But you wrote, it worked once at https://github.com/vinit13792. Therefore, what changed since then?

Stefan

**Comment by vinit13792** [comment]
> But you wrote, it worked once at https://github.com/vinit13792. Therefore, what changed since then?
> 
> Stefan

So to make aravis work, i tried uninstalling, and then re-installed tiscamera again. And since then this error shows up everytime i try to click an image.

**Comment by TIS-Stefan** [comment]
Please show me your cmake line. It should be 
`
cmake -DBUILD_ARAVIS=ON  -DTCAM_ARAVIS_USB_VISION=ON ..
`
Then rebuild and run sudo make install.

(Source : https://www.theimagingsource.com/documentation/tiscamera/building.html)

Stefan

**Comment by vinit13792** [comment]
> Please show me your cmake line. It should be `cmake -DBUILD_ARAVIS=ON -DTCAM_ARAVIS_USB_VISION=ON ..` Then rebuild and run sudo make install.
> 
> (Source : https://www.theimagingsource.com/documentation/tiscamera/building.html)
> 
> Stefan

Hi Stefan,

I actually did a fresh ubuntu install, and then installed tiscamera using the tutorial mentioned [here].(https://www.theimagingsource.com/documentation/tiscamera/tutorial.html)

**Comment by vinit13792** [comment]
> Please show me your cmake line. It should be `cmake -DBUILD_ARAVIS=ON -DTCAM_ARAVIS_USB_VISION=ON ..` Then rebuild and run sudo make install.
> 
> (Source : https://www.theimagingsource.com/documentation/tiscamera/building.html)
> 
> Stefan

Hi Stefan,

I just rebooted my computer, and i got the same error. `gi.repository.GLib.Error: gst_parse_error: no element "Collection" (1)`

So i followed the cmake line as you suggested, and i got the following:

There were two errors at the end.

`[  0%] Performing configure step for 'aravis'
`autoreconf: Entering directory `.'`
`autoreconf: configure.ac: not using Gettext
`autoreconf: running: aclocal --force -I m4`
`autoreconf: configure.ac: tracing`
`autoreconf: running: libtoolize --copy --force`
`libtoolize: putting auxiliary files in '.'.`
`libtoolize: copying file './ltmain.sh'`
`libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
`libtoolize: copying file 'm4/libtool.m4'
`libtoolize: copying file 'm4/ltoptions.m4'
`libtoolize: copying file 'm4/ltsugar.m4'
`libtoolize: copying file 'm4/ltversion.m4'
`libtoolize: copying file 'm4/lt~obsolete.m4'
`autoreconf: running: /usr/bin/autoconf --force`
`autoreconf: running: /usr/bin/autoheader --force`
`autoreconf: running: automake --add-missing --copy --force-missing`
`configure.ac:31: installing './compile'
`configure.ac:10: installing './missing'
`gst-0.10/Makefile.am: installing './depcomp'
`autoreconf: Leaving directory `.'
`checking for a BSD-compatible install... /usr/bin/install -c`
`checking whether build environment is sane... yes`
`checking for a thread-safe mkdir -p... /usr/bin/mkdir -p`
`checking for gawk... no`
`checking for mawk... mawk`
`checking whether make sets $(MAKE)... yes`
`checking whether make supports nested variables... yes`
`checking whether to enable maintainer-specific portions of Makefiles... no`
`checking whether make supports nested variables... (cached) yes`
`checking whether make supports the include directive... yes (GNU style)`
`checking for gcc... gcc`
`checking whether the C compiler works... yes`
`checking for C compiler default output file name... a.out`
`checking for suffix of executables... `
`checking whether we are cross compiling... no`
`checking for suffix of object files... o`
`checking whether we are using the GNU C compiler... yes`
`checking whether gcc accepts -g... yes`
`checking for gcc option to accept ISO C89... none needed`
`checking whether gcc understands -c and -o together... yes`
`checking dependency style of gcc... none`
`checking for library containing strerror... none required`
`checking for gcc... (cached) gcc`
`checking whether we are using the GNU C compiler... (cached) yes`
`checking whether gcc accepts -g... (cached) yes`
`checking for gcc option to accept ISO C89... (cached) none needed`
`checking whether gcc understands -c and -o together... (cached) yes`
`checking dependency style of gcc... (cached) none`
`checking for g++... g++`
`checking whether we are using the GNU C++ compiler... yes`
`checking whether g++ accepts -g... yes`
`checking dependency style of g++... none`
`checking how to run the C preprocessor... gcc -E`
`checking for grep that handles long lines and -e... /usr/bin/grep`
`checking for egrep... /usr/bin/grep -E`
`checking for ANSI C header files... yes`
`checking for sys/types.h... yes`
`checking for sys/stat.h... yes`
`checking for stdlib.h... yes`
`checking for string.h... yes`
`checking for memory.h... yes`
`checking for strings.h... yes`
`checking for inttypes.h... yes`
`checking for stdint.h... yes`
`checking for unistd.h... yes`
`checking locale.h usability... yes`
`checking locale.h presence... yes`
`checking for locale.h... yes`
`checking for LC_MESSAGES... yes`
`checking for CFPreferencesCopyAppValue... no`
`checking for CFLocaleCopyCurrent... no`
`checking libintl.h usability... yes`
`checking libintl.h presence... yes`
`checking for libintl.h... yes`
`checking for ngettext in libc... yes`
`checking for dgettext in libc... yes`
`checking for bind_textdomain_codeset... yes`
`checking for msgfmt... /usr/bin/msgfmt`
`checking for dcgettext... yes`
`checking if msgfmt accepts -c... yes`
`checking for gmsgfmt... /usr/bin/msgfmt`
`checking for xgettext... /usr/bin/xgettext`
`checking whether NLS is requested... yes`
`checking for intltool >= 0.31.2... 0.51.0 found`
`checking for intltool-update... /usr/bin/intltool-update`
`checking for intltool-merge... /usr/bin/intltool-merge`
`checking for intltool-extract... /usr/bin/intltool-extract`
`checking for xgettext... (cached) /usr/bin/xgettext`
`checking for msgmerge... /usr/bin/msgmerge`
`checking for msgfmt... (cached) /usr/bin/msgfmt`
`checking for gmsgfmt... (cached) /usr/bin/msgfmt`
`checking for perl... /usr/bin/perl`
`checking for perl >= 5.8.1... 5.30.0`
`checking for XML::Parser... ok`
`checking build system type... x86_64-pc-linux-gnu`
`checking host system type... x86_64-pc-linux-gnu`
`checking how to print strings... printf`
`checking for a sed that does not truncate output... /usr/bin/sed`
`checking for fgrep... /usr/bin/grep -F`
`checking for ld used by gcc... /usr/bin/ld`
`checking if the linker (/usr/bin/ld) is GNU ld... yes`
`checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B`
`checking the name lister (/usr/bin/nm -B) interface... BSD nm`
`checking whether ln -s works... yes`
`checking the maximum length of command line arguments... 1572864`
`checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop`
`checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop`
`checking for /usr/bin/ld option to reload object files... -r`
`checking for objdump... objdump`
`checking how to recognize dependent libraries... pass_all`
`checking for dlltool... no`
`checking how to associate runtime and link libraries... printf %s\n`
`checking for ar... ar`
`checking for archiver @FILE support... @`
`checking for strip... strip`
`checking for ranlib... ranlib`
`checking command to parse /usr/bin/nm -B output from gcc object... ok`
`checking for sysroot... no`
`checking for a working dd... /usr/bin/dd`
`checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1`
`checking for mt... mt`
`checking if mt is a manifest tool... no`
`checking for dlfcn.h... yes`
`checking for objdir... .libs`
`checking if gcc supports -fno-rtti -fno-exceptions... no`
`checking for gcc option to produce PIC... -fPIC -DPIC`
`checking if gcc PIC flag -fPIC -DPIC works... yes`
`checking if gcc static flag -static works... yes`
`checking if gcc supports -c -o file.o... yes`
`checking if gcc supports -c -o file.o... (cached) yes`
`checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes`
`checking whether -lc should be explicitly linked in... no`
`checking dynamic linker characteristics... GNU/Linux ld.so`
`checking how to hardcode library paths into programs... immediate`
`checking whether stripping libraries is possible... yes`
`checking if libtool supports shared libraries... yes`
`checking whether to build shared libraries... yes`
`checking whether to build static libraries... yes`
`checking how to run the C++ preprocessor... g++ -E`
`checking for ld used by g++... /usr/bin/ld -m elf_x86_64`
`checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes`
`checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes`
`checking for g++ option to produce PIC... -fPIC -DPIC`
`checking if g++ PIC flag -fPIC -DPIC works... yes`
`checking if g++ static flag -static works... yes`
`checking if g++ supports -c -o file.o... yes`
`checking if g++ supports -c -o file.o... (cached) yes`
`checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes`
`checking dynamic linker characteristics... (cached) GNU/Linux ld.so`
`checking how to hardcode library paths into programs... immediate`
`checking for valgrind... no`
`checking whether to build with code coverage support... no`
`checking for pkg-config... /usr/bin/pkg-config`
`checking pkg-config is at least version 0.14... yes`
`checking for ARAVIS_USB... yes`
`checking for ARAVIS... yes`
`checking for asan flags... no`
`checking for glib-mkenums... /usr/bin/glib-mkenums`
`checking for gobject-introspection... yes`
`checking for gtk-doc... yes`
`checking for gtkdoc-check... gtkdoc-check.test`
`checking for gtkdoc-check... /usr/bin/gtkdoc-check`
`checking for gtkdoc-rebase... /usr/bin/gtkdoc-rebase`
`checking for gtkdoc-mkpdf... /usr/bin/gtkdoc-mkpdf`
`checking whether to build gtk-doc documentation... no`
`checking for GTKDOC_DEPS... yes`
`checking for appstream-util... no`
`checking that generated files are newer than configure... done`
`configure: creating ./config.status`
`config.status: creating Makefile`
`config.status: creating src/Makefile`
`config.status: creating src/arvfeatures.h`
`config.status: creating src/arvversion.h`
`config.status: creating viewer/Makefile`
`config.status: creating viewer/data/Makefile`
`config.status: creating viewer/data/arv-viewer.desktop.in`
`config.status: creating viewer/data/arv-viewer.appdata.xml`
`config.status: creating gst/Makefile`
`config.status: creating gst-0.10/Makefile`
`config.status: creating tests/Makefile`
`config.status: creating po/Makefile.in`
`config.status: creating man/Makefile`
`config.status: creating docs/Makefile`
`config.status: creating docs/reference/Makefile`
`config.status: creating docs/reference/aravis/Makefile`
`config.status: creating aravis.pc`
`config.status: creating src/arvconfig.h`
`config.status: executing depfiles commands`
`config.status: executing default-1 commands`
`config.status: executing libtool commands`
`config.status: executing po/stamp-it commands`

`Configuration:`

 ` Compiler:                     gcc`
 ` Compiler flags:               -pthread -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libusb-1.0`
`  Linker flags:                 -lm -lgio-2.0 -lgobject-2.0 -lxml2 -lgthread-2.0 -pthread -lglib-2.0 -lz -lusb-1.0`

`  Build USB support:            yes`
`  Build packet socket support:  no`
`  Build viewer:                 no`
`  Build gstreamer plugin:       no`
`  Build gstreamer-0.10 plugin:  no`
`  Build with fast heartbeat:    yes`
`  Build with address sanitizer: no`

`[  1%] Performing build step for 'aravis'`
`Making all in src`
`  CC       arvuvinterface.lo`
`  CC       arvuvdevice.lo`
`  CC       arvuvstream.lo`
`  CC       arvuvcp.lo`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvcp.c: In function ‘arv_uvcp_packet_type_to_string’:`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvcp.c:127:29: error: ‘ARV_TYPE_UVCP_PACKET_TYPE’ undeclared (first use `in this function); did you mean ‘ARV_TYPE_GVCP_PACKET_TYPE’?`
`  127 |  return arv_enum_to_string (ARV_TYPE_UVCP_PACKET_TYPE, value);`
`      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~`
`      |                             ARV_TYPE_GVCP_PACKET_TYPE`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvcp.c:127:29: note: each undeclared identifier is reported only once for each function it appears in`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvcp.c: In function ‘arv_uvcp_command_to_string’:`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvcp.c:133:29: error: ‘ARV_TYPE_UVCP_COMMAND’ undeclared (first use in this function); did you mean ‘ARV_TYPE_GVCP_COMMAND’?`
`  133 |  return arv_enum_to_string (ARV_TYPE_UVCP_COMMAND, value);`
`      |                             ^~~~~~~~~~~~~~~~~~~~~`
`      |                             ARV_TYPE_GVCP_COMMAND`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvcp.c: In function ‘arv_uvcp_packet_type_to_string’:`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvcp.c:128:1: warning: control reaches end of non-void function [-Wreturn-type]`
`  128 | }`
`      | ^`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvcp.c: In function ‘arv_uvcp_command_to_string’:`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvcp.c:134:1: warning: control reaches end of non-void function [-Wreturn-type]
`  134 | }`
`      | ^`
`make[5]: *** [Makefile:952: arvuvcp.lo] Error 1`
`make[5]: *** Waiting for unfinished jobs....`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvinterface.c: In function ‘arv_uv_interface_init’:`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvinterface.c:369:13: warning: Deprecated pre-processor symbol, replace with 
  369 |  uv_interface->priv = G_TYPE_INSTANCE_GET_PRIVATE (uv_interface, ARV_TYPE_UV_INTERFACE, ArvUvInterfacePrivate);`
`      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvdevice.c: In function ‘arv_uv_device_init’:`
`/home/ubuntu/tiscamera/external/aravis/src/arvuvdevice.c:748:13: warning: Deprecated pre-processor symbol, replace with 
`  748 |  uv_device->priv = G_TYPE_INSTANCE_GET_PRIVATE (uv_device, ARV_TYPE_UV_DEVICE, ArvUvDevicePrivate);`
`      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`/home/ubuntu/tiscamera/external/aravis/src/arvuvstream.c: In function ‘arv_uv_stream_init’:
`/home/ubuntu/tiscamera/external/aravis/src/arvuvstream.c:418:13: warning: Deprecated pre-processor symbol, replace with 
  418 |  uv_stream->priv = G_TYPE_INSTANCE_GET_PRIVATE (uv_stream, ARV_TYPE_UV_STREAM, ArvUvStreamPrivate);`
`      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`make[4]: *** [Makefile:702: all] Error 2`
`make[3]: *** [Makefile:583: all-recursive] Error 1`
`make[2]: *** [external/CMakeFiles/aravis.dir/build.make:113: external/aravis-prefix/src/aravis-stamp/aravis-build] Error 2`
`make[1]: *** [CMakeFiles/Makefile2:638: external/CMakeFiles/aravis.dir/all] Error 2`
`make: *** [Makefile:152: all] Error 2`

**Comment by TIS-Stefan** [comment]
Hello

what happens here:

> /home/ubuntu/tiscamera/external/aravis/src/arvuvcp.c:133:29: error: ‘ARV_TYPE_UVCP_COMMAND’ undeclared (first use in this function); did you mean ‘ARV_TYPE_GVCP_COMMAND’?

Why is there an error, we do not get`?
what is the cmake command line you use?

**Comment by vinit13792** [comment]
I give up.

I did a reset on Ubuntu system, updated my system. And then installed tiscamera. It worked well on day 1. Next day when I fired up my system, and clicked an image, it gave the same error. I do not understand why is this happening just over a reboot.

**Comment by TIS-Stefan** [comment]
Hello

If a reboot destroys all, then the first question is, how did you install tiscamera?
How do you execute tcam-capture? From terminal or desktop?
what happens if open a terminal and enter
```
cd tiscamera/build
. ./env.sh
tcam-capture
```
You may ask yourself, what happens on reboot on your system, that does no happen on all other computers?
Do you have kind of reset program?
Do you run in a virtual machine?

Stefan

**Comment by vinit13792** [comment]
> Hello
> 
> If a reboot destroys all, then the first question is, how did you install tiscamera? How do you execute tcam-capture? From terminal or desktop? what happens if open a terminal and enter
> 
> ```
> cd tiscamera/build
> . ./env.sh
> tcam-capture
> ```
> 
> You may ask yourself, what happens on reboot on your system, that does no happen on all other computers? Do you have kind of reset program? Do you run in a virtual machine?
> 
> Stefan

how did you install tiscamera? with the help of instructions mentioned on Tiscamera github

How do you execute tcam-capture? using terminal

what happens if open a terminal and enter `cd tiscamera/build . ./env.sh tcam-capture` ? tcam-capture opens.

Do you have kind of reset program? No I do not.

Do you run in a virtual machine? No, its an old HP 7th gen 8gb laptop.

You may ask yourself, what happens on reboot on your system? I think there might be some disk errors. because before installing Ubuntu, the setup checks for disk errors, and there were some 6 errors found in disk checks. I think those disk checks has something to do withthis problem which is causing some important files to corrupt

**Comment by vinit13792** [comment]
> If you look into the source code of tcam-capture you find in /MediaSaver.py"
> 
> ```
>    self.encoder_dict = get_encoder_dict()
>   self.image_encoder = self.encoder_dict["png"]
> ```
> 
> get_encoder_dict() uses:
> 
> ```
>     if Gst.ElementFactory.find("pngenc") is not None:
>         encoder_dict["png"] = Encoder("png", "pngenc", MediaType.image, "png")
> ```
> 
> I conclude, that tcam-capture can not find pngenc. Therefore, It may is possible, that tcam-capture runs in a different environment, than gst-inspect. In case you use Anaconda or Pythonbox(?), you must add the GStreamer search paths to these environments.
> 
> Stefan

you must add the GStreamer search paths to these environments... How to add Gstreamer search paths to environment?

**Comment by TIS-Stefan** [comment]
Hi

> what happens if open a terminal and enter cd tiscamera/build . ./env.sh tcam-capture ? tcam-capture opens.

Do you get a live stream and are you able to save images?
the ". ./env.sh" sets include paths for the tiscamera files to your current build directory. 

> I think there might be some disk errors. because before installing Ubuntu, the setup checks for disk errors, and there were some 6 errors found in disk checks. I think those disk checks has something to do with this problem which is causing some important files to corrupt

I do not think, this could be an issue, but who knows? That could be possible. 

> How to add Gstreamer search paths to environment?

Use the GST_PLUGIN_PATH environment variable to point at the directory you want. Please see https://stackoverflow.com/questions/2120444/gstreamer-plugin-search-path
and https://gstreamer.freedesktop.org/documentation/gstreamer/gstregistry.html?gi-language=c

Stefan

**Comment by vinit13792** [comment]
Hi Stefan,

I dont know the logic behind using gst plugin path and how that would make a difference since i am not installing anything else apart from tiscamera. The building from source does exactly the same thing. So I am not sure how this would make a difference.

**Comment by vinit13792** [comment]
Also, I tried tcam-capture --reset, and the error disappeared and it started saving the image in the given folder.

**Comment by TIS-Stefan** [comment]
Hi

> I dont know the logic behind using gst plugin path and how that would make a difference since i am not installing anything else apart from tiscamera.

Welcome to Linux. It is also about installing additional packages.  However, I am guessing. 

> Also, I tried tcam-capture --reset, and the error disappeared and it started saving the image in the given folder.

Where to go from here? I have no more ideas. 

Stefan

**Comment by vinit13792** [comment]
> Hi
> 
> > I dont know the logic behind using gst plugin path and how that would make a difference since i am not installing anything else apart from tiscamera.
> 
> Welcome to Linux. It is also about installing additional packages. However, I am guessing.
> 
> > Also, I tried tcam-capture --reset, and the error disappeared and it started saving the image in the given folder.
> 
> Where to go from here? I have no more ideas.
> 
> Stefan

`Welcome to Linux. It is also about installing additional packages. However, I am guessing.` I agree I am new to Linux, but i thought gstreamer was being installed as a dependency with tiscamera. 

`Where to go from here? I have no more ideas.` Well i think anyone who gets this similar error can do a `tcam-capture --reset` and check it out themselves if it works for them or not. We can close this issue for now.

**Comment by TIS-Stefan** [comment]
Until now, you are the only one with this error. That makes it so hard to narrow down. 

Stefan

**Comment by vinit13792** [comment]
Hi Stefan,

Yeah i guess you are right, because I searched for the same issue and i couldn't find anything anywhere. So I think its better if its open.

Vinit

**Comment by TIS-Stefan** [comment]
Hi Vinit

ok. 

What do you want to do with the camera? Maybe programs like "qv4l2" are sufficient for you.

Stefan

**Comment by vinit13792** [comment]
Hi Stefan,

I am working on a instance segmentation problem. I need the camera to click and save a color accurate image and save it in a folder. I want to take it a step further by automating this process soon by sending software triggers. But for software triggers i read in your documentation that all the automatics need to be `Turned OFF`. Hence i may have to just stream the video with all the automatics enabled and snap an image from the video stream. 

Could you please elaborate on the qv4l2 part? i didn't understand what that refers to.

Vinit

**Comment by TIS-Stefan** [comment]
Hello Vinit

qv4l2 is a program. Install with 
sudo apt install qv4l2.

But it is a program, no SDK. It is just for testing and see, whether you can access the camera, even after a reboot.  

Stefan

**Comment by vinit13792** [comment]
Hi Stefan,

So i shutdown my system yesterday, booted it today, and i am able to access camera. Snap and save an image using `tcam-capture`

Vinit

**Comment by TIS-Stefan** [comment]
Hi Vinit

it seems, it is a good day to start programming!

Maybe you get some ideas from https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples

Stefan

**Comment by vinit13792** [comment]
Yes. Definitely!!

Vinit

**Comment by TIS-Edgar** [comment]
Closed due to inactivity.
