### ISSUE TITLE
is there a way to uninstall tiscamera?

### ISSUE THREAD

**Issue by vinit13792** [TheImagingSource/tiscamera#450]
Is there a way to uninstall tiscamera?

I tried rm -r tiscamera in the home dir. but it only removes the directory.

**Comment by TIS-Stefan** [comment]
Yes. If you installed with
sudo make install
then you use
sudo make uninstall. 

That removes the files from the /usr/* directories. After doing this, you can remove the tiscamera directory from your home directory.

Stefan

**Comment by vinit13792** [comment]
> Yes. If you installed with sudo make install then you use sudo make uninstall.
> 
> That removes the files from the /usr/* directories. After doing this, you can remove the tiscamera directory from your home directory.
> 
> Stefan

Do we run the `sudo make uninstall` from the build directory? or the tiscamera directory?

**Comment by TIS-Stefan** [comment]
Hello

> Do we run the sudo make uninstall from the build directory? or the tiscamera directory?
From the build directory.

Stefan

**Comment by TIS-Edgar** [comment]
Closed due to inactivity.
