### ISSUE TITLE
gi.repository.GLib.Error: gst_parse_error: no element "Collection" (1)

### ISSUE THREAD

**Issue by vinit13792** [TheImagingSource/tiscamera#453]
While capturing the image via `tcam-capture`, i get the following error:

`(tcam-capture:2889): GStreamer-CRITICAL **: 14:32:53.479: gst_element_make_from_uri: assertion 'gst_uri_is_valid (uri)' failed`
`Traceback (most recent call last):`
`  File "/usr/bin/tcam-capture", line 420, in save_image_action`
`    self.view.save_image(self.settings.get_image_type())`
`  File "/usr/lib/python3/dist-packages/tcam_capture/TcamView.py", line 190, in save_image`
`    self.imagesaver.save_image(get_encoder_dict()[image_type])`
`  File "/usr/lib/python3/dist-packages/tcam_capture/MediaSaver.py", line 246, in save_image`
`    self._create_pipeline()`
`  File "/usr/lib/python3/dist-packages/tcam_capture/MediaSaver.py", line 146, in _create_pipeline`
`    self.pipeline = Gst.parse_launch(save_str)`
`gi.repository.GLib.Error: gst_parse_error: no element "Collection" (1)`

**Comment by TIS-Stefan** [comment]
Double at https://github.com/TheImagingSource/tiscamera/issues/449
