### ISSUE TITLE
DFK33UX273 maximum Software Triggering rate

### ISSUE THREAD

**Issue by cshields-path** [TheImagingSource/tiscamera#454]
Hello TIS! We are currently working with TIS Camera DFK33UX273. According to your documentation, we see the listed maximum FPS for this camera is 238.

With our current implementation, we are having an issue achieving this maximum.

Some of the settings that we believe impact this performance are:

PixelFormat: BayerRG8 (aka 8-bit Bayer raw RGGB)
ExposureTime: 800 us
ImageResolution: 1440x1080 px

In our implementation, we are triggering image captures as fast as possible via Software Trigger. We need to control other hardware in the frame loop so Software Triggering is vital for our application.

With this implementation and settings, we are calculating ~90-95 fps (measured over 250 image captures).

How do we maximize the framerate for our given configuration?

Please let us know if there is any other information that would be helpful.

**Note:** We have been brainstorming a few approaches to improve FPS. They are as follows:
- Free run mode (trigger mode off) and grab latest image
- Develop a way to enable overlapping image acquisition by allowing trigger signal during the sensor readout period
    - Build tiscamera Linux drivers from source with TCAM_ARAVIS_USB_VISION=ON and enable IMX Low Latency Mode with TriggerOverlap=Readout (we are currently leveraging default Video4Linux2 pipeline driver)?

If possible, please let us know the feasibility of these approaches.

**Comment by TIS-Stefan** [comment]
Hello

Which frame rate do you get, if the camera is free running? On a usual Desktop computer with a good USB 3.0 controller and short enough exposure time, you will receive the full frame rate.
Which computer model and brand do you use?
Do you use a callback for image receiving?
The software trigger needs some time on its own, therefore, you can not reach maximum fps with is, but you should be able to have more than 95 fps.
The IMX Low Latency Mode disables overlapping. That reduces the maximum triggere frequency to 1/frame rate. The IMX Low Latency Mode is disabled by default.

Stefan
