### ISSUE TITLE
camera calibrate

### ISSUE THREAD

**Issue by ghost** [TheImagingSource/tiscamera#458]
How can I get camera intr_matrix and intr_coeffs directly? Do I need to calibrate the camera through the chessboard?

**Comment by TIS-Stefan** [comment]
I suppose, you speak about intrinsics and extrinsics,
The camera doe not have such values, because the camera does not know, which lens, focus etc is used. You have to calibrate your  camera/lens/focus/iris combination on yourself. 

Stefan

**Comment by TIS-Edgar** [comment]
Closed due to inactivity.
