### ISSUE TITLE
Camera Interface Does Not Recover From Camera Communication Loss

### ISSUE THREAD

**Issue by MichaelQMSI** [TheImagingSource/tiscamera#460]
Hello, 
We are having a problem where the camera interface app we have built utilizing TIS.Imaging.ICImagingControl34, fails to reconnect to cameras when they are disconnected, restarting the app will fix the issue, but that's not a solution to our problem
the following code throws this error "Base Library Error : An unexpected DShowLibException occured: Error = Failed to start the graph. Due to : The parameter is incorrect.
In file : "FilterGraph.cpp" at line : 263"

Here is the code:
            try
            {
                if (_cameraHandle.DeviceValid)
                {
                    _cameraHandle.LiveDisplayDefault = false;
                    _cameraHandle.LiveDisplayHeight = _cameraBaseheight;
                    _cameraHandle.LiveDisplayWidth = _cameraBaseWidth;

                    _cameraHandle.LiveStart();
                    IsPreviewVisible = Visibility.Visible;
                    ScaleLiveDisplay();
                }

                if (_cameraHandle.LiveVideoRunning)
                {
                    NotifyPropertyChanged("LiveVideoRunning");
                    return true;
                }

                errorString = "Failed to start camera";
                return false;
            }
            catch (Exception ex)
            {
                errorString = $"Failed to start camera w/ exception: {ex.Message}";
             }

**Comment by TIS-Stefan** [comment]
You are in the Linux issues here, the support question is wrong here. Please contact at https://www.theimagingsource.com/support/contact/

If the camera is lost, you must open it again by _cameraHandle.Device = "<insert camera name here>".  That may is the solution for your issue. 

Stefan
