### ISSUE TITLE
Various patches required to package tiscamera-v1 on nixos

### ISSUE THREAD

**Issue by jraygauthier** [TheImagingSource/tiscamera#470]
Hi,

we just packaged and merged latest version of tiscamera into nixpkgs `master` branch (see https://github.com/NixOS/nixpkgs/pull/178139 for the actual PR).

This is nice and seems to work well.

However, in order to package the v1 software, multiple patches were required. See the `*.patch` files under:

https://github.com/jraygauthier/nixpkgs/tree/11af729cd0535c48b22f65edc5112ec1fb04d7c7/pkgs/os-specific/linux/tiscamera

I think a lot of these could be easily applied to your `master` branch and will simplify packaging of further versions of the software.

Thanks in advance.

**Comment by TIS-Edgar** [comment]
Hi,

Sorry for the late reply. The patches seem fine to me. Do you want to create a merge request or would it be ok if i simply committed the changes myself?

**Comment by jraygauthier** [comment]
Hi again, @TIS-Edgar. I will gladly open a merge request. Coming back with it soon.

**Comment by jraygauthier** [comment]
PR #471 applying the patches on top of the master branch ready to be merged.
