### ISSUE TITLE
Wrong download on webpage for tiscamera

### ISSUE THREAD

**Issue by Ukhupacha** [TheImagingSource/tiscamera#477]
The following link https://www.theimagingsource.com/support/downloads-for-linux/install/tiscameraarm64642004 from the webpage doesn't download an **arm64** version, instead it downloads an **amd64** version for ubuntu 20.04

**Comment by TIS-Kevin** [comment]
Dear Ukhupacha,
you are right. Someone made a mistake there. We will fix that soon.

If you need the correct .deb package you can find it also here:
https://github.com/TheImagingSource/tiscamera/releases

Kevin
