### ISSUE TITLE
tcam-capture does not show camera image (probably due to VNC usage)

### ISSUE THREAD

**Issue by oliver** [TheImagingSource/tiscamera#495]
I am using tcam-capture 1.0.0 (installed from package tiscamera_1.0.0.4005_amd64_ubuntu_2004.deb) under Ubuntu 20.04.3, with a DFK 33GX265CS camera. I can select the camera in the GUI; but the main window only shows a menu but no camera image.

I guess this happens because I am running tcam-capture in a VNC server. This PC is a headless system (there is no display attached at all), and the VNC server is started with `/usr/bin/vncserver -SecurityTypes VncAuth -localhost no -geometry 1280x1024 -depth 24 :0`.

In the Info window of tcam-capture I can see that the Gstreamer pipeline uses `video-sink=xvimagesink`; but I suppose that the VNC server does not support Xv.

With tcam-capture 0.14 I was able to edit the Python source and change the output from xvimagesink to ximagesink, which made it work in VNC (this is also described at https://github.com/TheImagingSource/tiscamera/issues/409#issuecomment-836823170). With tcam-capture 1.0.0 this is apparently not possible any more, since the application is not written in Python, correct?

Is there a way to override the output sink used by tcam-capture?

This is the terminal output from tcam-capture:

```
2022-11-09T11:59:23 - unknown:0: info New device: 16020292-aravis
2022-11-09T11:59:23 - unknown:0: info New device: 16020328-aravis
2022-11-09T11:59:23 - unknown:0: info New device: 16020332-aravis
2022-11-09T11:59:23 - unknown:0: info New device: 16020354-aravis
2022-11-09T11:59:29 - unknown:0: info device selected: DFK 33GX265CS-16020292-aravis

2022-11-09T11:59:29 - unknown:0: debug Setting 'conversion-element' property to 'tcamconvert'
2022-11-09T11:59:30 - unknown:0: warning QXcbConnection: XCB error: 3 (BadWindow), sequence: 603, resource id: 6525691, major code: 40 (TranslateCoords), minor code: 0
2022-11-09T11:59:36 - unknown:0: info settings caps to : video/x-bayer, format=(string)rggb, width=(int)2048, height=(int)1536, framerate=(fraction)36/1, binning=(string)1x1, skipping=(string)1x1
2022-11-09T11:59:36 - unknown:0: info Error while retrieving property names: Error: Device not opened

** (tcam-capture:63262): CRITICAL **: 11:59:36.183: tcam_property_enumeration_get_value: assertion 'self != NULL' failed
```

**Comment by TIS-Stefan** [comment]
You are correct. xvimagesink uses graphics board hardware. You may exchange it against ximagesink (without "v").

**Comment by oliver** [comment]
@TIS-Stefan : so how can I change the sink in tcam-capture 1.0.0?

**Comment by TIS-Stefan** [comment]
If the error message is caused while you run tcam-capture please add in the file "~/.config/the_imaging_source/tcam-capture.conf" the line 
`video-sink-element=ximagesink`
Then the ximagesink without hardware acceleration is used. 

I am very sorry for not remembering that earlier and wasting your time. 

Stefan

**Comment by oliver** [comment]
Thanks for your quick help; I wasn't aware of this config file!

With `video-sink-element=ximagesink` the image is not scaled down to the window size; therefore I have instead added this line to the tcam-capture.conf file:
`pipeline="tcambin name=tcam0 ! video/x-raw,format=BGRx ! queue leaky=downstream ! videoconvert n-threads=4 ! videoscale ! fpsdisplaysink video-sink=ximagesink sync=false name=sink text-overlay=false signal-fps-measurements=true"`

The `videoscale` element scales the camera image down so that it fits the window, which is quite useful in my case.

**Comment by oliver** [comment]
This config line is a bit better, since it also preserves the aspect ratio of the camera image:
`pipeline="tcambin name=tcam0 ! video/x-raw,format=BGRx ! queue leaky=downstream ! videoconvert n-threads=4 ! video/x-raw, pixel-aspect-ratio=(fraction)1/1 ! videoscale ! fpsdisplaysink video-sink=ximagesink sync=false name=sink text-overlay=false signal-fps-measurements=true"`

**Comment by TIS-Stefan** [comment]
I did not knew, that a complete pipeline could be specified in the config file.
