### ISSUE TITLE
Documentation: Rename names of systemd services

### ISSUE THREAD

**Issue by tehkillerbee** [TheImagingSource/tiscamera#497]
Hello,

When reading the latest documentation describing the systemd service install (and wondering why I could not find the gige-daemon service anymore), I noticed that it has been renamed and the documentation must be updated accordingly.
[link](https://www.theimagingsource.com/documentation/tiscamera/systemd.html?highlight=systemd)

The documentation below has been updated already:
[link](https://www.theimagingsource.com/documentation/tiscamera/tcam-gige-daemon.html?highlight=systemd)

It also looks like the systemd service will not be installed, unless the flag TCAM_ENABLE_DATA_INSTALL is set, correct?

**Comment by TIS-Edgar** [comment]
Hello there,

Thank you for the bug report! Fixed in 765b1ad3e265e0d8a2d70ead2b1c90d03b982ce7 on the development branch.

> It also looks like the systemd service will not be installed, unless the flag TCAM_ENABLE_DATA_INSTALL is set, correct?

That is correct.
