### ISSUE TITLE
Using multiple cameras on linux

### ISSUE THREAD

**Issue by dinhtuanan** [TheImagingSource/tiscamera#499]
Hi,
I have 2 cameras: 

- DFK 33GX265    Serial: 31120204 aravis
- DFK 33GX264e  Serial: 39220008 aravis

I'm using Ubuntu 18.04.6 LTS

I plugged both of them through Ethernet Adapter Usb 3.0

Camera Info:

- ![image](https://user-images.githubusercontent.com/108641003/205008193-78ddfc67-ff87-4e47-ab22-c3fc0fe43b2b.png)
- I dont know why the second camera have no persistent IP, subnet, gateway
- ![image](https://user-images.githubusercontent.com/108641003/205005703-053c23ba-b312-4c9f-aa67-4eb78939448f.png)

When I use tcam-capture application to open camera, I can only open 1 camera that plugged first and the other I can't open

- ![image](https://user-images.githubusercontent.com/108641003/205006684-821600ee-2822-4692-ba55-739a0f84ac41.png)

I would like to know how I can use two cameras or how to setting cameras right way

Did I miss something in config cameras?

Regards,
An

**Comment by TIS-Stefan** [comment]
Hello

you may try to open the second camera with command
tcam-capture --reset.

Maybe that helps.

Stefan

**Comment by dinhtuanan** [comment]
Hi Stefan, thank you so much for replying

I tried your suggestion but nothing happen. Did I do right?
![image](https://user-images.githubusercontent.com/108641003/205012240-525b90ef-4779-42fb-87e8-661419bae6c2.png)

**Comment by TIS-Stefan** [comment]
Hello

you are right, that option was available in the precious version. But according to the documentation at https://www.theimagingsource.com/documentation/tiscamera/tcam-capture.html you can open the camera directly by serial:
tcam-capture --serial 31120204
and
tcam-capture --serial 39220008

I suppose, you can see the live stream of each of the cameras, if they are opened as only camera, right?

Stefan

**Comment by TIS-Stefan** [comment]
Hello 

Just one addtion: You use a PI4, so please make sure to use low frame rates:
- avoid GigE Bandwidth exhaustion
- do not overwhelm the weak PI4 CPU
Stefan

**Comment by dinhtuanan** [comment]
Thank you so much Stefan,

I will close this issue

Regards,
An
