### ISSUE TITLE
Firmware Update Necessary for DFK 23UM021?

### ISSUE THREAD

**Issue by koichiHik** [TheImagingSource/tiscamera#50]
Hello,

I am now trying to create stereo camera with two DFK 23UM021 with Ubuntu15.04.
For synchronizing purposes, I need to use software trigger functionality.
However, it seems that trigger functions are not available with my cams.
With "sudo uvcdynctrl -i usb3.xml -d /dev/video0", I got the following messages.

--------------------------------
[libwebcam] Unknown V4L2 control ID encountered: 0x0199E201
[libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0199E201, name = 'Exposure Time (us)'
[libwebcam] Unknown V4L2 control ID encountered: 0x0199E204
[libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0199E204, name = 'Gain (dB/100)'
[libwebcam] Unknown V4L2 control ID encountered: 0x0199E218
[libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0199E218, name = 'ROI Offset X'
[libwebcam] Unknown V4L2 control ID encountered: 0x0199E219
[libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0199E219, name = 'ROI Offset Y'
[libwebcam] Unknown V4L2 control ID encountered: 0x0199E220
[libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0199E220, name = 'ROI Auto Center'
[libwebcam] Unknown V4L2 control ID encountered: 0x0199E201
[libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0199E201, name = 'Exposure Time (us)'
[libwebcam] Unknown V4L2 control ID encountered: 0x0199E204
[libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0199E204, name = 'Gain (dB/100)'
[libwebcam] Unknown V4L2 control ID encountered: 0x0199E218
[libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0199E218, name = 'ROI Offset X'
[libwebcam] Unknown V4L2 control ID encountered: 0x0199E219
[libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0199E219, name = 'ROI Offset Y'
[libwebcam] Unknown V4L2 control ID encountered: 0x0199E220
[libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0199E220, name = 'ROI Auto Center'
Importing dynamic controls from file usb3.xml.
usb3.xml: error: video0: unable to map 'Exposure Time (us)' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 17: File exists)
usb3.xml: error: video0: unable to map 'Auto Shutter' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Auto Exposure Reference' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Gain (dB/100)' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 17: File exists)
usb3.xml: error: video0: unable to map 'Gain Auto' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Whitebalance One Push' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Whitebalance Preset' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Trigger Mode' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Trigger Polarity' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Trigger Global Reset Release' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Software Trigger' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Trigger Delay' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Strobe Enable' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Strobe Polarity' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Strobe Exposure' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Strobe Duration' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Strobe Delay' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'GPOUT' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'GPIN' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'ROI Offset X' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 17: File exists)
usb3.xml: error: video0: unable to map 'ROI Offset Y' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 17: File exists)
usb3.xml: error: video0: unable to map 'ROI Auto Center' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 17: File exists)
usb3.xml: error: video0: unable to map 'Auto Focus One Push' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Auto Focus ROI Enable' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Auto Focus ROI Left' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Auto Focus ROI Top' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'ATR Enable' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'ATR Gain' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'ATR Enable Wide D' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'ATR Contrast' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'ATR Contrast Auto' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'ATR Chroma' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Image Stabilization' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Noise Reduction' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Face Detection' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Flip Horizontal' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
usb3.xml: error: video0: unable to map 'Flip Vertical' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)

--------------------------------

I got the following information with firmware-update -i 

--------------------------------

Device manufacturer: The Imaging Source Europe GmbH
Product name:        DFK 23UM021
Serial number:       41510122
VendorID:ProductID:  199e:8455
Firmware version:    439

Device manufacturer: The Imaging Source Europe GmbH
Product name:        DFK 23UM021
Serial number:       41510125
VendorID:ProductID:  199e:8455
Firmware version:    439

--------------------------------

Do I need to update firmware? Your answer will be very appreciated!
Thank you in advance.
Koichi

**Comment by TIS-Stefan** [comment]
Hello Koichi

the DFK 23UM021 has no trigger at all. Therefore, there is no trigger property. The camera will not have a trigger in the near future.

Stefan
