### ISSUE TITLE
Hardware Triggering Questions

### ISSUE THREAD

**Issue by chutsu** [TheImagingSource/tiscamera#501]
Hi,

I am in the process of figuring out how to hardware trigger the camera **DFM 22BUC03-ML**. I have read the technical documentation [here](https://s1-dl.theimagingsource.com/api/2.5/packages/documentation/manuals-trm/trmdfm22buc03ml/ed4b49ac-9603-5b09-8469-6c5b1780748e/trmdfm22buc03ml.en_US.pdf), which tells me there's a `TRIGGER_IN` pin I can send a pulse to trigger image capture. The pulse can be generated from any thing e.g. Arduino digital pin.

In the software, one can set the GStreamer property "Trigger Mode" to enable hardware triggering [[source](https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/tree/master/python/Using%20external%20trigger%20and%20callback#trigger-mode)].

However, I have the following remaining questions:

- Is it triggered on the rising edge or lower?
- What is the minimum pulse width or are there no width requirements?

Many thanks
Chris

**Comment by ShadeTechnik** [comment]
I set my system up a very long time ago but the cameras are triggered via a CNC controller. I just checked the settings and it says "triggerwidth = 0.010" Which if memory serves is in ms so 10us? That's not even to say that's the shortest pulse width, I just have no reason to run it faster. That is a 24v sinking output to the camera and I'm guessing it's on the rising edge.
