### ISSUE TITLE
Camera getting disconnected after run gstreamer pipeline code

### ISSUE THREAD

**Issue by KushalBiyani** [TheImagingSource/tiscamera#514]
**Issue**
We have created a docker image with Ubuntu 18.04 with the commands specified in the [Building tiscamera](https://github.com/TheImagingSource/tiscamera#:~:text=dependency%2Dmanager%20install-,Building%20tiscamera,-The%20following%20commands)  on GitHub.
We were able to list down the camera using **tcam-ctrl -l** command.

<img width="221" alt="image" src="https://user-images.githubusercontent.com/59797945/224737867-cced8542-b2c2-4d74-bee5-a241f4ea59ec.png">

When we are starting the pipeline using below command : 
**gst-launch-1.0 tcambin ! videoconvert ! ximagesink**

we are getting the below error : 

![image](https://user-images.githubusercontent.com/59797945/224738850-953d9701-4c99-4d37-93c6-e9f61fb72ce4.png)

And while running this [code](https://www.theimagingsource.com/en-us/documentation/tiscamera/tutorial.html#receiving-images) our camera is getting disconnected every time and we are not able to receive any frames and not able to list down the camera also.

**Comment by TIS-Edgar** [comment]
Hi,

Could you set the following environment variable:

```
export GST_DEBUG=ximagesink:5,tcam-libtcam:5
```

This will enable debug output for our backend and the ximagesink.

Does tcam-capture work?
Does the xvimagesink work?
Does tiscamera work outside of the docker container?

The disconnects should also be logged in the debug output.
Did you adjust the MTU to 9000?

**Comment by KushalBiyani** [comment]
**Tiscamera is running outside the docker container**. We are using docker desktop on windows machine form where we are able to receive the feeds on IC capture software.

While running the **tcam-ctrl -l** command we are getting this output: 

<img width="732" alt="image" src="https://user-images.githubusercontent.com/59797945/225295483-f1b7c57d-fd13-44a5-8289-2baf3bc0556f.png">

On running **gst-launch-1.0 tcambin ! videoconvert ! ximagesink** we were getting this output: 

<img width="736" alt="image" src="https://user-images.githubusercontent.com/59797945/225295757-6777978d-d018-4d8e-a7c7-4bc5767405fe.png">

On running **gst-launch-1.0 tcambin ! videoconvert ! xvimagesink** we were getting this output: 

<img width="731" alt="image" src="https://user-images.githubusercontent.com/59797945/225295998-a98129de-6a6a-40cd-8625-92ab7a9fa9a9.png">

On running **tcam-capture** we were getting this output: 

<img width="575" alt="image" src="https://user-images.githubusercontent.com/59797945/225296299-82747b5a-ea4a-4734-acaf-c77668418c24.png">

On running the code from the [app-sink.py](https://github.com/TheImagingSource/tiscamera/blob/master/examples/python/07-appsink.py) file in Github example we get this error and camera also got disconnected : 

<img width="739" alt="image" src="https://user-images.githubusercontent.com/59797945/225297577-2956c9cd-886c-44a5-bf05-0eef74c17946.png">

**Comment by TIS-Edgar** [comment]
We are trying to find the cause of this issue.
Docker on Windows makes things more "interesting" than needed.

Can you set the following environment variable
```export ARV_DEBUG=all:3```

and capture the output of wireshark for us?
You should have your native interface available and a WSL interface.
Output of both would be of interest at this point.

Please disable host camera services before doing this.

You can send the capture to support@theimagingsource.com referencing this issue so that potential confidential data will be handled as such.

**Comment by TIS-Edgar** [comment]
Closed due to inactivity.
