### ISSUE TITLE
DMM 36AX290-ML Not Detected on RPi4 with TIS Demo OS Image

### ISSUE THREAD

**Issue by palacidr** [TheImagingSource/tiscamera#516]
I have the following hardware:

RPi 4 Model B

Camera DMM 36AX290-ML

Attached is image of my connection to the RPI4. I have confirmed the cable works by verifying it with a RPi camera module.
![image](https://user-images.githubusercontent.com/128733457/228020406-bdfb8ac4-7530-45c1-a0e1-f2ef0962f547.png)

I have installed the latest Demo image from Imaging Source from https://www.theimagingsource.com/en-us/support/download/imagetispimipi-1.0.0/

The camera does not show up as recognized by the TCam-Capture software
![image](https://user-images.githubusercontent.com/128733457/228021263-5dfff56f-eafa-4f99-bc37-3ee78a84a302.png)

I download and attempt to install the latest versions of tcamdutils and tcampimipisrc but there are dependency issues.
![image](https://user-images.githubusercontent.com/128733457/228021551-37e2966a-8b96-4166-a485-c381b17a3c19.png)

Any help with this would be greatly appreciated. Ideally, I would like to be able to get the software installed on a RPi 3 running the latest version of Raspbian OS (Bullseye 11) with the same camera DMM 36AX290-ML, but I should at least get it to work on the RPi4 first.

**Comment by TIS-Stefan** [comment]
Hello

please see https://github.com/TheImagingSource/tiscamera/issues/484#issuecomment-1485564045

Stefan
