### ISSUE TITLE
Reading Whitebalance values after One-Push Whitebalance

### ISSUE THREAD

**Issue by elRadish** [TheImagingSource/tiscamera#517]
I'm still on TisCamera 0.14, Linux 18.04 on Jetson Nano.

I’m trying to do a one-push Whitebalance and read back the White Balance values for red, green and blue to save them permanently.

But I can’t figure out how to do this. 
In IC Capture on Windows, the current values are displayed in the device properties, but when I read them back with `Tis.Get_Property("Whitebalance Blue").value`, it doesn’t change, only, when I set it manually.

Is this possible with TisCamera 0.14?

**Comment by TIS-Stefan** [comment]
Hello

Are you sure, you mean one push auto-focus, not one push Whitebalance?

Stefan

**Comment by elRadish** [comment]
Oops, no, of course one-push-whitebalance. Thanks!

**Comment by TIS-Stefan** [comment]
If you run the white balance one push in your Linux software, does the live video change to white balanced images?

(I ask so many questions, because we ended the support for tiscamera 0.14, since we use 1.1 by now.)

Stefan

**Comment by elRadish** [comment]
Yes, it does, but the Properties keep the same. 
The same happens in tcam-capture - it doesn't update the manual values which would be pretty useful:
My guess is that the values are read from the image metadata instead of the camera properties?

I'll try to migrate to 1.1 asap!

**Comment by TIS-Edgar** [comment]
Closed due to inactivity.
