### ISSUE TITLE
Unable to convert between caps formats [GRAY12p, 1920x1080, 8192/225]

### ISSUE THREAD

**Issue by Niv-R** [TheImagingSource/tiscamera#518]
**Describe the bug**
Using camera: **TIS_DMK_39GX265_Z20_TI**
I am trying to upgrade from tiscamera 0.14.0 to 1.1.0.
My code looks like this:
`pipeline: Gst.Pipeline = Gst.parse_launch("tcambin serial=... name=source ! video/x-raw,format=GRAY12p,width=1920,height=1080,framerate=8192/225 ! valve name=valve ! appsink name=sink")
state = pipeline.set_state(Gst.State.READY)
`
the returned state appears to be `Gst.StateChangeReturn.FAILURE`

using `Gst.debug_set_default_threshold(Gst.DebugLevel.WARNING)` I see:

`0:01:12.917753128   346 0x7f64a8057980 WARN             tcamconvert tcamconvert.cpp:214:gst_tcamconvert_transform_caps:<tcambin-converter> error: Unable to convert between caps formats
0:01:12.932470709   346 0x7f64a8057980 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<source:src> could not send sticky events`

Using `tcam-ctrl -c` I can see the caps I use, but using the function `print_formats` from `examples/python/04-list-formats.py` did not show GRAY12p at all.

**computer used (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture/Platform: amd64 Desktop
 - Camera  TIS_DMK_39GX265_Z20_TI
 - tiscamera version
 	Tcam:	1.1.0_master/70abad2a_rev_4139
	Aravis:	0.8_version_e977fa4
	Modules:	gst_aravis_arvu3v_v4l2_libusb_tools_doc_tests

**Comment by TIS-Stefan** [comment]
The failure is returned, because the valve prevents the start. The appsink does not get an image and therefore does not configure itself (or something like that.) I detected this behaviour, when I changed from Gstreamer 0.10 to version 1.0.

I found no workaround. 

Stefan

**Comment by Niv-R** [comment]
I removed the valve from the pipeline and the error still persists:

pipeline is now: `tcambin serial=... name=source ! video/x-raw,format=GRAY12p,width=1920,height=1080,framerate=8192/225 ! appsink name=sink
`
then setting state to READY works
but setting state to PLAYING afterwards fails:

`tcamconvert tcamconvert.cpp:214:gst_tcamconvert_transform_caps:<tcambin-converter> error: Unable to convert between caps formats
GST_PADS gstpad.c:4231:gst_pad_peer_query:<source:src> could not send sticky events
basesrc gstbasesrc.c:3072:gst_base_src_loop:<source> error: Internal data stream error
basesrc gstbasesrc.c:3072:gst_base_src_loop:<source> error: streaming stopped, reason not-negotiated (-4)
`

**Comment by TIS-Stefan** [comment]
Ouch, I am sorry. tcambin does not like GRAY12p. tcamsrc does like it. 

tcambin serial=... name=source ! video/x-raw,format=BGRx

or with tcamdutils
tcambin serial=... name=source ! video/x-raw,format=RGBx64

Stefan

**Comment by Niv-R** [comment]
changing `tcambin serial=... ! video/x-raw,format=GRAY12p` to `tcamsrc serial=... ! video/x-raw,format=GRAY12p` solved this issue for me
