### ISSUE TITLE
Connect Video-to-USB converter

### ISSUE THREAD

**Issue by lz89** [TheImagingSource/tiscamera#52]
I have a converter as shown here:
http://www.theimagingsource.com/en_US/products/converters/dfgusb2pro/

I wonder how can I use the tiscamera library to recognise the converter?
I have followed the tutorial where sudo ./euvccam-fw -p gave me: 
Device not found

I cannot find any device under /dev/video*

System: Ubuntu 14.04

Thanks very much.

**Comment by TIS-Edgar** [comment]
Hi,

Our converter are currently not Linux compatible.
There is currently no timetable as when (or even if) they will be made Linux compatible.

Best Regards,

Edgar
