### ISSUE TITLE
Unable to open a DMM 22BUC03-MLA camera

### ISSUE THREAD

**Issue by ismaelbenito-ub** [TheImagingSource/tiscamera#520]
**Describe the bug**

We're getting this error when connecting a DMM 22BUC03-MLA camera to a Linux system (Debian and Ubuntu): 

```
2023-05-24T09:48:21 - unknown:0: warning libpng warning: iCCP: known incorrect sRGB profile
```

**To Reproduce**
1. Connect a DMM 22BUC03-MLA camera to PC with a Linux Debian based distribution with the latest `tcam-capture` utility. 
2. Check if the camera is there and retrieve the serial number using `dmesg --follow`: 

```bash
[  658.256219] usb 2-2: new high-speed USB device number 10 using xhci_hcd
[  658.617682] usb 2-2: New USB device found, idVendor=199e, idProduct=8202, bcdDevice= 8.13
[  658.617686] usb 2-2: New USB device strings: Mfr=2, Product=1, SerialNumber=3
[  658.617688] usb 2-2: Product: DMM 22BUC03-MLA
[  658.617689] usb 2-2: Manufacturer: The Imaging Source Europe GmbH
[  658.617690] usb 2-2: SerialNumber: 47020928
```
3. Use the serial number to force `tcam-capture` to use that camera, otherwise the error is mutted by the GUI and the camera does not appear: 

```
$ tcam-capture --serial 47020928
```

4. Obtain the error:

```
2023-05-24T09:48:21 - unknown:0: warning libpng warning: iCCP: known incorrect sRGB profile
```

**Expected behavior**
The camera opens in `tcam-capture` and subsequently in our Python-based front-end. 

**Screenshots**

**computer used (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Architecture/Platform: amd64, Desktop, 
 - Camera model you use: DMM 22BUC03-MLA
 - libpng version: libpng16-16/stable,now 1.6.37-3 amd64
 - tiscamera version (tcam-ctrl --version, if possible):

```bash
Versions: 
	Tcam:	1.1.0_master/70abad2a_rev_4139
	Aravis:	0.8_version_e977fa4
	Modules:	gst_aravis_arvu3v_v4l2_libusb_tools_doc_tests
```

**Additional context**

If your bug report has potentially sensitive information, please write us directly at support@theimagingsource.com .

**Comment by ismaelbenito-ub** [comment]
Update: the camera works with no problem on Windows with the IC Capture software, and seems to be communicating at USB level with the computer as shown in the `dmesg` log. Here is suggested that apps running libpng should not treat warnings as errors: https://community.magento.com/t5/Magento-2-x-Technical-Issues/libpng-warning-iCCP-known-incorrect-sRGB-profile/td-p/127379

Cheers,

**Comment by TIS-Stefan** [comment]
Hello

That is the typical issue. For UVC/v4l2 compatibility the camera needs a firmware update.
The update program and the firmwares are at https://github.com/TheImagingSource/tcam-firmware-update . The firmware file to be written into the camera is [dmk22uc03_3017.euvc](https://github.com/TheImagingSource/tcam-firmware-update/blob/master/firmware/usb2/dmk22uc03_3017.euvc)

Stefan

**Comment by ismaelbenito-ub** [comment]
That fixed the problem! Thank you :)

**Comment by ismaelbenito-ub** [comment]
We have a similar issue for two DMM 22BUC03-ML cameras, but they do not show in the `dmesg --follow` log as the other camera, and when trying to write the same firmware, we obtain this error: 

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to attain device handle.
[1]    26297 abort      ./tcam-firmware-update -ud 07220032 -f ../../firmware/usb2/dmk22uc03_3017.euv
```

And then if we run once again the firmware update we obtain: 

```
Unable to find device with serial "07220032"
```

Are those errors related, or do we open another issue? Cheers,

**Comment by TIS-Stefan** [comment]
If the camera does not show up in dmesg log, then it is not found at all. This means, it may is broken. I suppose, you exchanged the cables already for a test, right? If yes, then you may create an RMA case for checking, so you go in contact with me at https://www.theimagingsource.com/en-us/company/contact/

**Comment by TIS-Stefan** [comment]
Hello

In /usr/src/linux-headers-5.15.0-56/include/uapi/asm-generic/errno.h I found
```C
#define	ETIMEDOUT	110	/* Connection timed out */    
````
so I think, the camera is somehow gone. I suggest to contact your camera dealer for sending the camera in for repair.
I see, there are two devices connected. What happens, if only one device is connected?

Stefan

**Comment by ismaelbenito-ub** [comment]
The message appears when only one camera is connected. Why it appears as two devices is unknown to me, if I understand correctly, first the 71 error appears, later the 110, but it is the same device. Error 71 is: 

```
#define	EPROTO		71	/* Protocol error */
```

Today I'm in remote, but on Monday I can check again the logs. But as you were saying, it seems it will be related with some problem on the board themselves, we are in touch with our Spanish dealer. 

Cheers, 
Ismael

**Comment by TIS-Stefan** [comment]
Hi Ismael
The protocol error can be ignored and as far as I can see, it is from another camera. At least den device number is different.
Stefan

**Comment by TIS-Stefan** [comment]
Hello Ismael
I am a little but confused. If the cameras are connected alone, then they work. Correct?
Stefan

**Comment by ismaelbenito-ub** [comment]
Hi Stefan,

no they do not. If I plug one single camera to the computer, the `dmesg` log shows after I plug the camera: 

```bash 
[  116.279095] usb 2-1: new full-speed USB device number 9 using xhci_hcd
[  116.407112] usb 2-1: device descriptor read/64, error -71
[  116.643147] usb 2-1: device descriptor read/64, error -71
[  116.879143] usb 2-1: new full-speed USB device number 10 using xhci_hcd
[  117.007151] usb 2-1: device descriptor read/64, error -71
[  117.243187] usb 2-1: device descriptor read/64, error -71
[  117.351331] usb usb2-port1: attempt power cycle
[  117.763214] usb 2-1: new full-speed USB device number 11 using xhci_hcd
[  117.763450] usb 2-1: Device not responding to setup address.
[  117.971444] usb 2-1: Device not responding to setup address.
[  118.179211] usb 2-1: device not accepting address 11, error -71
[  118.307227] usb 2-1: new full-speed USB device number 12 using xhci_hcd
[  118.307441] usb 2-1: Device not responding to setup address.
[  118.515500] usb 2-1: Device not responding to setup address.
[  118.723275] usb 2-1: device not accepting address 12, error -71
[  118.723344] usb usb2-port1: unable to enumerate USB device
```

**Comment by TIS-Stefan** [comment]
Hello Ismael

I think, the camera in question is broken. So please go in contact with your camera dealer for a repair. 
I am sorry for not having a better answer.

Stefan

**Comment by ismaelbenito-ub** [comment]
Hi Stefan, 

thanks for your help! I will close the issue as the original MLA camera is working, we happen to have this other problem with two ML models. 

Cheers,

Ismael

**Comment by TIS-Stefan** [comment]
Hell Ismael
It is unlikely, that two of this cameras from one batch do not work. Also they have been checked before they were sent out. Thus I suppose, something went wrong during firmware update. E.g. A bad USB connection can interrupt the firmware update, which makes the camera unusable. 
Stefan

**Comment by ismaelbenito-ub** [comment]
In neither of them have we attempted a firmware update, one of them was opened by me last week, and did not work. It is also strange for us that they do not work out-of-the-box, firmware updates aside. We also have another sealed camera of the same batch. We are arranging on how to proceed with the dealer (Iberoptics) on the matter. 

Cheers,
Ismael

**Comment by TIS-Stefan** [comment]
Hello Ismael

I am a little bit concerned. However, say Hello from me to Iberoptics.

Stefan
