### ISSUE TITLE
Cmake cannot find tcam

### ISSUE THREAD

**Issue by bartonp2** [TheImagingSource/tiscamera#540]
I am trying to follow the examples for using tiscamera with C++ but CMake is having issues finding tcam. In the example, the CMakeLists.txt contains the following code to find tcam: 

``` 
pkg_check_modules(TCAM tcam)
if( TCAM_FOUND)
    message(STATUS "TCAM INC : " ${TCAM_INCLUDE_DIRS})
    message(STATUS "TCAM LIB : " ${TCAM_LIBRARIES}) 
else()
    message(FATAL_ERROR "TCAM package missing.")
endif( TCAM_FOUND)
```

When compiling, I however get the error:

```
CMake Error at CMakeLists.txt:19 (message):
  TCAM package missing.
```

I have successfully installed tiscamera and tcamdutils from the built packages for ubuntu22 on x64. If I run `tcam-ctrl --packages` I get the following output:

```
tcam-ctrl --packages
tiscamera: 1.1.0.4139
tiscamera-tcamproperty: Provided by tiscamera
tcamdutils: 1.0.0.560
tcampimipisrc is not installed.
tcamtegrasrc is not installed.
tcamdutils-cuda is not installed.
theimagingsource-drivers is not installed.
ic_barcode is not installed.
```

While all the listed tools as well as tcam-capture and the python libraries are working, Cmake seems to have an issue finding it. Am I missing something or doing something wrong?

**Comment by TIS-Stefan** [comment]
Hello,

The deb packages do not contain the development files. You must download the tiscamera development package from https://www.theimagingsource.com/en-us/support/download/tiscameratiscameradev-1.1.0.4139/. The downloaded tiscameradev_1.1.0.4139.zip file contains four files. I guess, you run a desktop computer (AMD64), so you install the file "tiscamera-dev_1.1.0.4139_amd64_ubuntu_1804.deb". The 18.04 is used for the 22.04 too. 

Stefan
