### ISSUE TITLE
unable to detect camera on ubuntu

### ISSUE THREAD

**Issue by DigitalRowlet** [TheImagingSource/tiscamera#546]
HI!
After installing the precompiled packages of tiscamera, I attempted to launch the tcam-capture program, only to find a blank window when selecting a device. By the way, I can use the camera normally on the Windows system of the same device. I tried some commands in the terminal with the following results:
```
cam-ctrl --version
Versions: 
    Tcam:    1.1.1_master/ee45fcf7_rev_4142
    Aravis:    0.8_version_e977fa4
    Modules:    gst_aravis_arvu3v_v4l2_libusb_tools_doc_tests

tcam-gigetool list
No cameras found.

gst-launch-1.0 tcambin ! videoconvert ! ximagesink
WARNING: erroneous pipeline: no element "tcambin"

gst-inspect-1-0 tcambin
gst-inspect-1-0: command not found
```
Could you kindly provide assistance regarding this issue? Thank you in advance for your help.

**computer used (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Architecture/Platform: amd64
 - Camera : 33GX264

**Comment by TIS-Stefan** [comment]
Hello

Did you configure the camera' and network controller's IP addresses correctly? Please have a look at 
https://wiki.theimagingsource.com/index.php/Configure_GigE_Camera_IP_Addresses_in_Linux
and
https://wiki.theimagingsource.com/index.php/Gige_Camera_is_not_available

Stefan

**Comment by DigitalRowlet** [comment]
Thank you for your response, but it seems that it didn't work. I tried the commands from the wiki:
```
sudo sysctl -w net.ipv4.conf.enp2s0.rpfilters=0
sudo sysctl -w net.ipv4.conf.enp7s1.rpfilters=0
sysctl: cannot stat /proc/sys/net/ipv4/conf/enp2s0/rpfilters: No such file or directory
```
Then I attempted to modify the '/etc/sysctl.conf' file:
```
(base) wk@wk-HP-ZBook-Fury-17-3-inch-G8-Mobile-Workstation-PC:~$ ifconfig
enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 5c:60:ba:b8:08:e6  txqueuelen 1000  (以太网)
        RX packets 6  bytes 1062 (1.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 190  bytes 34997 (34.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0x6ed80000-6eda0000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (本地环回)
        RX packets 93281  bytes 32870119 (32.8 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 93281  bytes 32870119 (32.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp0s20f3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.37.136.105  netmask 255.255.0.0  broadcast 10.37.255.255
        inet6 fe80::a608:429c:a68f:e183  prefixlen 64  scopeid 0x20<link>
        ether a0:59:50:9b:ab:5e  txqueuelen 1000  (以太网)
        RX packets 14197  bytes 12281478 (12.2 MB)
        RX errors 0  dropped 12  overruns 0  frame 0
        TX packets 13500  bytes 5425438 (5.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

(base) wk@wk-HP-ZBook-Fury-17-3-inch-G8-Mobile-Workstation-PC:~$ sudo nano /etc/sysctl.conf
(base) wk@wk-HP-ZBook-Fury-17-3-inch-G8-Mobile-Workstation-PC:~$ sudo sysctl -p
net.ipv4.conf.enp0s31f6.rp_filter = 0
(base) wk@wk-HP-ZBook-Fury-17-3-inch-G8-Mobile-Workstation-PC:~$ tcam-gigetool list

No cameras found.
```
However, even after these steps, the camera still couldn't be detected. Did I miss something?

**Comment by TIS-Stefan** [comment]
Hello

"enp2s0" and "enp7s1" are names of network connections. These are samples, as they are on your computer. Your ifconfig output shows, your networks have different names: "enp0s31f6" and "wlp0s20f3". I would guess, the camera is connected to "enp0s31f6", but this controller uses an IV v6 not v4 address. 

Is the camera powered? Do your use 
 * an external power supply or
 * a 1GB PoE Injector or
 * a 1GBs ethernet switch ?
Do the LEDs light on the camera's RJ45 jack, as mentioned in the linked knowledbase?

Stefan

**Comment by DigitalRowlet** [comment]
The camera is indeed connected to "enp0s31f6", and I've already modified its properties as follows:
```
(base) wk@wk-HP-ZBook-Fury-17-3-inch-G8-Mobile-Workstation-PC:~$ sysctl net.ipv4.conf.enp0s31f6.rp_filter
net.ipv4.conf.enp0s31f6.rp_filter = 0
```
Regarding the connection setup, the camera is connected directly to the Ethernet port of my laptop. Both LEDs on the camera's RJ45 jack and on the laptop are lit correctly. Furthermore, when I switch the laptop's operating system to Windows, the camera works perfectly fine.

Could you please advise on the specific steps I should take next?

**Comment by TIS-Stefan** [comment]
Hello

"enp0s31f6" must support IPv4 protocol. Your ipconfig output says, it has IP v6 only. Thus, please change or add this configuration on your Linux.
