### ISSUE TITLE
AttributeError: 'GstTcamBin' object has no attribute 'get_device_serials_backend' while running the 00-list-devices.py

### ISSUE THREAD

**Issue by zarathacia** [TheImagingSource/tiscamera#547]
when running the 00-list-devices.py file i get this error:

Traceback (most recent call last):
  File "path/tiscamera/examples/python/00-list-devices.py", line 79, in <module>
    list_devices()
  File "path/tiscamera/examples/python/00-list-devices.py", line 43, in list_devices
    serials = source.get_device_serials_backend()
AttributeError: 'GstTcamBin' object has no attribute 'get_device_serials_backend'

When running the command gst-launch-1.0 tcambin ! videoconvert ! ximagesink
it works perfectly by adding this command export TCAM_DISABLE_DEVICE_BLACKLIST=1 

 - OS: Ubuntu 20.04
 - Architecture/Platform: amd64
 - Camera  model: DFK 23UX174
 - tiscamera version: Tcam:	1.1.0_master/70abad2a_rev_4139

I am trying to build a ROS node based on the sample code found in the repo but they don't work.

**Comment by TIS-Stefan** [comment]
Hello
The environment  TCAM_DISABLE_DEVICE_BLACKLIST=1 variable must be set in all sessions you have. I you set it only once in the terminal, is is not set in another. 

I am sure, there is a ways to set this variable once for your user account, but I am not sure, how to do that (it is Linux OS thing.)

Stefan

**Comment by zarathacia** [comment]
Hi, 
yeah it doesn't really relate to my problem is with the error that comes when i run the example files. i get the traceback above.

**Comment by TIS-Stefan** [comment]
Hello
I just saw, you use version 1.1.0, but we are on version 1.1.1 already. Therefore, can you please update and try again?

Stefan

**Comment by TIS-Stefan** [comment]
Hello

did you do the  "export TCAM_DISABLE_DEVICE_BLACKLIST=1" set before running the sample? What does tcam-ctrl -l says? (It does the same as the Python script.

Stefan

**Comment by zarathacia** [comment]
Hi it worked. thanks for your assistance.
