### ISSUE TITLE
No v4l2 firmware support for DFK 61BUC02 Cameras

### ISSUE THREAD

**Issue by zarathustr** [TheImagingSource/tiscamera#556]
Hi Officer,

It seems that the repo does not contain a valid v4l2 firmware for DFK 61BUC02 camera, with CMOS sensor. I really would like to request the firmware if available.

Thanks,
Jin Wu

**Comment by TIS-Stefan** [comment]
Hello Jin Wu

I am very sorry, but this camera model was never intended to be used in Linux. Also we do not produce this model anymore.
Therefore: You can not use this model in Linux.

Stefan
