### ISSUE TITLE
Raspberry pi 3b+ not able to detect the camera 

### ISSUE THREAD

**Issue by yatinarora01** [TheImagingSource/tiscamera#559]
I am not able to see my camera in interface options raspi-config. But I am able to run the command libcamera-hello

the camera I’m using is
https://amzn.in/d/3tNvb3n

Raspberry pi model 3b+

**Comment by TIS-Stefan** [comment]
Please ask the manufacturer of your camera for an SDK. It is not a The Imaging Source camera.
