### ISSUE TITLE
USB 2.0 DFK 22 BUC03 driver not working

### ISSUE THREAD

**Issue by gauravbaluni** [TheImagingSource/tiscamera#60]
I am using DFK 22 BUC03 camera of Imaging Source. It works fine on windows. I tried installing on ubuntu precise 12.04 as per the procedure mentioned. Everything worked fine upto the installation of euvccam-fw.
While uploading the relevant file either usb2/dmk22uc03_135.euvc or usb2/dfk22uc03_135.euvc it says firmware version not matching. I tried using -f to force upload the firmware. It went fine but after that there is still no device video0 in /dev. Can anyone help me out?

**Comment by TIS-Stefan** [comment]
The software is right here. The UVC compatible firmware is the file "dmk22uc03_163_uvc.euvc". The file "dfk22uc03_135.euvc" contains the Windows firmware.
