### ISSUE TITLE
Empty CGigECamera class in showcamera example

### ISSUE THREAD

**Issue by cguindel** [TheImagingSource/tiscamera#62]
Hello,

Are there any plans to implement the methods of the class 'CGigECamera' in the 'showcamera' example? I noticed it is just a skeleton when I was about to use it...

Thank you.

**Comment by TIS-Stefan** [comment]
Well.... the plan is there, but the time....

**Comment by TIS-Stefan** [comment]
Still not implemented the GigE cameras. However, we released Gstreamer 1.0 support with tcamsrc and tcambin modules, that encapsulate USB and GigE cameras. They support both of them, and both are handled with same source code.
