### ISSUE TITLE
enabling external trigger I/O

### ISSUE THREAD

**Issue by nonrevlb** [TheImagingSource/tiscamera#69]
I'm using the DMM 22BUC03-ML camera which has external trigger i/o  pins. Following the instructions here:

http://s1.dl.theimagingsource.com/api/2.0/packages/publications/whitepapers-cameras/wp224272trigo/948b91a44c/wp224272trigo_1.5.en_US.pdf

it says that I need to install the IC capture software but it is only available for windows and I'm using linux. 
I'm guessing that I have to write my own gstream module or something like that to enable the triggers.

Has anyone done this or have any ideas on how to do this?

**Comment by TIS-Stefan** [comment]
Installing IC Capture is indeed for Windows. 

I think, a nice start is using the UVC Extension, so you have access to all camera properties. Please refer to
https://github.com/TheImagingSource/tiscamera/wiki/UVC-Extension-Units

The second step is building the gstreamer modules as shown at https://github.com/TheImagingSource/tiscamera/wiki/Getting-Started-with-USB-2.0-cameras-on-a-Raspberry-PI-or-on-other-Linux-Systems

This could be followed by a simple demo program:
https://github.com/TheImagingSource/tiscamera/tree/master/examples/showcamera

If the UVC Extension unit is installed correctly you will see the trigger checkbox and software trigger button in the "Properties" dialog. If the trigger check box is checked, you can do software trigger and hardware trigger. 
For demonstrating the showcamera is nice, but for real development it is somewhat weird.

Stefan
