### ISSUE TITLE
UDEV Extensions

### ISSUE THREAD

**Issue by Ishtar-UK** [TheImagingSource/tiscamera#70]
Hello TIS

I am trying to install the udev extensions on a DFK21AU04 but running the following command on Fedora 24, kernel version 4.6 generates the following errors. Any idea what I am doing wrong.

Kind Regards
Amanda

uvcdynctrl -i ./tisEUVC.xml -d /dev/video1

[root@fedora-asys-it uvc-extensions]# uvcdynctrl -i ./tisEUVC.xml -d /dev/video1
[libwebcam] Unknown V4L2 user control ID encountered: 0x0098090E (V4L2_CID_USER_BASE + 14)
[libwebcam] Unknown V4L2 user control ID encountered: 0x0098090F (V4L2_CID_USER_BASE + 15)
Importing dynamic controls from file ./tisEUVC.xml.
./tisEUVC.xml: error: video1: unable to map 'ExtIO' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
./tisEUVC.xml: error: video1: unable to map 'GainR' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
./tisEUVC.xml: error: video1: unable to map 'GainG' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
./tisEUVC.xml: error: video1: unable to map 'GainB' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
./tisEUVC.xml: error: video1: unable to map 'Trigger' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
./tisEUVC.xml: error: video1: unable to map 'Trigger Global Reset Shutter' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
./tisEUVC.xml: error: video1: unable to map 'Software Trigger' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
./tisEUVC.xml: error: video1: unable to map 'Binning' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
./tisEUVC.xml: error: video1: unable to map 'Skipping' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
./tisEUVC.xml: error: video1: unable to map 'X Offset' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)
./tisEUVC.xml: error: video1: unable to map 'Y Offset' control. ioctl(UVCIOC_CTRL_MAP) failed with return value -1 (error 2: No such file or directory)

**Comment by TIS-Stefan** [comment]
Hello Amanda

the "errors" can be ignored, they are more warnings than errors. The DFK 21AU04 does not have these properties as they are defined in the extension file.
