### ISSUE TITLE
gst launch set property problem and some problem...

### ISSUE THREAD

**Issue by hwanil** [TheImagingSource/tiscamera#73]
Hi

I'm using dmm72buc02-ml sensor in raspberry Pi.

I'm using sensor with shell script.

gst-launch v4l2 ...

How can i set property value?

For example, brightness, contrast,gain, exposure, auto reference, auto max value, sharpness, gamma, denoise..

And, other problem...

I can't get data with 2592x1944

I can get data with 1280x720 or 1920x1080 but can't 2592x1944

How Can i get that data???

I want to example about these problem or shell script document about gst-launch...

**Comment by TIS-Stefan** [comment]
Hi

If you do not get images in the highest resolution, you should lower the frame rates:

gst-launch-0.10 v4l2src ! video/x-raw-gray,width=2592,height=1944,framerate=3/1 ! (...)

If you want to set the camera properties, you can use v4l2-ctl:

v4l2-ctl -c gain=4

This belongs to the v4l-utils package.

Stefan
