### ISSUE TITLE
DMK 21AU04: Terminate a long exposure

### ISSUE THREAD

**Issue by Ishtar-UK** [TheImagingSource/tiscamera#74]
I have written software to control the DMK* / DFK* cameras specifically for Astronomical Imaging. It is using raw V4L2, not GStreamer. Sometimes a user accidentally sets an exposure of 1 minute and then has to wait until the camera has finished exposing. Is it possible to terminate the exposure early? If so, what V4L2 call should I make?

I hope somebody can help and, as always, I appreciate any help offered.
Amanda

**Comment by TIS-Stefan** [comment]
Good Morning.

I am very sorry, but there is no way to interrupt the camera exposure. The method with best effect is disconnect and reconnect... (do not take that too serious, even if that works.)

Stefan
