### ISSUE TITLE
Partial scan | DFK72AUC02

### ISSUE THREAD

**Issue by fliewatueuet** [TheImagingSource/tiscamera#75]
Using your MS Software "IC Capture-2.4" it is possible to define an area which will be scanned with a higher frame-rate (e.g.: 2592x96 @ ~100fps).
Is this feature also available using tiscamera (tcambin/tcamsrc/v4l2-ctl/uvcdynctrl)?

We've tried to set it... 
... as "capsfilter" for gstreamer:
`gst-launch-1.0 --gst-debug=tcambin:5 tcambin ! video/x-bayer,width=2592,height=96,framerate=90/1,format=grbg ! bayer2rgb ! videoconvert ! autovideosink`

...via tcam-ctrl
(after we fixed the set-function)

and `v4l2-ctl --set-fmt-video` command
but until now we were not able to get the partial scan working.

Could you give us an advice, please?
Thank you for any help you can provide!

**Comment by TIS-Stefan** [comment]
Hello

v4l2 does not support variable resolutions, as DirectShow. Therefore, there is a limited list of resolutions available only in Linux. However, using lower resolutions leads to higher frame rates.

Using the the tcam-ctrl program you can see the available video formats and frame rates.

Also you can shorten your pipeline:

st-launch-1.0 --gst-debug=tcambin:5 tcambin ! video/x-raw, width=1024,height=768 ,framerate=60/1,format=RGB ! videoconvert ! autovideosink

The debayering is done in the tcambin.
