### ISSUE TITLE
Showcamera example is not working

### ISSUE THREAD

**Issue by Kidong** [TheImagingSource/tiscamera#77]
Hello there,

I'm trying to run the Showcamera example with DFK 42BUC03-ML.
The showcamera program lists the camera, but when I press start button it display below screen captured images.

![sc1](https://cloud.githubusercontent.com/assets/7202696/22131691/542ff260-def8-11e6-8a67-8ee69289e56f.png)

![sc2](https://cloud.githubusercontent.com/assets/7202696/22131702/64c5e6ac-def8-11e6-8acd-f5188dd1090b.png)

FYI, guvcview is working fine with this camera but whitebalance parameters are not display.

**Comment by TIS-Stefan** [comment]
Hello

I think, the output of the program clearly says, all needed modules are missing. "bla bla is null". So you may follow the manual at  https://github.com/TheImagingSource/tiscamera/wiki/Getting-Started-with-USB-2.0-cameras-on-a-Raspberry-PI-or-on-other-Linux-Systems
Please keep in mind, the show camera sample and the wiki entry is for gstreamer 0.10. The current tiscamera is for Gstreamer 1.0 and I did not find the time to create a nice graphical application.

**Comment by Kidong** [comment]
Thank you.
