### ISSUE TITLE
Support for Aravis 0.5.6

### ISSUE THREAD

**Issue by Ape** [TheImagingSource/tiscamera#78]
The latest stable Aravis release is 0.5.6, but tiscamera seems to require 0.4.0.

**Comment by TIS-Stefan** [comment]
Yes, we found this too.

**Comment by EmmanuelP** [comment]
@Ape 

> The latest stable Aravis release is 0.5.6, but tiscamera seems to require 0.4.0.

0.5.6 is a development version of Aravis. The current stable release is 0.4.1.
