### ISSUE TITLE
gstreamer-0.10 tis_auto_exposure stucks

### ISSUE THREAD

**Issue by fehlfarbe** [TheImagingSource/tiscamera#80]
Hi,

I tried to capture long exposure frame with the new gstreamer-1.0 pipeline but this didn't work (see: https://github.com/TheImagingSource/tiscamera/issues/76)

So I changed to the old gstreamer-0.10 pipeline that worked some months ago. I compiled gstreamer, gstreamer-plugins-base, gstreamer-plugins-good and gstreamer-plugins-bad on my fresh installed Ubuntu 16.04 ARM machine and then I followed the guide at https://github.com/TheImagingSource/tiscamera/wiki/Getting-Started-with-USB-2.0-cameras-on-a-Raspberry-PI-or-on-other-Linux-Systems to compile and install the TIS gstreamer-0.10 pipeline.

But when I start the pipeline with my DFK 72AUC02 gstreamer just waits but doesn't show/save any images:
```bash
pi@orangepizero:~/src/tiscamera-0.10/src$ GST_DEBUG=tis_auto_exposure:8 gst-launch v4l2src ! video/x-raw-gray,width=2592,height=1944,framerate=5/1 ! tisvideobufferfilter ! tis_auto_exposure ! tiscolorize ! queue ! tiswhitebalance ! queue ! bayer2rgb ! queue ! ffmpegcolorspace ! jpegenc ! multifilesink max-files=20 location="%05d.jpg"
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
0:00:02.427365737  3496   0xf51720 DEBUG      tis_auto_exposure gsttis_auto_exposure.c:394:gst_tis_auto_exposure_fixate_caps:<tis_auto_exposure0> trying to fixate outgoing video/x-raw-gray, bpp=(int)8, width=(int)2592, height=(int)1944, interlaced=(boolean)false, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)5/1 based on caps video/x-raw-gray, bpp=(int)8, width=(int)2592, height=(int)1944, interlaced=(boolean)false, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)5/1
0:00:02.428946049  3496   0xf51720 WARN       tis_auto_exposure tis_auto_exposure:471:gst_tis_auto_exposure_fixate_caps: Structure name video/x-raw-gray
```

I found the problem in https://github.com/TheImagingSource/tiscamera/blob/gstreamer-0.10/src/gsttis_auto_exposure.c#L583
It can't read the camera exposure/gain values and stucks in an endless loop ( `ioctl(fd, VIDIOC_G_CTRL, &ctrl)` returns -1 ).

There's also the problem that v4l2-ctl can't read the gain values but reading absolute exposure is working:
```bash
pi@orangepizero:~/src/tiscamera-0.10/src$ v4l2-ctl --all
Driver Info (not using libv4l2):
	Driver name   : uvcvideo
	Card type     : DFK 72AUC02
	Bus info      : usb-sunxi-ehci-1.4
	Driver version: 1.1.1
	Capabilities  : 0x04000001
		Video Capture
		Streaming
Video input : 0 (Camera 1: ok)
Format Video Capture:
	Width/Height      : 2592/1944
	Pixel Format      : 'GREY'
	Field             : None
	Bytes per Line    : 2592
	Size Image        : 5038848
	Colorspace        : Default
	Transfer Function : Default
	YCbCr Encoding    : Default
	Quantization      : Default
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 2592, Height 1944
	Default     : Left 0, Top 0, Width 2592, Height 1944
	Pixel Aspect: 1/1
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 5.000 (5/1)
	Read buffers     : 0
error 22 getting ctrl Brightness
error 22 getting ctrl Gain
              exposure_absolute (int)    : min=1 max=300000 step=1 default=127 value=127
                 focus_absolute (int)    : min=0 max=1000 step=1 default=0 value=0
                        privacy (bool)   : default=0 value=0
```

My camera:
```bash
pi@orangepizero:~/src/tiscamera-0.10/tools/firmware-update$ sudo ./firmware-update -id xxx

Device manufacturer: The Imaging Source Europe GmbH
Product name:        DFK 72AUC02
Serial number:       xxx
VendorID:ProductID:  199e:8207
Firmware version:    196
UVC mode is:         on
```
My system:
```bash
pi@orangepizero:~/src/tiscamera-0.10/tools/firmware-update$ uname -a
Linux orangepizero 3.4.113-sun8i #10 SMP PREEMPT Thu Feb 23 19:55:00 CET 2017 armv7l armv7l armv7l GNU/Linux
```

Looks like a problem in the v4l2 driver or camera!?
I also tried to set exposure time with v4l2-ctl and capture images with OpenCV but that also stucks from time to time. With GUVCView I can change absolute exposure and gain without problems but I need some way to read and process the image data with OpenCV.

**Comment by TIS-Stefan** [comment]
Hello

you may install the UVC Extension Unit in order to get all camera properties. https://github.com/TheImagingSource/tiscamera/wiki/UVC-Extension-Units

But I wonder why you use the auto exposure module, if you not use auto exposure, which is my understanding. 
You can set the properties with v4l2-ctl.
