### ISSUE TITLE
DFK23U445, Hardware trigger supported also for Linux (Ubuntu 16.04)?

### ISSUE THREAD

**Issue by koichiHik** [TheImagingSource/tiscamera#82]
Hello Stefan,

I am thinking to buy DFK23U445 to create my own stereo cam. I bought before DFK23UM021 for the same purpose, but realized the hardware level synchronization was necessary. So, can you let me know if hardware trigger is supported for DFK23U445 also for linux??

Thank you,
Koichi

**Comment by TIS-Stefan** [comment]
Hello Koichi

yes, hardware trigger is supported. You may need to install the UVC Extension for letting v4l2 know about the trigger properties.  https://github.com/TheImagingSource/tiscamera/wiki/UVC-Extension-Units
