### ISSUE TITLE
Won't compile on Raspberry Pi standard installation

### ISSUE THREAD

**Issue by NMCity** [TheImagingSource/tiscamera#85]
in tools/firmware-update/33u/Archive.cpp <codecvt> is used. 

The Reason is descripte here: http://stackoverflow.com/a/15615190/7568926

so maybe there is a workaround needed, so long raspbian use gcc 4.9.2.

**Comment by davidgt** [comment]
I'm having the same issue compiling in debian using gcc 4.9

missing codecvt.

**Comment by TIS-Edgar** [comment]
Hi,

The issue has been dealt with. If you pull and recompile you should now not face any problems.

**Comment by davidgt** [comment]
Hi,

I installed gcc 6 and now is fine.

Thanks Edgar.
