### ISSUE TITLE
Pipeline Problem

### ISSUE THREAD

**Issue by matheusns** [TheImagingSource/tiscamera#88]
Hi,

Camera = Teledyne Dalsa Genie Nano C2590
System = Linux Ubuntu 16.10

I'm trying to use the Aravis pipeline and when a run that:
```bash
./gst-aravis-launch aravissrc camera-name="Teledyne\ DALSA-S1112934" ! videoconvert ! xvimagesink sync="false"
```
I have been supposing that the dimensions are wrong, because it's a High Resolution Camera. How can I fix that? 

Congrats for the job!

Thanks!

**Comment by TIS-Stefan** [comment]
Hello

I am very sorry, but there is no error message! Thus, nothing to fix.

Maybe it is a good idea to use ' instead of "

**Comment by TIS-Arne** [comment]
This is not even one of our cameras o.O
