### ISSUE TITLE
cmake failed

### ISSUE THREAD

**Issue by DragonSmile** [TheImagingSource/tiscamera#89]
**when i did  cmake command, it always throwing such an error.**
**the os i used is ubuntu16.04**
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBZIP_INCLUDE_DIR
   used as include directory in directory /home/xjm/Desktop/tiscamera/src/tcam-network
   used as include directory in directory /home/xjm/Desktop/tiscamera/src/tcam-network
   used as include directory in directory /home/xjm/Desktop/tiscamera/src/tcam-network
   used as include directory in directory /home/xjm/Desktop/tiscamera/src/tcam-network
   used as include directory in directory /home/xjm/Desktop/tiscamera/src/tcam-network
   used as include directory in directory /home/xjm/Desktop/tiscamera/src/tcam-network
   used as include directory in directory /home/xjm/Desktop/tiscamera/src/tcam-network
   used as include directory in directory /home/xjm/Desktop/tiscamera/src/tcam-network
   used as include directory in directory /home/xjm/Desktop/tiscamera/src/tcam-network
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update/33u
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update/33u
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update/33u
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update/33u
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update/33u
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update/33u
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update/33u
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update/33u
   used as include directory in directory /home/xjm/Desktop/tiscamera/tools/firmware-update/33u
LIBZIP_LIBRARY
    linked by target "tcam-network" in directory /home/xjm/Desktop/tiscamera/src/tcam-network
    linked by target "firmware-update" in directory /home/xjm/Desktop/tiscamera/tools/firmware-update

**And here is the cmake error log**

> -- libudev stable: 1
-- Found UDev: /usr/lib/x86_64-linux-gnu/libudev.so
--    include: /usr/include
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/x86_64-linux-gnu/libusb-1.0.so
-- Checking for module 'aravis-0.6'
--   No package 'aravis-0.6' found
-- Found aravis 
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/x86_64-linux-gnu/libusb-1.0.so
-- libudev stable: 1
-- Found UDev: /usr/lib/x86_64-linux-gnu/libudev.so
--    include: /usr/include
-- 
-- Build gstreamer-1.0 plugins:   ON
-- Support for GigE via aravis:   ON
-- Support for USB cameras:       ON
-- Build additional utilities:    ON
-- 
-- Installation prefix:           /usr
-- Installing binaries to:        /usr/bin
-- Installing libraries to        /usr/lib
-- Installing header to:          /usr/include
-- Installing udev rules to:      /usr/lib/udev/rules.d
-- Installing uvcdynctrl rules to:/usr/share/uvcdynctrl/data/199e
-- Installing gstreamer-1.0 to:   /usr/lib/x86_64-linux-gnu/gstreamer-1.0
-- Installing gobject-introspection to: /usr/share/gir-1.0
-- Installing introspection typelib to: /usr/lib/x86_64-linux-gnu/girepository-1.0
-- 
-- Configuring incomplete, errors occurred!
See also "/home/xjm/Desktop/tiscamera/build/CMakeFiles/CMakeOutput.log".

**I have checked  the CMakeOutput.log but get nothing *_*!**
**it seems that lacking some third lbraries  and how can i deal it ?**

Thanks very much!!

**Comment by TIS-Stefan** [comment]
Hello 

sorry for the late reply. Did you follow the instructions at https://github.com/TheImagingSource/tiscamera and install all needed libs?

Stefan
