### ISSUE TITLE
DFK AFU420-L62 in Ubuntu 17.04

### ISSUE THREAD

**Issue by kaa-it** [TheImagingSource/tiscamera#93]
I want to install the cameras DFK AFU420-L62 in Ubuntu 17.04, when I connect I get the message:

[   12.485894] uvcvideo: Found UVC 0.00 device DFK AFU420-L62 (199e:0804)
[   12.485899] uvcvideo: No valid video chain found.

I have udev rules defined.

When I try to detect the camera with tcam-ctrl, I get the message:
No device found.

How I can use this camera under Linux?
Perhaps, I need a special library like libafo050 ?
Thank you for help!

**Comment by TIS-Edgar** [comment]
Hi,

The DFK AFU420-L62 currently has no Linux support. 
It does not offer a UVC mode. A special library similar to libabu050 is in the working and should arrive within the next months.

I am sorry for the inconvenience.
