### ISSUE TITLE
DFK AFUJ003-M12

### ISSUE THREAD

**Issue by makabe0510** [TheImagingSource/tiscamera#98]
I`m trying to use DFK AFUJ003-M12 to use pipeline like

gst-launch-1.0 tcambin ! videoconvert ! autovideosink

Then, I can see the window popping up but that window is white. (I attach the picture of screen shot of that.)

It seems normal log is displayed in terminal.

Using other computer, I did well in this way.  

How can I display movie from DFK AFUJ003-M12 ?

DFK AFUJ003-M12
![screenshot from 2017-06-21 19 47 09](https://user-images.githubusercontent.com/18542593/27380806-89136292-56bb-11e7-8082-d761da5ed1f1.png)DFK AFUJ003-M12

**Comment by TIS-Stefan** [comment]
Hello

Is the other computer a Linux system too? If yes, what is the difference between them?

Also I would like to know, which computer model you use, on which the camera does not provide a live video.

Thank you in advance!

Stefan

**Comment by makabe0510** [comment]
Thank you for your answer.

I use ubuntu 14.04.1 on Intel NUC (NUC7i7BNH).
I did well when I used ubuntu 14.04.5 on Intel NUC(NUC D34010WYK) using same camera.
I think difference between them is minor version of ubuntu.
Is this difference the matter?

**Comment by TIS-Stefan** [comment]
May be the difference is, the camera being connected to an USB 2.0 port only? What happens if you try a low resolution video format an a low frame rate? You can use the tcam-ctrl tool in order to query the camera's properties, video formats and frame rates.

Stefan

**Comment by TIS-Arne** [comment]
Closing this issue since we need feedback on Stefans questions. Please re-open when neccessary.
